import type { Course } from "@/lib/courses/kit";

/**
 * "Email, CRM, and Lifecycle Marketing with AI": course 6 of the AI Augmented Digital
 * Marketing program, not started. 34 topics in 3 modules, none done; Module 3 is locked
 * until Module 2 is complete. It opens on "Course Introduction", as the Program page says.
 */
export const outline: Course = {
  id: "crm",
  slug: "email-crm-and-lifecycle-marketing-with-ai",
  title: "Email, CRM, and Lifecycle Marketing with AI",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Beginner",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 0,
  modulesCompleted: 0,
  modulesTotal: 3,
  modules: [
    {
      id: "crm-m1",
      label: "MODULE 01",
      title: "Email Foundations & Deliverability",
      topicsCompleted: 0,
      topicsTotal: 12,
      isCompleted: false,
      lessons: [
        {
          id: "crm-m1-l1",
          label: "Permission and the inbox",
          topics: [
            {
              id: "crm-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "6 min",
              completed: false,
              transcript: [
                { id: "crm-m1-t1-ln1", ts: "0:00", text: "Welcome to course 6. The channels you have studied so far bring people to the brand. This course is about what happens after they arrive: the messages you send to people who asked to hear from you." },
                { id: "crm-m1-t1-ln2", ts: "0:20", text: "Email is the main one. It is the only large channel where you own the audience: a list of people who gave you their address and can take it back at any time." },
                { id: "crm-m1-t1-ln3", ts: "0:37", text: "Module 1 covers the foundations: permission, how a message reaches the inbox or fails to, and how to write an email that gets opened." },
                { id: "crm-m1-t1-ln4", ts: "0:52", text: "Module 2 adds the customer record. A CRM stores who each person is and what they have done, and that is what lets you send different messages to different people, automatically." },
                { id: "crm-m1-t1-ln5", ts: "1:10", text: "Module 3 is where AI does the most work: personalisation, send times, subject lines and testing. It ends with your final project, a lifecycle email plan for one customer journey." },
                { id: "crm-m1-t1-ln6", ts: "1:29", text: "One rule runs through the course. An AI assistant can draft an email in seconds, but it cannot tell you whether the person agreed to receive it. Permission is always your job." },
                { id: "crm-m1-t1-ln7", ts: "1:47", text: "You do not need an email platform to follow along. The sample contact list and the flow templates are in Handouts. Let's begin with why email still pays." },
              ],
            },
            { id: "crm-m1-t2", type: "Reading", title: "Why email still pays: an audience you own", duration: "approx. 12 min read", completed: false },
            {
              id: "crm-m1-t3",
              type: "Video",
              title: "How an email reaches the inbox: authentication, reputation, filters",
              duration: "16 min",
              completed: false,
              transcript: [
                { id: "crm-m1-t3-ln1", ts: "0:00", text: "Pressing send does not put an email in anyone's inbox. It hands the message to the receiving mail provider, which then decides: inbox, promotions tab, spam folder, or refuse it altogether. Three things shape that decision." },
                { id: "crm-m1-t3-ln2", ts: "0:24", text: "The first is authentication: proof that the message really comes from your domain. There are three records, all published in your domain's settings." },
                { id: "crm-m1-t3-ln3", ts: "0:39", text: "SPF lists the servers allowed to send for your domain. DKIM adds a signature to each message that shows it was not altered on the way. DMARC tells the receiver what to do when a check fails, and where to send reports." },
                { id: "crm-m1-t3-ln4", ts: "1:07", text: "Large mailbox providers now expect all three from anyone who sends in bulk. Without them, your messages are easy to forge and likely to be filtered." },
                { id: "crm-m1-t3-ln5", ts: "1:24", text: "The second is reputation. Receivers keep a score for your domain and your sending address, built from how people treat your mail. Opens, replies and moving a message out of spam raise it." },
                { id: "crm-m1-t3-ln6", ts: "1:46", text: "Spam complaints, messages to addresses that do not exist, and long runs of unopened mail lower it. A complaint rate above about three in a thousand is a warning sign." },
                { id: "crm-m1-t3-ln7", ts: "2:06", text: "The third is the filter itself, which reads each message for signs of trouble: a misleading subject line, a single large image with no text, links to doubtful sites." },
                { id: "crm-m1-t3-ln8", ts: "2:25", text: "Notice what is missing from the list: clever tricks. Deliverability is authentication you set up once, and reputation you earn by sending wanted mail to people who asked for it." },
              ],
            },
            { id: "crm-m1-t4", type: "Reading", title: "Consent, unsubscribes and the rules you must follow", duration: "approx. 14 min read", completed: false },
            {
              id: "crm-m1-t5",
              type: "Video",
              title: "Growing a list without buying one: forms, offers and double opt-in",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "crm-m1-t5-ln1", ts: "0:00", text: "A bought list looks like a shortcut: fifty thousand addresses by this afternoon. None of those people asked to hear from you. They complain, your reputation falls, and your real subscribers stop receiving your mail. So we grow the list ourselves." },
                { id: "crm-m1-t5-ln2", ts: "0:27", text: "Begin with the places people already are. The footer of the site, the checkout, the end of a helpful article, the profile link on social media. Put a form in each." },
                { id: "crm-m1-t5-ln3", ts: "0:48", text: "Ask for as little as possible. An email address, perhaps a first name. Every extra field loses sign-ups, and you can learn more once the person is a subscriber." },
                { id: "crm-m1-t5-ln4", ts: "1:07", text: "Give a reason. Join our newsletter is not one. Ten percent off your first order is. So is a five-day email course on brewing better coffee, or first notice of new stock." },
                { id: "crm-m1-t5-ln5", ts: "1:28", text: "Choose the offer with the customer you want in mind. A big discount attracts people who wait for discounts. A useful guide attracts people interested in the subject." },
                { id: "crm-m1-t5-ln6", ts: "1:47", text: "Say on the form what they will get and how often. One email a week, recipes and offers. That sentence is your consent wording, so keep a copy." },
                { id: "crm-m1-t5-ln7", ts: "2:06", text: "Then confirm. With double opt-in, the new subscriber gets one email with a button to confirm the address. It catches typing errors and fake sign-ups, and gives you clean proof of consent." },
                { id: "crm-m1-t5-ln8", ts: "2:27", text: "You will lose some people at that step. The ones who remain open more and complain less. A list is judged by how many people read, not by how many addresses it holds." },
              ],
            },
            { id: "crm-m1-t6", type: "Activity", title: "Check a sending domain against the deliverability checklist", duration: "approx. 20 min", completed: false },
          ],
        },
        {
          id: "crm-m1-l2",
          label: "Emails people open",
          topics: [
            { id: "crm-m1-t7", type: "Reading", title: "Subject lines, preview text and sender names", duration: "approx. 12 min read", completed: false },
            {
              id: "crm-m1-t8",
              type: "Video",
              title: "Drafting an email with an AI assistant: brief, draft, edit",
              duration: "16 min",
              completed: false,
              transcript: [
                { id: "crm-m1-t8-ln1", ts: "0:00", text: "An assistant can write an email in ten seconds. Whether it is an email worth sending depends on what you do before and after. We will work in three steps: brief, draft, edit." },
                { id: "crm-m1-t8-ln2", ts: "0:22", text: "The brief comes first, and it is written by you. One reader: someone who signed up yesterday through the plant care guide. One purpose: get them to read the first care tip. One action: click through to the watering guide." },
                { id: "crm-m1-t8-ln3", ts: "0:49", text: "Add the facts the assistant cannot know. The guide covers twelve plants. The shop ships in two days. And the voice: friendly, plain, no exclamation marks." },
                { id: "crm-m1-t8-ln4", ts: "1:06", text: "Now the prompt asks for the draft. A welcome email of up to one hundred and twenty words, a subject line and preview text, one link, and no claims beyond the facts supplied." },
                { id: "crm-m1-t8-ln5", ts: "1:28", text: "Read the draft against the brief. Is there one action, or three? Ours added a discount nobody offered and a line about award-winning service. Both come out." },
                { id: "crm-m1-t8-ln6", ts: "1:46", text: "Then edit for voice. The draft opens with we are thrilled to have you. Nobody talks like that. Rewrite the first line as you would say it to a customer at the counter." },
                { id: "crm-m1-t8-ln7", ts: "2:08", text: "Check the working parts: the link goes where it should, the name field has a fallback for contacts with no first name, and the unsubscribe link is there." },
                { id: "crm-m1-t8-ln8", ts: "2:27", text: "Last, send it to yourself and read it on a phone. The assistant produced the words. The brief, the facts, the voice and the decision to send are yours." },
              ],
            },
            { id: "crm-m1-t9", type: "Practice Assignment", title: "Practice Quiz: Deliverability and consent", duration: "approx. 10 min", completed: false },
            { id: "crm-m1-t10", type: "Reading", title: "Designing for small screens, dark mode and screen readers", duration: "approx. 12 min read", completed: false },
            { id: "crm-m1-t11", type: "Graded Assignment", title: "Assignment 01 · Welcome series", duration: "approx. 45 min", completed: false },
            { id: "crm-m1-t12", type: "Quiz", title: "Graded Quiz: Email foundations", duration: "approx. 10 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "crm-m2",
      label: "MODULE 02",
      title: "CRM, Segmentation & Lifecycle Automation",
      topicsCompleted: 0,
      topicsTotal: 12,
      isCompleted: false,
      lessons: [
        {
          id: "crm-m2-l1",
          label: "One record per customer",
          topics: [
            {
              id: "crm-m2-t1",
              type: "Video",
              title: "What a CRM holds: contacts, events and properties",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "crm-m2-t1-ln1", ts: "0:00", text: "CRM stands for customer relationship management. Behind the name is a simple thing: one record for each person, holding who they are and what they have done. Three kinds of data make up that record." },
                { id: "crm-m2-t1-ln2", ts: "0:23", text: "The first is the contact itself: an email address, usually the key that identifies the person, with a name and their consent status. Whether they may be emailed, and since when, belongs on the record." },
                { id: "crm-m2-t1-ln3", ts: "0:46", text: "The second is properties. These are facts that describe the contact now: country, preferred language, lifecycle stage, date of last order, total spent. A property has one current value." },
                { id: "crm-m2-t1-ln4", ts: "1:05", text: "The third is events. An event is something that happened, with a time: opened an email, viewed a product, added to cart, placed an order, contacted support. Events pile up as a history." },
                { id: "crm-m2-t1-ln5", ts: "1:27", text: "The difference matters. Total spent is a property. Each order is an event. The property is worked out from the events, and it answers a question quickly." },
                { id: "crm-m2-t1-ln6", ts: "1:45", text: "Data arrives from several places: the shop, the email tool, forms, the support desk. The CRM's job is to join them on one person. If the shop knows Dana by one address and the form by another, you have two half-customers." },
                { id: "crm-m2-t1-ln7", ts: "2:12", text: "Everything in the next lessons is built from these parts. A segment is a filter on properties and events. A flow is a message triggered by an event." },
                { id: "crm-m2-t1-ln8", ts: "2:31", text: "So before any automation, open one contact record and read it. If you cannot tell from it what this person has done, neither can your emails." },
              ],
            },
            { id: "crm-m2-t2", type: "Reading", title: "Lifecycle stages: from subscriber to repeat customer", duration: "approx. 14 min read", completed: false },
            {
              id: "crm-m2-t3",
              type: "Video",
              title: "Segmenting by behaviour: recency, frequency and value",
              duration: "16 min",
              completed: false,
              transcript: [
                { id: "crm-m2-t3-ln1", ts: "0:00", text: "The most useful way to divide a customer list uses three numbers you already have. Recency: how long since the last order. Frequency: how many orders. Value: how much they have spent. Together they are known as RFM." },
                { id: "crm-m2-t3-ln2", ts: "0:25", text: "Recency is usually the strongest of the three. Someone who bought last week is far more likely to buy again than someone who last bought a year ago, whatever else you know about them." },
                { id: "crm-m2-t3-ln3", ts: "0:48", text: "Frequency separates a one-time buyer from a regular. Value separates small baskets from large ones." },
                { id: "crm-m2-t3-ln4", ts: "0:58", text: "A simple method: score each customer from one to three on each measure. A last order within thirty days scores three for recency. Within ninety, two. Longer, one. Do the same for number of orders and for total spent." },
                { id: "crm-m2-t3-ln5", ts: "1:24", text: "Now read the combinations. Three, three, three: your best customers, recent, frequent and high-spending. Thank them and give them early access. Do not send them a discount they do not need." },
                { id: "crm-m2-t3-ln6", ts: "1:45", text: "Three, one, one: new customers, recent, with a single small order. They need the nudge to a second purchase." },
                { id: "crm-m2-t3-ln7", ts: "1:58", text: "One, three, three is the group to worry about: people who used to buy often and spend well, and have stopped. A win-back message here is worth more than anywhere else on the list." },
                { id: "crm-m2-t3-ln8", ts: "2:21", text: "And one, one, one: bought once, long ago, a small amount. Email them rarely, or stop. In the activity you build three of these segments from the sample contact list." },
              ],
            },
            { id: "crm-m2-t4", type: "Reading", title: "Keeping data clean: duplicates, bounces and stale contacts", duration: "approx. 12 min read", completed: false },
            { id: "crm-m2-t5", type: "Activity", title: "Build three segments from the sample contact list", duration: "approx. 25 min", completed: false },
            { id: "crm-m2-t6", type: "Practice Assignment", title: "Practice Quiz: Segments and lifecycle stages", duration: "approx. 10 min", completed: false },
          ],
        },
        {
          id: "crm-m2-l2",
          label: "Automated flows",
          topics: [
            {
              id: "crm-m2-t7",
              type: "Video",
              title: "Triggers, delays and exits: how a flow is built",
              duration: "16 min",
              completed: false,
              transcript: [
                { id: "crm-m2-t7-ln1", ts: "0:00", text: "A flow is a set of instructions: when this happens, wait this long, send this, unless that. Every flow, however large, is made of the same few parts. We will build one to see them: the abandoned cart reminder." },
                { id: "crm-m2-t7-ln2", ts: "0:26", text: "The trigger starts it. Here, the event added to cart. The moment a known contact adds a product, they enter the flow." },
                { id: "crm-m2-t7-ln3", ts: "0:41", text: "Then a delay. Do not write at once, because they may still be shopping. Wait one hour." },
                { id: "crm-m2-t7-ln4", ts: "0:52", text: "Before sending, a condition. Has an order been placed since the trigger? If yes, the contact leaves the flow. This check is the most important line in the whole design." },
                { id: "crm-m2-t7-ln5", ts: "1:12", text: "If not, the first message goes out: you left this behind, with the product and a link back to the cart. Then another delay of a day, the same check, and a second message that answers a likely doubt, such as delivery time or returns." },
                { id: "crm-m2-t7-ln6", ts: "1:42", text: "Exits are the rules for leaving. Placing an order is one. Unsubscribing is another. So is reaching the end. A flow with no exit keeps reminding someone about a cart they paid for yesterday." },
                { id: "crm-m2-t7-ln7", ts: "2:05", text: "Add two guards. A re-entry rule, so that a person who fills three carts in a week gets one series and not three. And a frequency limit across all flows, so that the cart reminder and the newsletter do not land in the same hour." },
                { id: "crm-m2-t7-ln8", ts: "2:35", text: "Draw the flow on paper before you build it: trigger, delay, condition, message, exit. If you cannot draw it, the tool will not make it clearer." },
              ],
            },
            { id: "crm-m2-t8", type: "Reading", title: "The five flows most businesses need first", duration: "approx. 15 min read", completed: false },
            { id: "crm-m2-t9", type: "Video", title: "Abandoned cart and win-back flows, step by step", duration: "16 min", completed: false },
            { id: "crm-m2-t10", type: "Reading", title: "How often is too often: frequency caps and sunset rules", duration: "approx. 12 min read", completed: false },
            { id: "crm-m2-t11", type: "Graded Assignment", title: "Assignment 02 · Lifecycle map and segments", duration: "approx. 45 min", completed: false },
            { id: "crm-m2-t12", type: "Quiz", title: "Graded Quiz: CRM and automation", duration: "approx. 10 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "crm-m3",
      label: "MODULE 03",
      title: "AI Personalisation, Final Project, and Wrap-Up",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "crm-m3-l1",
          label: "Personalisation and testing with AI",
          topics: [
            { id: "crm-m3-t1", type: "Video", title: "Personalisation beyond the first name", duration: "14 min", completed: false, locked: true },
            { id: "crm-m3-t2", type: "Reading", title: "Using AI for send times, subject lines and product picks", duration: "approx. 15 min read", completed: false, locked: true },
            { id: "crm-m3-t3", type: "Video", title: "Testing an email: one variable, enough recipients, a clear winner", duration: "15 min", completed: false, locked: true },
            { id: "crm-m3-t4", type: "Reading", title: "Measuring email when open rates cannot be trusted", duration: "approx. 12 min read", completed: false, locked: true },
            { id: "crm-m3-t5", type: "Practice Assignment", title: "Practice Quiz: Testing and measurement", duration: "approx. 10 min", completed: false, locked: true },
          ],
        },
        {
          id: "crm-m3-l2",
          label: "Final project and assessment",
          topics: [
            { id: "crm-m3-t6", type: "Reading", title: "Final project brief: a lifecycle email plan", duration: "approx. 12 min read", completed: false, locked: true },
            { id: "crm-m3-t7", type: "Project", title: "Final Project: Lifecycle email plan", duration: "approx. 90 min", completed: false, locked: true },
            { id: "crm-m3-t8", type: "Peer Review", title: "Review two lifecycle email plans", duration: "approx. 25 min", completed: false, locked: true },
            { id: "crm-m3-t9", type: "Quiz", title: "Final Assessment", duration: "approx. 20 min", completed: false, locked: true },
            { id: "crm-m3-t10", type: "Video", title: "Course wrap-up and next steps", duration: "5 min", completed: false, locked: true },
          ],
        },
      ],
    },
  ],
};
