import type { Course } from "@/lib/courses/kit";

/**
 * "Network Security and Defence": course 2 of 5 of the Cybersecurity Fundamentals
 * Certificate, not started. 39 topics in 4 modules, none done: the player opens on
 * the first topic. Module 4 is locked until Module 3 is complete.
 */
export const outline: Course = {
  id: "sec2",
  slug: "network-security-and-defence",
  title: "Network Security and Defence",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Beginner",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 0,
  modulesCompleted: 0,
  modulesTotal: 4,
  modules: [
    {
      id: "sec2-m1",
      label: "MODULE 01",
      title: "How Networks Work",
      topicsCompleted: 0,
      topicsTotal: 9,
      isCompleted: false,
      lessons: [
        {
          id: "sec2-m1-l1",
          label: "Layers and addresses",
          topics: [
            {
              id: "sec2-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "6 min",
              completed: false,
              transcript: [
                {
                  id: "sec2-m1-t1-ln1",
                  ts: "0:00",
                  text: "Welcome to Network Security and Defence, the second course of the Cybersecurity Fundamentals Certificate.",
                },
                {
                  id: "sec2-m1-t1-ln2",
                  ts: "0:20",
                  text: "Almost every attack crosses a network at some point. If you can read what a network normally does, you can notice when it does something else.",
                },
                {
                  id: "sec2-m1-t1-ln3",
                  ts: "0:40",
                  text: "Module 1 gives you the working model: layers, addresses, ports and the protocols that turn names into connections.",
                },
                {
                  id: "sec2-m1-t1-ln4",
                  ts: "0:55",
                  text: "Module 2 looks at what goes wrong on a network and at segmentation, which limits how far a problem can spread.",
                },
                {
                  id: "sec2-m1-t1-ln5",
                  ts: "1:15",
                  text: "Module 3 covers the controls and the sensors: firewalls, intrusion detection, and the logs that show you what happened.",
                },
                {
                  id: "sec2-m1-t1-ln6",
                  ts: "1:30",
                  text: "Module 4 is about protecting data on the move: TLS, certificates, VPNs, email authentication and Wi-Fi.",
                },
                {
                  id: "sec2-m1-t1-ln7",
                  ts: "1:50",
                  text: "You will design a segmentation plan for a two-site office and review a peer's hardening checklist. No lab equipment is needed: every exercise uses diagrams and sample data.",
                },
              ],
            },
            {
              id: "sec2-m1-t2",
              type: "Reading",
              title: "The TCP/IP model in four layers",
              duration: "approx. 14 min read",
              completed: false,
            },
            {
              id: "sec2-m1-t3",
              type: "Video",
              title: "IP addresses, subnets and routing",
              duration: "14 min",
              completed: false,
            },
            {
              id: "sec2-m1-t4",
              type: "Reading",
              title: "Ports, protocols and what normal traffic looks like",
              duration: "approx. 13 min read",
              completed: false,
            },
            {
              id: "sec2-m1-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Network basics",
              duration: "approx. 8 min",
              completed: false,
            },
          ],
        },
        {
          id: "sec2-m1-l2",
          label: "Names and the local network",
          topics: [
            {
              id: "sec2-m1-t6",
              type: "Video",
              title: "DNS: how names become addresses",
              duration: "11 min",
              completed: false,
              transcript: [
                {
                  id: "sec2-m1-t6-ln1",
                  ts: "0:00",
                  text: "People remember names; networks route by address. The Domain Name System is the service that translates one into the other.",
                },
                {
                  id: "sec2-m1-t6-ln2",
                  ts: "0:20",
                  text: "When you open a site, your device asks a resolver for the address behind the name. The resolver asks other servers in turn, starting from the root, until one of them holds the answer.",
                },
                {
                  id: "sec2-m1-t6-ln3",
                  ts: "0:40",
                  text: "Answers are cached for a set time, so the next request is quick. That time is called the time to live.",
                },
                {
                  id: "sec2-m1-t6-ln4",
                  ts: "0:55",
                  text: "Defenders care about DNS for two reasons. First, almost every connection starts with a lookup, so DNS logs are a compact record of where devices tried to go.",
                },
                {
                  id: "sec2-m1-t6-ln5",
                  ts: "1:15",
                  text: "Second, DNS is a control point. A filtering resolver can refuse to answer for names known to host malicious content, which stops many connections before they begin.",
                },
                {
                  id: "sec2-m1-t6-ln6",
                  ts: "1:30",
                  text: "Things to watch for in DNS logs: a device that suddenly looks up many names that do not exist, names that look randomly generated, and lookups at hours when nobody is working.",
                },
                {
                  id: "sec2-m1-t6-ln7",
                  ts: "1:50",
                  text: "In the next reading you meet the protocols of the local network, DHCP and ARP, and see what they tell you about which device is which.",
                },
              ],
            },
            {
              id: "sec2-m1-t7",
              type: "Reading",
              title: "DHCP, ARP and the local network",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec2-m1-t8",
              type: "Activity",
              title: "Label the layers in a packet capture summary",
              duration: "approx. 15 min",
              completed: false,
            },
            {
              id: "sec2-m1-t9",
              type: "Quiz",
              title: "Graded Quiz: How networks work",
              duration: "approx. 12 min",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sec2-m2",
      label: "MODULE 02",
      title: "Network Threats and Segmentation",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "sec2-m2-l1",
          label: "What goes wrong on a network",
          topics: [
            {
              id: "sec2-m2-t1",
              type: "Video",
              title: "Eavesdropping, spoofing and denial of service",
              duration: "13 min",
              completed: false,
            },
            {
              id: "sec2-m2-t2",
              type: "Reading",
              title: "Why flat networks fail",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec2-m2-t3",
              type: "Video",
              title: "Trust zones: users, servers, guests and devices",
              duration: "12 min",
              completed: false,
            },
            {
              id: "sec2-m2-t4",
              type: "Reading",
              title: "VLANs, subnets and a DMZ",
              duration: "approx. 14 min read",
              completed: false,
            },
            {
              id: "sec2-m2-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Threats and zones",
              duration: "approx. 8 min",
              completed: false,
            },
          ],
        },
        {
          id: "sec2-m2-l2",
          label: "Designing the zones",
          topics: [
            { id: "sec2-m2-t6", type: "Video", title: "Zero trust in plain terms", duration: "11 min", completed: false },
            {
              id: "sec2-m2-t7",
              type: "Reading",
              title: "Securing network devices and their management",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec2-m2-t8",
              type: "Activity",
              title: "Place twenty devices into zones",
              duration: "approx. 20 min",
              completed: false,
            },
            {
              id: "sec2-m2-t9",
              type: "Graded Assignment",
              title: "Assignment 01 · Segmentation plan for a two-site office",
              duration: "approx. 60 min",
              completed: false,
            },
            {
              id: "sec2-m2-t10",
              type: "Quiz",
              title: "Graded Quiz: Threats and segmentation",
              duration: "approx. 12 min",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sec2-m3",
      label: "MODULE 03",
      title: "Firewalls, Detection and Monitoring",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "sec2-m3-l1",
          label: "Controlling traffic",
          topics: [
            { id: "sec2-m3-t1", type: "Video", title: "How a firewall decides", duration: "12 min", completed: false },
            {
              id: "sec2-m3-t2",
              type: "Reading",
              title: "Writing a rule base: default deny and rule order",
              duration: "approx. 15 min read",
              completed: false,
            },
            {
              id: "sec2-m3-t3",
              type: "Video",
              title: "Stateful inspection and application-aware filtering",
              duration: "12 min",
              completed: false,
            },
            {
              id: "sec2-m3-t4",
              type: "Activity",
              title: "Review a firewall rule base for gaps",
              duration: "approx. 20 min",
              completed: false,
            },
            {
              id: "sec2-m3-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Firewalls",
              duration: "approx. 8 min",
              completed: false,
            },
          ],
        },
        {
          id: "sec2-m3-l2",
          label: "Seeing what happens",
          topics: [
            {
              id: "sec2-m3-t6",
              type: "Video",
              title: "Intrusion detection and prevention systems",
              duration: "12 min",
              completed: false,
            },
            {
              id: "sec2-m3-t7",
              type: "Reading",
              title: "Flow records, DNS logs and proxy logs",
              duration: "approx. 13 min read",
              completed: false,
            },
            {
              id: "sec2-m3-t8",
              type: "Reading",
              title: "Tuning alerts: false positives and blind spots",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec2-m3-t9",
              type: "Video",
              title: "Baselines: knowing normal before spotting odd",
              duration: "10 min",
              completed: false,
            },
            {
              id: "sec2-m3-t10",
              type: "Quiz",
              title: "Graded Quiz: Firewalls and monitoring",
              duration: "approx. 12 min",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sec2-m4",
      label: "MODULE 04",
      title: "Secure Communication and Wireless",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "sec2-m4-l1",
          label: "Protecting data in transit",
          topics: [
            {
              id: "sec2-m4-t1",
              type: "Video",
              title: "Encryption in transit: what TLS provides",
              duration: "13 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec2-m4-t2",
              type: "Reading",
              title: "Certificates and the chain of trust",
              duration: "approx. 14 min read",
              completed: false,
              locked: true,
            },
            {
              id: "sec2-m4-t3",
              type: "Video",
              title: "VPNs and remote access",
              duration: "12 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec2-m4-t4",
              type: "Reading",
              title: "Email authentication: SPF, DKIM and DMARC",
              duration: "approx. 13 min read",
              completed: false,
              locked: true,
            },
            {
              id: "sec2-m4-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Secure communication",
              duration: "approx. 8 min",
              completed: false,
              locked: true,
            },
          ],
        },
        {
          id: "sec2-m4-l2",
          label: "Wireless and wrap-up",
          topics: [
            {
              id: "sec2-m4-t6",
              type: "Video",
              title: "Wi-Fi security: WPA3 and guest networks",
              duration: "12 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec2-m4-t7",
              type: "Reading",
              title: "Hardening a small office network: a checklist",
              duration: "approx. 12 min read",
              completed: false,
              locked: true,
            },
            {
              id: "sec2-m4-t8",
              type: "Peer-graded",
              title: "Network hardening review",
              duration: "approx. 45 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec2-m4-t9",
              type: "Quiz",
              title: "Graded Quiz: Secure communication and wireless",
              duration: "approx. 15 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec2-m4-t10",
              type: "Video",
              title: "Course wrap-up and what comes next",
              duration: "5 min",
              completed: false,
              locked: true,
            },
          ],
        },
      ],
    },
  ],
};
