import type { Course } from "@/lib/courses/kit";

/**
 * "AI-Driven Content and Brand Communication": course 2 of the AI Augmented Digital
 * Marketing program. 38 topics, 15 done: Module 1 complete, 3 of 10 in Module 2.
 */
export const outline: Course = {
  id: "acb",
  slug: "ai-driven-content-and-brand-communication",
  title: "AI-Driven Content and Brand Communication",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Beginner",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 40,
  modulesCompleted: 1,
  modulesTotal: 4,
  modules: [
    {
      id: "acb-m1",
      label: "MODULE 01",
      title: "Brand Strategy & Voice Systems",
      topicsCompleted: 12,
      topicsTotal: 12,
      isCompleted: true,
      lessons: [
        {
          id: "acb-m1-l1",
          label: "Brand strategy and voice",
          topics: [
            {
              id: "acb-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "6 min",
              completed: true,
              transcript: [
                { id: "acb-m1-t1-ln1", ts: "0:00", text: "Welcome to AI-Driven Content and Brand Communication. In this course you learn to produce content with AI tools that still sounds and looks like one brand." },
                { id: "acb-m1-t1-ln2", ts: "0:16", text: "The order matters. We start with the brand and bring in the tools second. An assistant given no direction writes fluent copy that could belong to anyone." },
                { id: "acb-m1-t1-ln3", ts: "0:30", text: "Module 1 covers brand strategy and voice. You define what the brand stands for and how it speaks, and you write that down as a system a person or a tool can follow." },
                { id: "acb-m1-t1-ln4", ts: "0:47", text: "Module 2 puts the voice to work on copy: briefs, prompts, long and short formats, audience segments and editing." },
                { id: "acb-m1-t1-ln5", ts: "1:01", text: "Module 3 does the same for visual content: image prompts, brand consistency, rights and accessibility. Module 4 is the final project, a brand content kit reviewed by two peers." },
                { id: "acb-m1-t1-ln6", ts: "1:19", text: "Along the way there are two graded assignments, two graded quizzes and a final assessment." },
                { id: "acb-m1-t1-ln7", ts: "1:29", text: "We use one case study throughout: Brightwell Refill, a fictional company that sells refillable household cleaning products by subscription. You can work on it, or on a brand you know." },
                { id: "acb-m1-t1-ln8", ts: "1:46", text: "You can follow the course with any general-purpose AI assistant. One rule applies from start to finish: the tool drafts, and you answer for what is published." },
              ],
            },
            { id: "acb-m1-t2", type: "Reading", title: "What a brand strategy decides", duration: "approx. 12 min read", completed: true },
            {
              id: "acb-m1-t3",
              type: "Video",
              title: "Positioning, promise and proof",
              duration: "14 min",
              completed: true,
              transcript: [
                { id: "acb-m1-t3-ln1", ts: "0:00", text: "Three ideas hold a brand strategy together: positioning, promise and proof. Each answers a different question a customer has." },
                { id: "acb-m1-t3-ln2", ts: "0:14", text: "Positioning answers “what are you, and for whom?”. It places the brand in a category and names the people it serves and what sets it apart from the alternatives." },
                { id: "acb-m1-t3-ln3", ts: "0:30", text: "A common template: for this audience, with this need, our brand is the category that offers this benefit, unlike the alternative." },
                { id: "acb-m1-t3-ln4", ts: "0:44", text: "For our case study: for households that want to cut plastic waste without extra effort, Brightwell Refill is the cleaning subscription that arrives before you run out, unlike refill shops you have to travel to." },
                { id: "acb-m1-t3-ln5", ts: "1:03", text: "The promise answers “what will I get, every time?”. It is the positioning in the customer's words, short enough to remember: clean home, no new plastic, no errands." },
                { id: "acb-m1-t3-ln6", ts: "1:19", text: "Proof answers “why should I believe you?”. These are facts a customer can check: the number of bottles reused, a delivery guarantee, an independent certification, customer ratings." },
                { id: "acb-m1-t3-ln7", ts: "1:36", text: "The three must line up. A promise with no proof is a slogan. Proof that supports no promise is trivia. And a positioning that nobody else would dispute, such as “high quality”, positions nothing." },
                { id: "acb-m1-t3-ln8", ts: "1:54", text: "Keep all three on one page. Every content brief you write in this course will draw on it." },
              ],
            },
            { id: "acb-m1-t4", type: "Reading", title: "Defining a brand voice: traits, tone and vocabulary", duration: "approx. 15 min read", completed: true },
            {
              id: "acb-m1-t5",
              type: "Video",
              title: "Turning a voice into a system: the voice chart",
              duration: "16 min",
              completed: true,
              transcript: [
                { id: "acb-m1-t5-ln1", ts: "0:00", text: "In the last reading you described a voice with three traits. A list of traits is a start. To be used, it has to become a tool, and the most practical one is the voice chart." },
                { id: "acb-m1-t5-ln2", ts: "0:17", text: "A voice chart is a table with one row per trait and four columns: the trait, what it means for this brand, what to do, and what to avoid." },
                { id: "acb-m1-t5-ln3", ts: "0:31", text: "Take “plain-spoken” for Brightwell Refill. Meaning: we explain things the way you would to a neighbour. Do: use short sentences, everyday words and concrete numbers." },
                { id: "acb-m1-t5-ln4", ts: "0:48", text: "Do not: use jargon such as “eco-conscious solutions”, or vague claims such as “better for the planet” with no figure attached." },
                { id: "acb-m1-t5-ln5", ts: "1:01", text: "The “do not” column does the most work. It marks where the trait tips over. Plain-spoken should never turn blunt. Warm should never turn gushing." },
                { id: "acb-m1-t5-ln6", ts: "1:16", text: "Add a fifth column with an example: one sentence written in the voice next to the same sentence written badly. People copy examples far more readily than they follow rules." },
                { id: "acb-m1-t5-ln7", ts: "1:32", text: "Then add a short section on tone. The voice stays the same, and the tone shifts with the situation: lighter in a welcome email, calmer and more direct in a message about a late delivery." },
                { id: "acb-m1-t5-ln8", ts: "1:49", text: "Finally, list the vocabulary: words the brand uses, words it avoids, and how it writes product names and numbers." },
                { id: "acb-m1-t5-ln9", ts: "2:01", text: "One page of this is enough for a new colleague, an agency or an AI assistant. In the activity that follows you describe a voice in three traits and begin your own chart." },
              ],
            },
            { id: "acb-m1-t6", type: "Activity", title: "Describe a voice in three traits", duration: "approx. 20 min", completed: true },
          ],
        },
        {
          id: "acb-m1-l2",
          label: "A voice system for AI tools",
          topics: [
            { id: "acb-m1-t7", type: "Reading", title: "Voice guidelines an AI assistant can follow", duration: "approx. 15 min read", completed: true },
            {
              id: "acb-m1-t8",
              type: "Video",
              title: "Briefing AI tools with brand context",
              duration: "18 min",
              completed: true,
              transcript: [
                { id: "acb-m1-t8-ln1", ts: "0:00", text: "An AI assistant starts every conversation knowing nothing about your brand. Briefing it is how you bring the voice system into the room." },
                { id: "acb-m1-t8-ln2", ts: "0:13", text: "Think of the briefing as a block of text you prepare once and reuse. It has four parts." },
                { id: "acb-m1-t8-ln3", ts: "0:23", text: "Part one is who the brand is: two or three sentences from the positioning. What you sell, to whom, and what makes you different." },
                { id: "acb-m1-t8-ln4", ts: "0:36", text: "Part two is the voice: the traits with their do and do not lines, straight from the chart. Part three is the vocabulary: words to use, words to avoid, how names and numbers are written." },
                { id: "acb-m1-t8-ln5", ts: "0:53", text: "Part four is examples: two or three short pieces of real, approved copy. Examples do more than any description. The assistant picks up rhythm and word choice from them." },
                { id: "acb-m1-t8-ln6", ts: "1:08", text: "Paste this block at the start of a conversation, or save it in the tool's custom instructions if it has them. Then give the task: the content brief for the piece you need." },
                { id: "acb-m1-t8-ln7", ts: "1:23", text: "Test the briefing before you rely on it. Ask for the same short piece with and without it, and compare. If you cannot tell which is which, the briefing is too vague." },
                { id: "acb-m1-t8-ln8", ts: "1:39", text: "When the output drifts, correct the briefing as well as the draft. Add the word it keeps using to the avoid list, or add an example of what you wanted." },
                { id: "acb-m1-t8-ln9", ts: "1:53", text: "Never put customer data or unpublished plans into the briefing. A voice block needs no secrets to work." },
              ],
            },
            { id: "acb-m1-t9", type: "Practice Assignment", title: "Practice Quiz: Brand voice basics", duration: "approx. 10 min", completed: true },
            { id: "acb-m1-t10", type: "Reading", title: "Responsible use: claims, sources and disclosure", duration: "approx. 12 min read", completed: true },
            { id: "acb-m1-t11", type: "Graded Assignment", title: "Assignment 01 · Brand voice guide", duration: "approx. 45 min", completed: true },
            { id: "acb-m1-t12", type: "Quiz", title: "Graded Quiz: Brand strategy and voice", duration: "approx. 10 min", completed: true },
          ],
        },
      ],
    },
    {
      id: "acb-m2",
      label: "MODULE 02",
      title: "AI-Assisted Content Development",
      topicsCompleted: 3,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "acb-m2-l1",
          label: "Prompting for brand copy",
          topics: [
            {
              id: "acb-m2-t1",
              type: "Video",
              title: "From brand voice to content brief",
              duration: "12 min",
              completed: true,
              transcript: [
                { id: "acb-m2-t1-ln1", ts: "0:00", text: "Welcome to Module 2. In Module 1 you wrote a voice guide. In this module you put it to work with an AI writing assistant." },
                { id: "acb-m2-t1-ln2", ts: "0:16", text: "An assistant knows nothing about your brand unless you tell it. The content brief is how you tell it, every time, in the same order." },
                { id: "acb-m2-t1-ln3", ts: "0:34", text: "A brief has five parts: who the reader is, what you want them to do, the one message, the voice traits, and the format and length." },
                { id: "acb-m2-t1-ln4", ts: "0:55", text: "Notice what is not in the brief: the copy itself. You describe the job, the assistant drafts, and you edit." },
                { id: "acb-m2-t1-ln5", ts: "1:12", text: "Let's fill one in for a product update email. The reader is an existing customer who has not opened the app in a month." },
                { id: "acb-m2-t1-ln6", ts: "1:33", text: "The action is one thing only: open the app and try the new feature. If you ask for three things, the draft will try to sell all three." },
                { id: "acb-m2-t1-ln7", ts: "1:52", text: "Keep the brief as a template. In the next reading you turn each of its parts into a line of a prompt." },
              ],
            },
            { id: "acb-m2-t2", type: "Reading", title: "Anatomy of an effective prompt", duration: "approx. 10 min read", completed: true },
            {
              id: "acb-m2-t3",
              type: "Video",
              title: "Drafting long-form content with an AI assistant",
              duration: "14 min",
              completed: true,
              transcript: [
                { id: "acb-m2-t3-ln1", ts: "0:00", text: "Long-form content, such as an article, a guide or a newsletter, is where an assistant saves the most time and where it can go wrong for the longest." },
                { id: "acb-m2-t3-ln2", ts: "0:15", text: "Do not ask for the whole piece in one go. You will get eight hundred words that are smooth, generic and built on facts you did not supply." },
                { id: "acb-m2-t3-ln3", ts: "0:29", text: "Work in four passes. First, the outline. Give the brief and ask for three possible structures, each as a list of headings with one line on what the section will say." },
                { id: "acb-m2-t3-ln4", ts: "0:46", text: "Choose one and correct it. This is where you decide the argument. Changing an outline costs seconds. Changing a finished draft costs an afternoon." },
                { id: "acb-m2-t3-ln5", ts: "1:00", text: "Second, the material. For each section, give the assistant the facts, figures, quotes and examples it should use. What you do not supply, it will invent or leave vague." },
                { id: "acb-m2-t3-ln6", ts: "1:16", text: "Third, the draft, one section at a time. Read each before you ask for the next. Errors caught early do not spread through the rest of the piece." },
                { id: "acb-m2-t3-ln7", ts: "1:31", text: "Fourth, the edit, which is yours. Check every fact against its source, cut the padding and rewrite the opening. Assistants tend to begin with a sentence that could start any article." },
                { id: "acb-m2-t3-ln8", ts: "1:48", text: "Ask the assistant to help with the edit too: “list every factual claim in this draft” gives you a checklist to verify." },
                { id: "acb-m2-t3-ln9", ts: "2:00", text: "The next reading applies the same discipline to the shortest format of all: the ad." },
              ],
            },
            { id: "acb-m2-t4", type: "Reading", title: "Creating impactful ad copy with effective prompts", duration: "approx. 15 min read", completed: false, active: true },
            { id: "acb-m2-t5", type: "Practice Assignment", title: "Practice Quiz: Prompting for copy", duration: "approx. 10 min", completed: false },
          ],
        },
        {
          id: "acb-m2-l2",
          label: "Audiences, editing and planning",
          topics: [
            {
              id: "acb-m2-t6",
              type: "Video",
              title: "Segmenting an audience for tailored messaging",
              duration: "16 min",
              completed: false,
              transcript: [
                { id: "acb-m2-t6-ln1", ts: "0:00", text: "A message written for everyone is noticed by no one. Segmenting means dividing your audience into groups that need to hear something different." },
                { id: "acb-m2-t6-ln2", ts: "0:14", text: "The easiest way to segment is by demographics: age, location, income. It is also the least useful for writing. Two people of the same age can want opposite things." },
                { id: "acb-m2-t6-ln3", ts: "0:29", text: "Segment by need or situation instead. Ask what the person is trying to do and what stands in their way." },
                { id: "acb-m2-t6-ln4", ts: "0:40", text: "For Brightwell Refill, three segments appear. The first wants to cut waste and will accept some effort. The second wants convenience and does not care much about plastic. The third is watching the household budget." },
                { id: "acb-m2-t6-ln5", ts: "1:00", text: "It is the same product with three different reasons to buy. So each segment gets its own message: fewer bottles thrown away, never running out, a lower cost per wash." },
                { id: "acb-m2-t6-ln6", ts: "1:15", text: "For each segment write a short profile: who they are, what they need, what holds them back, the one message, and the proof that supports it." },
                { id: "acb-m2-t6-ln7", ts: "1:29", text: "That profile goes into the content brief, and the brief goes into the prompt. The assistant can then adapt one announcement for all three in minutes." },
                { id: "acb-m2-t6-ln8", ts: "1:43", text: "Check two things in the output. The facts must be identical across versions, with only the emphasis changing. And the voice must stay the same. You are changing what you say first, not who you are." },
                { id: "acb-m2-t6-ln9", ts: "1:58", text: "In the activity that follows you rewrite one message for three segments." },
              ],
            },
            { id: "acb-m2-t7", type: "Activity", title: "Rewrite one message for three segments", duration: "approx. 30 min", completed: false },
            { id: "acb-m2-t8", type: "Reading", title: "Editing AI drafts: accuracy, tone and disclosure", duration: "approx. 25 min read", completed: false },
            {
              id: "acb-m2-t9",
              type: "Video",
              title: "Planning a week of content with an AI assistant",
              duration: "25 min",
              completed: false,
              transcript: [
                { id: "acb-m2-t9-ln1", ts: "0:00", text: "Producing content one piece at a time, on the day it is due, is how brands end up posting whatever is quickest. A weekly plan fixes that, and an assistant makes the plan fast to build." },
                { id: "acb-m2-t9-ln2", ts: "0:17", text: "Start with content pillars: three or four themes the brand always talks about. For Brightwell Refill they are how refilling works, the numbers on waste saved, and customers' routines." },
                { id: "acb-m2-t9-ln3", ts: "0:34", text: "Next, list the week's fixed points: a product update, a delivery cut-off, a seasonal date. Those go into the calendar first." },
                { id: "acb-m2-t9-ln4", ts: "0:46", text: "Now give the assistant the pillars, the fixed points, your channels and how often you post on each. Ask for a week's plan as a table: day, channel, pillar, topic, format and call to action." },
                { id: "acb-m2-t9-ln5", ts: "1:04", text: "Check the balance. A week of five promotional posts is an advertising schedule. A common guide is that most posts should inform or help, and a minority should sell." },
                { id: "acb-m2-t9-ln6", ts: "1:20", text: "Then plan for reuse. One customer story can be an email on Tuesday, a short post on Wednesday and three quotes for the week after. Ask the assistant to propose the versions." },
                { id: "acb-m2-t9-ln7", ts: "1:36", text: "Draft in one sitting, with the voice block and one brief per piece. Writing five pieces in a single session keeps the voice more consistent than writing them on five different days." },
                { id: "acb-m2-t9-ln8", ts: "1:52", text: "Edit everything, schedule it, and leave one slot open for something that happens during the week." },
                { id: "acb-m2-t9-ln9", ts: "2:02", text: "At the end of the week, note which pieces people responded to. That note becomes part of next week's prompt." },
              ],
            },
            { id: "acb-m2-t10", type: "Graded Assignment", title: "Assignment 02 · Audience segmentation", duration: "approx. 45 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "acb-m3",
      label: "MODULE 03",
      title: "AI for Visual Content",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "acb-m3-l1",
          label: "Generating images on brand",
          topics: [
            { id: "acb-m3-t1", type: "Video", title: "What image models can and cannot do", duration: "15 min", completed: false },
            { id: "acb-m3-t2", type: "Reading", title: "Writing prompts for images: subject, style, composition", duration: "approx. 18 min read", completed: false },
            { id: "acb-m3-t3", type: "Video", title: "Keeping visuals on brand: palettes, references and style guides", duration: "18 min", completed: false },
            { id: "acb-m3-t4", type: "Activity", title: "Check four generated images against a brand guide", duration: "approx. 25 min", completed: false },
            { id: "acb-m3-t5", type: "Reading", title: "Rights, likeness and disclosure in generated imagery", duration: "approx. 15 min read", completed: false },
          ],
        },
        {
          id: "acb-m3-l2",
          label: "Motion, accessibility and campaigns",
          topics: [
            { id: "acb-m3-t6", type: "Video", title: "From static to motion: short video and animation tools", duration: "20 min", completed: false },
            { id: "acb-m3-t7", type: "Reading", title: "Alt text and accessible visual content", duration: "approx. 12 min read", completed: false },
            { id: "acb-m3-t8", type: "Practice Assignment", title: "Practice Quiz: Visual prompts", duration: "approx. 10 min", completed: false },
            { id: "acb-m3-t9", type: "Video", title: "Building a campaign visual set end to end", duration: "36 min", completed: false },
            { id: "acb-m3-t10", type: "Quiz", title: "Graded Quiz: AI for visual content", duration: "approx. 15 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "acb-m4",
      label: "MODULE 04",
      title: "Final Project, Assessment, and Wrap-Up",
      topicsCompleted: 0,
      topicsTotal: 6,
      isCompleted: false,
      lessons: [
        {
          id: "acb-m4-l1",
          label: "Final project",
          topics: [
            { id: "acb-m4-t1", type: "Reading", title: "Final project brief: a brand content kit", duration: "approx. 15 min read", completed: false, locked: true },
            { id: "acb-m4-t2", type: "Video", title: "Planning your content kit", duration: "14 min", completed: false, locked: true },
            { id: "acb-m4-t3", type: "Project", title: "Final Project: Brand content kit", duration: "approx. 2 h", completed: false, locked: true },
            { id: "acb-m4-t4", type: "Peer Review", title: "Review two content kits", duration: "approx. 20 min", completed: false, locked: true },
          ],
        },
        {
          id: "acb-m4-l2",
          label: "Assessment and wrap-up",
          topics: [
            { id: "acb-m4-t5", type: "Quiz", title: "Final Assessment", duration: "approx. 20 min", completed: false, locked: true },
            { id: "acb-m4-t6", type: "Video", title: "Course wrap-up and next steps", duration: "5 min", completed: false, locked: true },
          ],
        },
      ],
    },
  ],
};
