import type { Course } from "@/lib/courses/kit";

/**
 * "Leadership in Remote Teams": a stand-alone course on My Learning and on the Dashboard's
 * resume list, in progress. 25 topics, 13 done: Modules 1 and 2 complete; the learner is on
 * the first topic of Module 3.
 */
export const outline: Course = {
  id: "lrt",
  slug: "leadership-in-remote-teams",
  title: "Leadership in Remote Teams",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Intermediate",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 52,
  modulesCompleted: 2,
  modulesTotal: 4,
  modules: [
    {
      id: "lrt-m1",
      label: "MODULE 01",
      title: "Trust and Expectations at a Distance",
      topicsCompleted: 6,
      topicsTotal: 6,
      isCompleted: true,
      lessons: [
        {
          id: "lrt-m1-l1",
          label: "What changes when the team is remote",
          topics: [
            {
              id: "lrt-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "4 min",
              completed: true,
              transcript: [
                { id: "lrt-m1-t1-ln1", ts: "0:00", text: "Welcome to Leadership in Remote Teams. This course is for people who lead a team they rarely or never see in person." },
                { id: "lrt-m1-t1-ln2", ts: "0:13", text: "Leading at a distance uses the same skills as leading in an office. The difference is that less happens by accident, so more has to be done on purpose." },
                { id: "lrt-m1-t1-ln3", ts: "0:28", text: "Module 1 is about trust and expectations: what changes when the corridor disappears, and how a team agrees on the way it works." },
                { id: "lrt-m1-t1-ln4", ts: "0:43", text: "Module 2 covers communication norms: which channel for which message, time zones, and writing things down so that the team has a memory." },
                { id: "lrt-m1-t1-ln5", ts: "0:59", text: "Module 3 looks at meetings and rituals, from async standups to one-to-ones. Module 4 covers goals, feedback and noticing when someone is struggling." },
                { id: "lrt-m1-t1-ln6", ts: "1:16", text: "You will write a communication charter for a team, and for the final project a plan for your first thirty days leading a remote team. Two peers review it." },
                { id: "lrt-m1-t1-ln7", ts: "1:32", text: "A case study runs through the course: a team of nine people in three time zones. Use it, or use your own team where that helps you more." },
              ],
            },
            { id: "lrt-m1-t2", type: "Reading", title: "What a remote team loses, and what it gains", duration: "approx. 10 min read", completed: true },
            {
              id: "lrt-m1-t3",
              type: "Video",
              title: "Trust without the corridor: reliability, openness and care",
              duration: "12 min",
              completed: true,
              transcript: [
                { id: "lrt-m1-t3-ln1", ts: "0:00", text: "In an office, trust builds as a side effect. You see a colleague stay late to help someone, or you talk while the coffee brews. A remote team gets none of that for free." },
                { id: "lrt-m1-t3-ln2", ts: "0:18", text: "It helps to split trust into three parts that you can work on: reliability, openness and care." },
                { id: "lrt-m1-t3-ln3", ts: "0:30", text: "Reliability means doing what you said you would, when you said. At a distance people cannot see your effort. They see only whether the thing arrived." },
                { id: "lrt-m1-t3-ln4", ts: "0:45", text: "So make small promises and keep them. Say “I will reply by Thursday noon”, and do. If you cannot, say so before Thursday noon, not after." },
                { id: "lrt-m1-t3-ln5", ts: "1:00", text: "Openness means sharing what you know and what you do not: the reasons for a decision, a mistake you made, a question you cannot answer yet." },
                { id: "lrt-m1-t3-ln6", ts: "1:15", text: "When a lead says “I got that wrong, here is what I am changing”, it becomes safe for others to say the same. Problems then surface while they are still small." },
                { id: "lrt-m1-t3-ln7", ts: "1:31", text: "Care means showing that you see the person as well as the output. Remember that their child was ill. Notice a message sent at midnight, and ask about it." },
                { id: "lrt-m1-t3-ln8", ts: "1:46", text: "None of the three needs a team-building event. Each is built in ordinary work, repeated. The next lesson turns them into an agreement the whole team writes." },
              ],
            },
          ],
        },
        {
          id: "lrt-m1-l2",
          label: "Agreeing how you work",
          topics: [
            { id: "lrt-m1-t4", type: "Reading", title: "Writing a team working agreement", duration: "approx. 12 min read", completed: true },
            { id: "lrt-m1-t5", type: "Activity", title: "Draft the working agreement for a team of six", duration: "approx. 20 min", completed: true },
            { id: "lrt-m1-t6", type: "Quiz", title: "Graded Quiz: Trust and expectations", duration: "approx. 10 min", completed: true },
          ],
        },
      ],
    },
    {
      id: "lrt-m2",
      label: "MODULE 02",
      title: "Communication Norms",
      topicsCompleted: 7,
      topicsTotal: 7,
      isCompleted: true,
      lessons: [
        {
          id: "lrt-m2-l1",
          label: "Choosing the channel",
          topics: [
            {
              id: "lrt-m2-t1",
              type: "Video",
              title: "Sync or async: choosing the channel for the message",
              duration: "12 min",
              completed: true,
              transcript: [
                { id: "lrt-m2-t1-ln1", ts: "0:00", text: "Every message has a best channel. Choosing it well is the cheapest improvement a remote team can make." },
                { id: "lrt-m2-t1-ln2", ts: "0:12", text: "Synchronous means together at the same time: a call or a live chat. Asynchronous means each person reads and answers when they can: a document, a thread, an email." },
                { id: "lrt-m2-t1-ln3", ts: "0:29", text: "Use two questions to choose. How complex or sensitive is this? And how soon does it need an answer?" },
                { id: "lrt-m2-t1-ln4", ts: "0:42", text: "Simple and not urgent: write it. A status update, a file for review or a question with a clear answer never needs a call." },
                { id: "lrt-m2-t1-ln5", ts: "0:55", text: "Complex or emotional: talk. Disagreement, feedback on someone's work, bad news, or a problem nobody has understood yet go better with voice and faces." },
                { id: "lrt-m2-t1-ln6", ts: "1:11", text: "Urgent and simple: use the channel your team has named for urgent things, and keep it rare. If everything is urgent, the word stops meaning anything." },
                { id: "lrt-m2-t1-ln7", ts: "1:25", text: "Here is a useful signal. When a written thread passes five or six replies without converging, stop and call. Then write the outcome back into the thread." },
                { id: "lrt-m2-t1-ln8", ts: "1:40", text: "Async is the default for a team across time zones, because it lets people think and does not cost anyone their evening. Sync is the exception you choose deliberately." },
              ],
            },
            { id: "lrt-m2-t2", type: "Reading", title: "Writing messages that do not need a meeting", duration: "approx. 12 min read", completed: true },
            {
              id: "lrt-m2-t3",
              type: "Video",
              title: "Time zones, overlap hours and response times",
              duration: "10 min",
              completed: true,
              transcript: [
                { id: "lrt-m2-t3-ln1", ts: "0:00", text: "When a team spans time zones, the clock becomes a shared resource. Someone has to manage it, or it will be shared unfairly." },
                { id: "lrt-m2-t3-ln2", ts: "0:14", text: "Start with a simple chart: each person's working hours on one common timeline. The hours where everyone is at work are your overlap." },
                { id: "lrt-m2-t3-ln3", ts: "0:28", text: "The case-study team is spread over three zones and has two hours of overlap a day. Those two hours are precious. Do not fill them with status updates." },
                { id: "lrt-m2-t3-ln4", ts: "0:43", text: "Protect the overlap for work that needs everyone live: decisions, planning, difficult conversations. Everything else moves to writing." },
                { id: "lrt-m2-t3-ln5", ts: "0:56", text: "Next, agree response times per channel and write them down. For example: chat within four working hours, email within one working day, the urgent channel within thirty minutes." },
                { id: "lrt-m2-t3-ln6", ts: "1:14", text: "“Working” hours means the recipient's. A message sent at your nine in the morning may arrive at their nine at night. It should wait until their morning, and they should know that it can." },
                { id: "lrt-m2-t3-ln7", ts: "1:30", text: "Design the handover. The person ending their day leaves a short note: what is done, what is open, what the next person needs. Work then moves forward while half the team sleeps." },
                { id: "lrt-m2-t3-ln8", ts: "1:47", text: "And when a call must fall outside someone's hours, rotate the cost. The same person should not take the late slot every week." },
              ],
            },
            { id: "lrt-m2-t4", type: "Practice Assignment", title: "Practice Quiz: Channels and response times", duration: "approx. 8 min", completed: true },
          ],
        },
        {
          id: "lrt-m2-l2",
          label: "Making work visible",
          topics: [
            { id: "lrt-m2-t5", type: "Reading", title: "Documentation as the team's memory", duration: "approx. 10 min read", completed: true },
            {
              id: "lrt-m2-t6",
              type: "Video",
              title: "Decisions in writing: the decision log",
              duration: "11 min",
              completed: true,
              transcript: [
                { id: "lrt-m2-t6-ln1", ts: "0:00", text: "In a remote team, a decision that is not written down has been made only for the people who were on the call." },
                { id: "lrt-m2-t6-ln2", ts: "0:13", text: "A decision log is a simple shared list. Each entry answers five questions, and it takes two minutes to write." },
                { id: "lrt-m2-t6-ln3", ts: "0:25", text: "What was decided, in one sentence. Why, including the options that were rejected. Who decided. When. And what would make the team look at it again." },
                { id: "lrt-m2-t6-ln4", ts: "0:42", text: "The “why” is the part people skip, and it is the most valuable. Six months later, someone will propose the option you rejected. The log saves the whole argument from being repeated." },
                { id: "lrt-m2-t6-ln5", ts: "0:59", text: "Write the entry the same day, and post a link in the team channel so that people in other time zones see it when they start work." },
                { id: "lrt-m2-t6-ln6", ts: "1:13", text: "Give everyone a short window to object, say two working days, before the decision is final. This is how people who could not join the call still have a voice." },
                { id: "lrt-m2-t6-ln7", ts: "1:28", text: "Not everything is a decision for the log. Use it for choices that affect more than one person, or that would be costly to reverse." },
                { id: "lrt-m2-t6-ln8", ts: "1:41", text: "Keep it in one place and in date order. A decision log that lives in five documents is as lost as one that lives in nobody's memory." },
              ],
            },
            { id: "lrt-m2-t7", type: "Graded Assignment", title: "Assignment 01 · Team communication charter", duration: "approx. 40 min", completed: true },
          ],
        },
      ],
    },
    {
      id: "lrt-m3",
      label: "MODULE 03",
      title: "Meetings, Rituals and Async Work",
      topicsCompleted: 0,
      topicsTotal: 6,
      isCompleted: false,
      lessons: [
        {
          id: "lrt-m3-l1",
          label: "Rituals across time zones",
          topics: [
            {
              id: "lrt-m3-t1",
              type: "Video",
              title: "Async standups",
              duration: "10 min",
              completed: false,
              active: true,
              transcript: [
                { id: "lrt-m3-t1-ln1", ts: "0:00", text: "A standup exists so that people can coordinate. It was never meant to be a report to the manager, and moving it online does not change that." },
                { id: "lrt-m3-t1-ln2", ts: "0:14", text: "In a team spread over time zones, the daily call costs someone their early morning or their evening. An async standup keeps the purpose and drops the call." },
                { id: "lrt-m3-t1-ln3", ts: "0:31", text: "Each person posts once a day, in one thread, before a set hour in their own time zone. Three lines: what I finished, what I am doing next, what is in my way." },
                { id: "lrt-m3-t1-ln4", ts: "0:50", text: "The third line is the one that matters. Ask for it by name, and ask who can help. A blocker with no person attached stays a blocker." },
                { id: "lrt-m3-t1-ln5", ts: "1:08", text: "Your job as the lead is to read every post and to answer blockers within the working day. If nobody replies, people stop writing anything real." },
                { id: "lrt-m3-t1-ln6", ts: "1:25", text: "Watch for two signs that it is not working: posts that only list tasks, and blockers that appear for the first time in a one-to-one. Both mean the thread does not feel safe or useful." },
                { id: "lrt-m3-t1-ln7", ts: "1:44", text: "Keep one live call a week for what text does badly: disagreement, planning and seeing each other. The next reading helps you decide which other meetings to keep." },
              ],
            },
            { id: "lrt-m3-t2", type: "Reading", title: "Which meetings to keep, shorten or replace", duration: "approx. 12 min read", completed: false },
            { id: "lrt-m3-t3", type: "Activity", title: "Redesign a weekly calendar for a team in three time zones", duration: "approx. 20 min", completed: false },
          ],
        },
        {
          id: "lrt-m3-l2",
          label: "One-to-ones and belonging",
          topics: [
            {
              id: "lrt-m3-t4",
              type: "Video",
              title: "One-to-ones that are not status updates",
              duration: "12 min",
              completed: false,
              transcript: [
                { id: "lrt-m3-t4-ln1", ts: "0:00", text: "A one-to-one is the only meeting that belongs to the team member. When it turns into a status report, they lose the one place where they could raise what matters to them." },
                { id: "lrt-m3-t4-ln2", ts: "0:17", text: "Status belongs in the async standup and on the board. Read those before the call. Then you will not need to ask “so, what are you working on?”" },
                { id: "lrt-m3-t4-ln3", ts: "0:31", text: "Open with a question that hands the agenda over: “What is on your mind this week?” Then wait. The first answer is often small, and the real one follows it." },
                { id: "lrt-m3-t4-ln4", ts: "0:47", text: "Keep a shared document for each person where both of you add topics during the week. People who think before they speak get the same chance as people who think aloud." },
                { id: "lrt-m3-t4-ln5", ts: "1:02", text: "Over a month, cover four things: how the work is going, what is in their way, how they are developing, and how they are doing as a person." },
                { id: "lrt-m3-t4-ln6", ts: "1:17", text: "Ask for feedback on yourself, and ask specifically: “What is one thing I could do differently that would make your work easier?” A general invitation gets a polite “nothing”." },
                { id: "lrt-m3-t4-ln7", ts: "1:34", text: "Hold it weekly or every two weeks, thirty minutes, with the camera on if they are comfortable. Do not cancel it. Move it if you must." },
                { id: "lrt-m3-t4-ln8", ts: "1:48", text: "A cancelled one-to-one tells a remote team member that everything else came first. For some of them it is the only conversation they have with you all week." },
              ],
            },
            { id: "lrt-m3-t5", type: "Reading", title: "Belonging and informal contact at a distance", duration: "approx. 10 min read", completed: false },
            { id: "lrt-m3-t6", type: "Quiz", title: "Graded Quiz: Meetings and rituals", duration: "approx. 10 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "lrt-m4",
      label: "MODULE 04",
      title: "Performance, Feedback and Wellbeing",
      topicsCompleted: 0,
      topicsTotal: 6,
      isCompleted: false,
      lessons: [
        {
          id: "lrt-m4-l1",
          label: "Managing by outcomes",
          topics: [
            { id: "lrt-m4-t1", type: "Video", title: "Outcomes over hours: setting goals you can see", duration: "12 min", completed: false, locked: true },
            { id: "lrt-m4-t2", type: "Reading", title: "Giving feedback in writing and on a call", duration: "approx. 12 min read", completed: false, locked: true },
            { id: "lrt-m4-t3", type: "Video", title: "Spotting overload and isolation early", duration: "11 min", completed: false, locked: true },
          ],
        },
        {
          id: "lrt-m4-l2",
          label: "Final project",
          topics: [
            { id: "lrt-m4-t4", type: "Project", title: "Final Project: 30-day plan for a remote team", duration: "approx. 1 h", completed: false, locked: true },
            { id: "lrt-m4-t5", type: "Peer Review", title: "Review two 30-day plans", duration: "approx. 15 min", completed: false, locked: true },
            { id: "lrt-m4-t6", type: "Video", title: "Course wrap-up and next steps", duration: "5 min", completed: false, locked: true },
          ],
        },
      ],
    },
  ],
};
