import type { Course } from "@/lib/courses/kit";

/**
 * "Digital Marketing Fundamentals and the AI Mindset": course 1 of the AI Augmented Digital
 * Marketing program. 36 topics, all done: the learner finished it and holds its certificate.
 * No topic is flagged `active`: Review opens the course on its first topic.
 */
export const outline: Course = {
  id: "dmf",
  slug: "digital-marketing-fundamentals-and-the-ai-mindset",
  title: "Digital Marketing Fundamentals and the AI Mindset",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Beginner",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 100,
  modulesCompleted: 4,
  modulesTotal: 4,
  modules: [
    {
      id: "dmf-m1",
      label: "MODULE 01",
      title: "The Digital Marketing Landscape",
      topicsCompleted: 10,
      topicsTotal: 10,
      isCompleted: true,
      lessons: [
        {
          id: "dmf-m1-l1",
          label: "How digital marketing works",
          topics: [
            {
              id: "dmf-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "6 min",
              completed: true,
              transcript: [
                { id: "dmf-m1-t1-ln1", ts: "0:00", text: "Welcome to the first course of the program. Over four modules you will learn how digital marketing works and where AI fits into it." },
                { id: "dmf-m1-t1-ln2", ts: "0:17", text: "We start with the landscape: the channels a brand can use, and the journey a customer takes from first hearing of you to recommending you." },
                { id: "dmf-m1-t1-ln3", ts: "0:36", text: "Module 2 is about numbers. You will turn a business goal into objectives, read a funnel and work out what a customer costs to win." },
                { id: "dmf-m1-t1-ln4", ts: "0:55", text: "Module 3 introduces the AI mindset. An AI assistant drafts, sorts and summarises quickly. It does not know your customer, and it does not check its own facts." },
                { id: "dmf-m1-t1-ln5", ts: "1:16", text: "So the rule for this whole program is simple: you set the task, the assistant does a first pass, and you review before anything is published." },
                { id: "dmf-m1-t1-ln6", ts: "1:34", text: "Each module has short videos, readings, one activity and a practice quiz. Two assignments, two graded quizzes, a final project and a final assessment make up your grade." },
                { id: "dmf-m1-t1-ln7", ts: "1:55", text: "You need 70% to pass. The first reading is next: what digital marketing is, and what it is not." },
              ],
            },
            { id: "dmf-m1-t2", type: "Reading", title: "What digital marketing is, and what it is not", duration: "approx. 12 min read", completed: true },
            {
              id: "dmf-m1-t3",
              type: "Video",
              title: "Owned, earned and paid media",
              duration: "14 min",
              completed: true,
              transcript: [
                { id: "dmf-m1-t3-ln1", ts: "0:00", text: "Every channel a brand uses falls into one of three groups: owned, earned or paid. This video shows how to tell them apart and why a plan needs all three." },
                { id: "dmf-m1-t3-ln2", ts: "0:20", text: "Owned media is what you control: the website, the app, the email list, the profile pages you run. You decide what appears there, and it stays for as long as you keep it." },
                { id: "dmf-m1-t3-ln3", ts: "0:42", text: "Paid media is a placement you buy: a search ad, a sponsored post, a banner. It starts the day you pay and stops the day the budget ends." },
                { id: "dmf-m1-t3-ln4", ts: "1:01", text: "Earned media is attention other people give you: a review, a share, a mention in an article. You cannot buy it or edit it, which is exactly why readers trust it." },
                { id: "dmf-m1-t3-ln5", ts: "1:22", text: "Test any channel with two questions. Who decides what is said? Was the space paid for? You decide and nothing is paid: owned. You decide and you pay: paid. Someone else decides, freely: earned." },
                { id: "dmf-m1-t3-ln6", ts: "1:45", text: "Take a neighbourhood bike shop. Its repair guide sits on its own site. A search ad brings in people looking for a repair near them. A happy customer posts a photo of the fixed bike." },
                { id: "dmf-m1-t3-ln7", ts: "2:08", text: "The three feed each other. The ad sends visitors to the guide, the guide earns their trust, and the good repair earns the review that persuades the next visitor." },
                { id: "dmf-m1-t3-ln8", ts: "2:27", text: "Owned media is slow to build and cheap to keep. Paid is fast and stops when you stop. Earned is the most trusted and the least predictable. Next, the channels one by one." },
              ],
            },
            { id: "dmf-m1-t4", type: "Reading", title: "The channels at a glance: search, social, email and display", duration: "approx. 15 min read", completed: true },
            { id: "dmf-m1-t5", type: "Activity", title: "Map the channels a brand already uses", duration: "approx. 25 min", completed: true },
          ],
        },
        {
          id: "dmf-m1-l2",
          label: "Customers and journeys",
          topics: [
            {
              id: "dmf-m1-t6",
              type: "Video",
              title: "The customer journey: from awareness to advocacy",
              duration: "16 min",
              completed: true,
              transcript: [
                { id: "dmf-m1-t6-ln1", ts: "0:00", text: "Nobody buys the first time they hear of a brand. In this video we follow one customer through five stages: awareness, consideration, purchase, retention and advocacy." },
                { id: "dmf-m1-t6-ln2", ts: "0:17", text: "Meet Dana. Her back hurts after long days at a desk. At the awareness stage she knows no brand of office chair. She knows she has a problem, and a short video about desk posture catches her eye." },
                { id: "dmf-m1-t6-ln3", ts: "0:42", text: "In consideration she compares. She searches for chairs with lumbar support, reads reviews and opens three price pages. Content that helps her choose matters more here than content that praises the product." },
                { id: "dmf-m1-t6-ln4", ts: "1:03", text: "Purchase is the moment of decision, and small things decide it: a clear delivery date, a return policy she can find, a checkout that does not demand an account." },
                { id: "dmf-m1-t6-ln5", ts: "1:22", text: "Most journey maps stop there. The business should not. Retention is what happens next: the chair arrives, an email explains how to adjust it, and three months later she is offered a footrest." },
                { id: "dmf-m1-t6-ln6", ts: "1:44", text: "Advocacy is the last stage. Dana tells a colleague, or writes a review. That review becomes someone else's consideration stage, so the journey is a loop more than a line." },
                { id: "dmf-m1-t6-ln7", ts: "2:04", text: "At each stage the customer has a different question. What is this? Is it right for me? Can I trust the order? Did I choose well? Would I recommend it?" },
                { id: "dmf-m1-t6-ln8", ts: "2:24", text: "Your job is to answer the question of the stage she is in, on the channel she is using. In the assignment you will map this for a business you choose." },
              ],
            },
            { id: "dmf-m1-t7", type: "Reading", title: "Personas and the job a customer wants done", duration: "approx. 15 min read", completed: true },
            { id: "dmf-m1-t8", type: "Practice Assignment", title: "Practice Quiz: Channels and journeys", duration: "approx. 10 min", completed: true },
            { id: "dmf-m1-t9", type: "Graded Assignment", title: "Assignment 01 · Customer journey map", duration: "approx. 45 min", completed: true },
            { id: "dmf-m1-t10", type: "Quiz", title: "Graded Quiz: The digital marketing landscape", duration: "approx. 15 min", completed: true },
          ],
        },
      ],
    },
    {
      id: "dmf-m2",
      label: "MODULE 02",
      title: "Goals, Funnels and Measurement",
      topicsCompleted: 10,
      topicsTotal: 10,
      isCompleted: true,
      lessons: [
        {
          id: "dmf-m2-l1",
          label: "Setting goals",
          topics: [
            {
              id: "dmf-m2-t1",
              type: "Video",
              title: "From business goals to marketing objectives",
              duration: "14 min",
              completed: true,
              transcript: [
                { id: "dmf-m2-t1-ln1", ts: "0:00", text: "A business goal is what the owner wants. A marketing objective is what marketing will do about it. This video shows how to get from one to the other." },
                { id: "dmf-m2-t1-ln2", ts: "0:19", text: "Start with a goal as an owner would say it: we want the online shop to bring in twenty percent more revenue this year. That is clear, and it tells marketing nothing about what to do on Monday." },
                { id: "dmf-m2-t1-ln3", ts: "0:44", text: "Ask where the revenue can come from. There are only three places: more customers, more orders from each customer, or more money per order. Pick the one with the most room." },
                { id: "dmf-m2-t1-ln4", ts: "1:05", text: "Say this shop has plenty of first-time buyers and few who return. Then the lever is repeat orders, and the objective follows: raise the share of customers who order a second time." },
                { id: "dmf-m2-t1-ln5", ts: "1:26", text: "Now make it specific. From eighteen percent to twenty-five percent, among customers who first bought this quarter, by the end of September. A number, a group of people and a date." },
                { id: "dmf-m2-t1-ln6", ts: "1:47", text: "Check it against the goal. If the objective is met, does revenue rise? If a quarter of new customers come back where fewer than a fifth did, yes. If the answer were no, the objective would be a distraction." },
                { id: "dmf-m2-t1-ln7", ts: "2:13", text: "Two or three objectives are enough. Each one will need a metric, a data source and an owner, which is the subject of the next reading." },
              ],
            },
            { id: "dmf-m2-t2", type: "Reading", title: "Specific objectives and the metrics that follow", duration: "approx. 15 min read", completed: true },
            {
              id: "dmf-m2-t3",
              type: "Video",
              title: "The funnel and its conversion rates",
              duration: "18 min",
              completed: true,
              transcript: [
                { id: "dmf-m2-t3-ln1", ts: "0:00", text: "A funnel is a count of how many people reach each step on the way to becoming a customer. It is called a funnel because every step holds fewer people than the one before." },
                { id: "dmf-m2-t3-ln2", ts: "0:23", text: "Here is a simple one for an online shop in one month. Ten thousand visits. Two thousand product page views. Four hundred carts. Two hundred orders." },
                { id: "dmf-m2-t3-ln3", ts: "0:40", text: "A conversion rate is the people who took a step, divided by the people who could have. Visits to product views: two thousand over ten thousand, twenty percent." },
                { id: "dmf-m2-t3-ln4", ts: "0:59", text: "Product views to carts: four hundred over two thousand, twenty percent again. Carts to orders: two hundred over four hundred, fifty percent." },
                { id: "dmf-m2-t3-ln5", ts: "1:14", text: "The overall rate is orders over visits: two hundred over ten thousand, two percent. You get the same figure by multiplying the steps: point two times point two times point five." },
                { id: "dmf-m2-t3-ln6", ts: "1:35", text: "The step rates tell you where to work. Half of all carts are abandoned here. Moving that step from fifty to sixty percent gives forty more orders without one extra visit." },
                { id: "dmf-m2-t3-ln7", ts: "1:56", text: "Always say which two numbers a rate compares. A two percent conversion rate means little until you know it is orders per visit and not orders per cart." },
                { id: "dmf-m2-t3-ln8", ts: "2:15", text: "In the activity that follows you will work out the rates of a funnel yourself and choose the step to fix first." },
              ],
            },
            { id: "dmf-m2-t4", type: "Activity", title: "Calculate the conversion rates of a funnel", duration: "approx. 30 min", completed: true },
            { id: "dmf-m2-t5", type: "Reading", title: "Cost per acquisition, lifetime value and return on ad spend", duration: "approx. 18 min read", completed: true },
          ],
        },
        {
          id: "dmf-m2-l2",
          label: "Reading the numbers",
          topics: [
            { id: "dmf-m2-t6", type: "Video", title: "A first look at a web analytics report", duration: "20 min", completed: true },
            { id: "dmf-m2-t7", type: "Reading", title: "Attribution: which channel gets the credit for a sale", duration: "approx. 15 min read", completed: true },
            { id: "dmf-m2-t8", type: "Practice Assignment", title: "Practice Quiz: Metrics and funnels", duration: "approx. 10 min", completed: true },
            { id: "dmf-m2-t9", type: "Video", title: "Privacy, consent and first-party data", duration: "16 min", completed: true },
            { id: "dmf-m2-t10", type: "Graded Assignment", title: "Assignment 02 · Measurement plan", duration: "approx. 45 min", completed: true },
          ],
        },
      ],
    },
    {
      id: "dmf-m3",
      label: "MODULE 03",
      title: "The AI Mindset for Marketers",
      topicsCompleted: 10,
      topicsTotal: 10,
      isCompleted: true,
      lessons: [
        {
          id: "dmf-m3-l1",
          label: "What AI can do for a marketer",
          topics: [
            { id: "dmf-m3-t1", type: "Video", title: "What generative AI is, in plain terms", duration: "15 min", completed: true },
            { id: "dmf-m3-t2", type: "Reading", title: "Where AI helps in marketing, and where it does not", duration: "approx. 15 min read", completed: true },
            {
              id: "dmf-m3-t3",
              type: "Video",
              title: "Your first prompts: role, task, context and format",
              duration: "18 min",
              completed: true,
              transcript: [
                { id: "dmf-m3-t3-ln1", ts: "0:00", text: "In this video you write your first prompts for a marketing task. We use four parts: role, task, context and format." },
                { id: "dmf-m3-t3-ln2", ts: "0:15", text: "Start with a weak prompt: write a post about our new running shoe. The assistant has to guess the reader, the length and the point." },
                { id: "dmf-m3-t3-ln3", ts: "0:33", text: "Role first. Tell the assistant who it is working as: a copywriter for a small sports shop. That sets the vocabulary and the level of detail." },
                { id: "dmf-m3-t3-ln4", ts: "0:51", text: "Then the task, as one verb and one output: write three versions of a social post that announce the shoe." },
                { id: "dmf-m3-t3-ln5", ts: "1:08", text: "Context is what only you know: the reader runs twice a week, the shoe is lighter than last year's model, and stock arrives on Friday." },
                { id: "dmf-m3-t3-ln6", ts: "1:27", text: "Format closes the prompt: up to forty words each, no hashtags, one clear call to action. Limits given as numbers are followed far more often." },
                { id: "dmf-m3-t3-ln7", ts: "1:46", text: "Compare the two results side by side. The second set is usable, and it still needs you: check the facts, then pick one." },
              ],
            },
            { id: "dmf-m3-t4", type: "Activity", title: "Rewrite three weak prompts", duration: "approx. 25 min", completed: true },
            { id: "dmf-m3-t5", type: "Reading", title: "The marketer as supervisor: review before you publish", duration: "approx. 12 min read", completed: true },
          ],
        },
        {
          id: "dmf-m3-l2",
          label: "Using AI responsibly",
          topics: [
            {
              id: "dmf-m3-t6",
              type: "Video",
              title: "Bias, accuracy and made-up facts",
              duration: "16 min",
              completed: true,
              transcript: [
                { id: "dmf-m3-t6-ln1", ts: "0:00", text: "An AI assistant can be wrong in three ways that matter to a marketer: it can invent facts, it can be out of date, and it can repeat a bias. This video shows each one and what to do about it." },
                { id: "dmf-m3-t6-ln2", ts: "0:27", text: "First, invented facts. The assistant builds sentences that sound likely. Ask it for a statistic about email open rates and it may give you a neat percentage with a source that does not exist." },
                { id: "dmf-m3-t6-ln3", ts: "0:50", text: "The fix is a rule, not a better prompt: no number, quote, name or date is published until you have found it in a source you can open and read." },
                { id: "dmf-m3-t6-ln4", ts: "1:10", text: "Second, old information. A model learns from text collected up to a certain date. Prices, platform features and regulations change after that, and the assistant will describe last year's rules with full confidence." },
                { id: "dmf-m3-t6-ln5", ts: "1:32", text: "Third, bias. Ask for a picture of a chief executive, or a description of a typical nurse, and watch who appears. The model reproduces the patterns in what it learned from, including the unfair ones." },
                { id: "dmf-m3-t6-ln6", ts: "1:55", text: "In marketing that shows up as ad copy that assumes who does the cooking, or an audience suggestion that leaves out older customers. Read every draft asking: who is missing, and who is being assumed?" },
                { id: "dmf-m3-t6-ln7", ts: "2:18", text: "You can reduce all three. Give the assistant the facts yourself. Ask it to mark anything it was not given. Ask for a second version written for a different reader, and compare." },
                { id: "dmf-m3-t6-ln8", ts: "2:39", text: "None of this removes the review. Whoever publishes the copy answers for it, and that is you." },
              ],
            },
            { id: "dmf-m3-t7", type: "Reading", title: "Customer data and AI tools: what not to paste", duration: "approx. 12 min read", completed: true },
            { id: "dmf-m3-t8", type: "Practice Assignment", title: "Practice Quiz: Prompting basics", duration: "approx. 10 min", completed: true },
            { id: "dmf-m3-t9", type: "Video", title: "An AI-assisted workflow, start to finish", duration: "22 min", completed: true },
            { id: "dmf-m3-t10", type: "Quiz", title: "Graded Quiz: The AI mindset", duration: "approx. 15 min", completed: true },
          ],
        },
      ],
    },
    {
      id: "dmf-m4",
      label: "MODULE 04",
      title: "Final Project, Assessment, and Wrap-Up",
      topicsCompleted: 6,
      topicsTotal: 6,
      isCompleted: true,
      lessons: [
        {
          id: "dmf-m4-l1",
          label: "Final project",
          topics: [
            { id: "dmf-m4-t1", type: "Reading", title: "Final project brief: a one-page marketing plan", duration: "approx. 15 min read", completed: true },
            { id: "dmf-m4-t2", type: "Video", title: "Planning your one-page marketing plan", duration: "14 min", completed: true },
            { id: "dmf-m4-t3", type: "Project", title: "Final Project: One-page marketing plan", duration: "approx. 2 h", completed: true },
            { id: "dmf-m4-t4", type: "Peer Review", title: "Review two marketing plans", duration: "approx. 20 min", completed: true },
          ],
        },
        {
          id: "dmf-m4-l2",
          label: "Assessment and wrap-up",
          topics: [
            { id: "dmf-m4-t5", type: "Quiz", title: "Final Assessment", duration: "approx. 20 min", completed: true },
            { id: "dmf-m4-t6", type: "Video", title: "Course wrap-up and next steps", duration: "5 min", completed: true },
          ],
        },
      ],
    },
  ],
};
