import type { Course } from "@/lib/courses/kit";

/**
 * "Paid Advertising, Media & AI-Integrated Campaign Strategy": course 4 of the AI Augmented
 * Digital Marketing program. 54 topics, none done: the learner has not started it, so it
 * opens on its "Course Introduction" video. Module 4 is locked until Module 3 is complete.
 */
export const outline: Course = {
  id: "paid",
  slug: "paid-advertising-media-and-ai-integrated-campaign-strategy",
  title: "Paid Advertising, Media & AI-Integrated Campaign Strategy",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Beginner",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 0,
  modulesCompleted: 0,
  modulesTotal: 4,
  modules: [
    {
      id: "paid-m1",
      label: "MODULE 01",
      title: "Paid Media Foundations & Search Advertising",
      topicsCompleted: 0,
      topicsTotal: 16,
      isCompleted: false,
      lessons: [
        {
          id: "paid-m1-l1",
          label: "How paid media works",
          topics: [
            {
              id: "paid-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "6 min",
              completed: false,
              active: true,
              transcript: [
                { id: "paid-m1-t1-ln1", ts: "0:00", text: "Welcome to course 4. In course 3 you earned attention. In this course you buy it, and you learn to buy it carefully." },
                { id: "paid-m1-t1-ln2", ts: "0:16", text: "Paid media is any placement you pay for: an ad above the search results, a post in a social feed, a banner on a news site, a video before another video." },
                { id: "paid-m1-t1-ln3", ts: "0:35", text: "Most of it is sold by auction, and most of the bidding is now automated. That changes your job from setting bids to setting goals, budgets and limits." },
                { id: "paid-m1-t1-ln4", ts: "0:54", text: "Module 1 covers how auctions work and how to build a search campaign. Module 2 covers social, display and video, and how to plan a budget across them." },
                { id: "paid-m1-t1-ln5", ts: "1:13", text: "Module 3 is about measurement and testing, and about working with automated campaigns: what you control, what you do not, and the guardrails you set." },
                { id: "paid-m1-t1-ln6", ts: "1:32", text: "You do not need an advertising account or a budget. Every exercise uses the sample accounts and reports in the Handouts." },
                { id: "paid-m1-t1-ln7", ts: "1:48", text: "In Module 4 you plan an integrated campaign for one product. The first reading is next: paid media in the marketing mix." },
              ],
            },
            { id: "paid-m1-t2", type: "Reading", title: "Paid media in the marketing mix", duration: "approx. 10 min read", completed: false },
            {
              id: "paid-m1-t3",
              type: "Video",
              title: "How an ad auction works: bids, quality and rank",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "paid-m1-t3-ln1", ts: "0:00", text: "Every time someone searches, an auction decides which ads appear and in what order. It takes a fraction of a second, and the highest bid does not always win. Here is how it works." },
                { id: "paid-m1-t3-ln2", ts: "0:23", text: "Each advertiser enters with a bid: the most they are willing to pay for a click. If money were the only factor, the richest advertiser would own every search and people would see poor ads." },
                { id: "paid-m1-t3-ln3", ts: "0:46", text: "So the platform adds a second factor, quality. It estimates how likely the ad is to be clicked, how closely it matches the search, and how useful the landing page is." },
                { id: "paid-m1-t3-ln4", ts: "1:07", text: "Bid and quality together give the ad rank. In its simplest form, think of it as the bid multiplied by a quality score. The ad with the highest rank takes the top position." },
                { id: "paid-m1-t3-ln5", ts: "1:29", text: "Take two advertisers. One bids 2.00 with a quality score of 4: rank 8. The other bids 1.50 with a score of 8: rank 12. The lower bid wins the higher place." },
                { id: "paid-m1-t3-ln6", ts: "1:50", text: "The price is also set by rank. You pay only what is needed to stay above the advertiser below you, so the winner here pays well under 1.50." },
                { id: "paid-m1-t3-ln7", ts: "2:09", text: "Real auctions use more signals than this, and the platforms do not publish the formula. The lesson holds anyway: a more relevant ad buys the same position for less." },
                { id: "paid-m1-t3-ln8", ts: "2:28", text: "That is why the next topics spend so much time on structure, keywords and landing pages. They are how you raise quality." },
              ],
            },
            { id: "paid-m1-t4", type: "Reading", title: "Pricing models: cost per thousand, per click and per action", duration: "approx. 10 min read", completed: false },
            {
              id: "paid-m1-t5",
              type: "Video",
              title: "Campaign structure: accounts, campaigns and ad groups",
              duration: "12 min",
              completed: false,
              transcript: [
                { id: "paid-m1-t5-ln1", ts: "0:00", text: "A search account is built in three levels: the account, its campaigns, and the ad groups inside each campaign. A tidy structure is what makes relevant ads possible, so it is worth ten minutes before you write anything." },
                { id: "paid-m1-t5-ln2", ts: "0:25", text: "The account holds billing, access and conversion tracking. Most businesses need one." },
                { id: "paid-m1-t5-ln3", ts: "0:33", text: "A campaign is where you set the budget, the locations, the language and the bid strategy. So make a separate campaign whenever one of those must differ: a different product line, a different country, a different goal." },
                { id: "paid-m1-t5-ln4", ts: "0:58", text: "An ad group sits inside a campaign and holds two things: a small set of closely related keywords, and the ads written for exactly those keywords." },
                { id: "paid-m1-t5-ln5", ts: "1:15", text: "Take a shop selling running gear. One campaign for shoes, one for clothing. Inside shoes, an ad group for trail running shoes, one for road running shoes, one for children's sizes." },
                { id: "paid-m1-t5-ln6", ts: "1:36", text: "The test of an ad group is simple. Could one ad honestly answer every keyword in it? If trail shoes and waterproof jackets share a group, no single headline fits both, and relevance drops." },
                { id: "paid-m1-t5-ln7", ts: "1:59", text: "Each ad group also points to its own landing page. Trail shoe searches land on trail shoes, not on the home page." },
                { id: "paid-m1-t5-ln8", ts: "2:14", text: "Name things so that a stranger could read them: country, product, intent. You will be glad of it when you open the reports. In the activity you sort twenty keywords into ad groups this way." },
              ],
            },
            { id: "paid-m1-t6", type: "Activity", title: "Sort twenty keywords into ad groups", duration: "approx. 20 min", completed: false },
          ],
        },
        {
          id: "paid-m1-l2",
          label: "Search campaigns",
          topics: [
            {
              id: "paid-m1-t7",
              type: "Video",
              title: "Keywords and match types",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "paid-m1-t7-ln1", ts: "0:00", text: "In a search campaign you do not choose searches one by one. You choose keywords, and a match type that says how far a search may stray from the keyword and still show your ad." },
                { id: "paid-m1-t7-ln2", ts: "0:23", text: "There are three match types. Exact match shows the ad for searches with the same meaning as the keyword. Trail running shoes also matches running shoes for trails, and little else." },
                { id: "paid-m1-t7-ln3", ts: "0:44", text: "Phrase match shows the ad when the search includes the meaning of the keyword, with other words before or after. Trail running shoes can match best trail running shoes for women." },
                { id: "paid-m1-t7-ln4", ts: "1:05", text: "Broad match is the loosest. The platform may show the ad for anything it judges related: hiking trainers, off-road footwear, even a search for a rival product. It reaches the most searches and the most irrelevant ones." },
                { id: "paid-m1-t7-ln5", ts: "1:30", text: "Think of it as a trade between control and reach. Exact gives you clean data and misses searches you never thought of. Broad finds new searches and spends on some you would never have chosen." },
                { id: "paid-m1-t7-ln6", ts: "1:53", text: "A sound way to start on a small budget: exact and phrase on the terms you know convert. Add broad later, once conversion tracking works, with automated bidding and a list of negative keywords." },
                { id: "paid-m1-t7-ln7", ts: "2:16", text: "Whatever you choose, the keyword is only your side of the deal. What people really typed appears in the search terms report, and that report is the next topic." },
              ],
            },
            { id: "paid-m1-t8", type: "Reading", title: "Negative keywords and the search terms report", duration: "approx. 10 min read", completed: false },
            {
              id: "paid-m1-t9",
              type: "Video",
              title: "Writing search ads with an AI assistant",
              duration: "16 min",
              completed: false,
              transcript: [
                { id: "paid-m1-t9-ln1", ts: "0:00", text: "A search ad is a few short headlines and a couple of descriptions, with strict character limits. An AI assistant is well suited to producing many of them. In this video we write a set together, and you will see where it needs you." },
                { id: "paid-m1-t9-ln2", ts: "0:29", text: "The usual format is a responsive search ad. You supply up to fifteen headlines of thirty characters and four descriptions of ninety. The platform tests combinations and shows the ones that perform." },
                { id: "paid-m1-t9-ln3", ts: "0:50", text: "Start with the brief, not the prompt. The ad group is trail running shoes. The reader is choosing a first pair. The facts: free returns for thirty days, delivery in two days, prices from 89." },
                { id: "paid-m1-t9-ln4", ts: "1:13", text: "Now the prompt. Role: a search ad copywriter. Task: twelve headlines and four descriptions. Context: those facts and that reader. Format: the character limits, the keyword in at least three headlines, no claims beyond the facts given." },
                { id: "paid-m1-t9-ln5", ts: "1:38", text: "Read what comes back. Some headlines run over thirty characters, because assistants count badly. One says best-rated trail shoes, which nobody told it. That one goes, unless we can prove it." },
                { id: "paid-m1-t9-ln6", ts: "1:59", text: "Check that the headlines work in any order. The platform will pair them freely, so two that both say free returns waste the space. Aim for variety: the product, a benefit, proof, an offer, a call to action." },
                { id: "paid-m1-t9-ln7", ts: "2:24", text: "Last, compare the ad with the landing page. Every promise in a headline has to be visible on the page the click leads to. The assistant has not seen that page. You have." },
              ],
            },
            { id: "paid-m1-t10", type: "Reading", title: "Landing pages that keep the promise of the ad", duration: "approx. 12 min read", completed: false },
            { id: "paid-m1-t11", type: "Activity", title: "Draft three ad variants from one brief", duration: "approx. 25 min", completed: false },
          ],
        },
        {
          id: "paid-m1-l3",
          label: "Budgets and bidding",
          topics: [
            {
              id: "paid-m1-t12",
              type: "Video",
              title: "Budgets, bid strategies and automated bidding",
              duration: "16 min",
              completed: false,
              transcript: [
                { id: "paid-m1-t12-ln1", ts: "0:00", text: "Two settings decide what a campaign spends: the budget, which is the limit, and the bid strategy, which is how the platform uses the money inside that limit." },
                { id: "paid-m1-t12-ln2", ts: "0:19", text: "The budget is usually set per day. Platforms may spend more on a busy day and less on a quiet one, and even it out over the month. So think in monthly terms: a daily budget of 20 is roughly 600 a month." },
                { id: "paid-m1-t12-ln3", ts: "0:48", text: "With manual bidding you set the most you will pay for a click, keyword by keyword. You have full control and a great deal of work, and you bid the same for every searcher." },
                { id: "paid-m1-t12-ln4", ts: "1:11", text: "Automated bidding sets a bid for each auction, using signals you could never act on by hand: the device, the time, the place, what the person searched before." },
                { id: "paid-m1-t12-ln5", ts: "1:30", text: "You choose the goal. Maximise clicks buys traffic. Maximise conversions buys results within the budget. Target cost per acquisition and target return on ad spend aim for a figure you set." },
                { id: "paid-m1-t12-ln6", ts: "1:51", text: "Automation learns from conversions. It needs tracking that works and enough results to find a pattern. A common rule of thumb is a few dozen conversions a month in a campaign. With fewer, start with maximise clicks and a bid limit." },
                { id: "paid-m1-t12-ln7", ts: "2:18", text: "After any change, the system relearns for a week or two, and results swing during that time. Changing the target every other day keeps it learning for ever." },
                { id: "paid-m1-t12-ln8", ts: "2:37", text: "So your work moves up a level. You no longer set the bid. You set the goal, the budget, the tracking and the limits, and you judge the result." },
              ],
            },
            { id: "paid-m1-t13", type: "Reading", title: "Quality signals and what lowers your cost per click", duration: "approx. 10 min read", completed: false },
            { id: "paid-m1-t14", type: "Practice Assignment", title: "Practice Quiz: Auctions and search ads", duration: "approx. 10 min", completed: false },
            { id: "paid-m1-t15", type: "Graded Assignment", title: "Assignment 01 · Search campaign plan", duration: "approx. 45 min", completed: false },
            { id: "paid-m1-t16", type: "Quiz", title: "Graded Quiz: Paid media foundations", duration: "approx. 15 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "paid-m2",
      label: "MODULE 02",
      title: "Social, Display and Video Advertising",
      topicsCompleted: 0,
      topicsTotal: 16,
      isCompleted: false,
      lessons: [
        {
          id: "paid-m2-l1",
          label: "Paid social",
          topics: [
            { id: "paid-m2-t1", type: "Video", title: "How paid social differs from search", duration: "12 min", completed: false },
            { id: "paid-m2-t2", type: "Reading", title: "Audiences: interests, customer lists and lookalikes", duration: "approx. 12 min read", completed: false },
            {
              id: "paid-m2-t3",
              type: "Video",
              title: "Creative that stops the scroll: hook, proof and offer",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "paid-m2-t3-ln1", ts: "0:00", text: "On a social feed your ad sits between a friend's holiday and a video of a dog. Nobody asked for it. A structure of three parts gives it a chance: hook, proof and offer." },
                { id: "paid-m2-t3-ln2", ts: "0:23", text: "The hook is the first second and a half of a video, or the first line and image of a post. Its only job is to make the right person stop. Name their situation: blisters after every long run?" },
                { id: "paid-m2-t3-ln3", ts: "0:49", text: "Weak hooks start with the brand. Our new collection is here means nothing to a stranger. Start with the viewer's problem, a surprising result, or a clear picture of the product in use." },
                { id: "paid-m2-t3-ln4", ts: "1:11", text: "Proof is the reason to believe what the hook implied. Show, do not claim: the shoe on a wet trail, a customer's own words, a count of reviews you can back up. One strong proof beats three thin ones." },
                { id: "paid-m2-t3-ln5", ts: "1:37", text: "The offer is what to do now and why now. Try them for thirty days, free returns. Say it in words and put it on screen, because many people watch with the sound off." },
                { id: "paid-m2-t3-ln6", ts: "2:00", text: "Build for the feed. Vertical format, captions, the product visible in the first two seconds, and the whole message understandable without audio." },
                { id: "paid-m2-t3-ln7", ts: "2:15", text: "Then vary one part at a time. Three hooks on the same proof and offer will tell you which opening works. Change all three at once and you learn nothing." },
                { id: "paid-m2-t3-ln8", ts: "2:35", text: "In the activity you write hooks for one product and three audiences. First, a reading on the formats these ads can take." },
              ],
            },
            { id: "paid-m2-t4", type: "Reading", title: "Ad formats: image, carousel, short video and stories", duration: "approx. 10 min read", completed: false },
            { id: "paid-m2-t5", type: "Activity", title: "Write hooks for one product and three audiences", duration: "approx. 20 min", completed: false },
            { id: "paid-m2-t6", type: "Video", title: "Generating creative variants with AI tools", duration: "14 min", completed: false },
          ],
        },
        {
          id: "paid-m2-l2",
          label: "Display, video and retargeting",
          topics: [
            { id: "paid-m2-t7", type: "Video", title: "Display and programmatic buying in plain terms", duration: "14 min", completed: false },
            { id: "paid-m2-t8", type: "Reading", title: "Brand safety, placements and exclusions", duration: "approx. 10 min read", completed: false },
            { id: "paid-m2-t9", type: "Video", title: "Video advertising: skippable, in-feed and connected TV", duration: "14 min", completed: false },
            { id: "paid-m2-t10", type: "Reading", title: "Retargeting and frequency caps", duration: "approx. 10 min read", completed: false },
            { id: "paid-m2-t11", type: "Reading", title: "Privacy, consent and advertising without third-party cookies", duration: "approx. 12 min read", completed: false },
          ],
        },
        {
          id: "paid-m2-l3",
          label: "Media planning",
          topics: [
            { id: "paid-m2-t12", type: "Video", title: "Reach, frequency and the media plan", duration: "16 min", completed: false },
            { id: "paid-m2-t13", type: "Reading", title: "Splitting a budget across channels", duration: "approx. 12 min read", completed: false },
            { id: "paid-m2-t14", type: "Practice Assignment", title: "Practice Quiz: Social, display and video", duration: "approx. 10 min", completed: false },
            { id: "paid-m2-t15", type: "Activity", title: "Build a one-month media plan", duration: "approx. 25 min", completed: false },
            { id: "paid-m2-t16", type: "Graded Assignment", title: "Assignment 02 · Paid social campaign brief", duration: "approx. 45 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "paid-m3",
      label: "MODULE 03",
      title: "Measurement, Optimization & AI-Integrated Strategy",
      topicsCompleted: 0,
      topicsTotal: 16,
      isCompleted: false,
      lessons: [
        {
          id: "paid-m3-l1",
          label: "Tracking and attribution",
          topics: [
            { id: "paid-m3-t1", type: "Video", title: "Conversion tracking: tags, pixels and events", duration: "14 min", completed: false },
            { id: "paid-m3-t2", type: "Reading", title: "Naming campaigns and tagging links", duration: "approx. 10 min read", completed: false },
            {
              id: "paid-m3-t3",
              type: "Video",
              title: "Attribution models and what each one hides",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "paid-m3-t3-ln1", ts: "0:00", text: "A customer sees a video ad on Monday, clicks a social ad on Wednesday, searches the brand on Friday and buys. Which ad earned the sale? An attribution model is the rule that answers, and every rule hides something." },
                { id: "paid-m3-t3-ln2", ts: "0:26", text: "Last click gives all the credit to the final touch, here the brand search. It is simple, and it flatters whatever comes last. It hides the ads that made the person search for you in the first place." },
                { id: "paid-m3-t3-ln3", ts: "0:51", text: "First click does the opposite. The video gets everything. It rewards discovery and hides the work of closing the sale." },
                { id: "paid-m3-t3-ln4", ts: "1:04", text: "Linear splits the credit evenly across every touch. Position-based gives most to the first and the last and shares the rest. Both are fairer, and both are still fixed rules that ignore what really made the difference." },
                { id: "paid-m3-t3-ln5", ts: "1:29", text: "Data-driven attribution lets the platform assign credit from patterns across many journeys. It is the default in many tools. It needs volume, you cannot inspect its reasoning, and each platform runs its own." },
                { id: "paid-m3-t3-ln6", ts: "1:51", text: "Which leads to the larger problem. Every platform counts the sales it touched. Add up the conversions claimed by each one and the total can exceed the orders in your shop." },
                { id: "paid-m3-t3-ln7", ts: "2:12", text: "And no model sees everything. A view on one device and a purchase on another, a recommendation from a friend, a visitor who declined tracking: all of it is missing." },
                { id: "paid-m3-t3-ln8", ts: "2:32", text: "So use attribution to compare campaigns inside one platform, with one model, kept the same over time. For the question would this sale have happened anyway, you need a test, which is the next reading." },
              ],
            },
            { id: "paid-m3-t4", type: "Reading", title: "Return on ad spend, cost per acquisition and incrementality", duration: "approx. 12 min read", completed: false },
            { id: "paid-m3-t5", type: "Activity", title: "Read a campaign report and find the waste", duration: "approx. 20 min", completed: false },
          ],
        },
        {
          id: "paid-m3-l2",
          label: "Testing and optimization",
          topics: [
            { id: "paid-m3-t6", type: "Video", title: "Designing an A/B test for ads", duration: "14 min", completed: false },
            { id: "paid-m3-t7", type: "Reading", title: "Sample size and when to stop a test", duration: "approx. 10 min read", completed: false },
            { id: "paid-m3-t8", type: "Video", title: "Optimization routines: daily, weekly and monthly", duration: "12 min", completed: false },
            { id: "paid-m3-t9", type: "Reading", title: "Landing page tests that move the conversion rate", duration: "approx. 10 min read", completed: false },
            { id: "paid-m3-t10", type: "Practice Assignment", title: "Practice Quiz: Measurement and testing", duration: "approx. 10 min", completed: false },
          ],
        },
        {
          id: "paid-m3-l3",
          label: "AI-integrated campaign strategy",
          topics: [
            { id: "paid-m3-t11", type: "Video", title: "Automated campaign types: what you control and what you do not", duration: "16 min", completed: false },
            { id: "paid-m3-t12", type: "Reading", title: "Feeding the algorithm: signals, creative and budgets", duration: "approx. 12 min read", completed: false },
            { id: "paid-m3-t13", type: "Video", title: "An AI-assisted campaign workflow, from brief to report", duration: "18 min", completed: false },
            { id: "paid-m3-t14", type: "Reading", title: "Guardrails: brand, budget and policy checks", duration: "approx. 10 min read", completed: false },
            { id: "paid-m3-t15", type: "Activity", title: "Write the guardrails for an automated campaign", duration: "approx. 20 min", completed: false },
            { id: "paid-m3-t16", type: "Quiz", title: "Graded Quiz: Measurement and AI-integrated strategy", duration: "approx. 15 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "paid-m4",
      label: "MODULE 04",
      title: "Final Project, Assessment, and Wrap-Up",
      topicsCompleted: 0,
      topicsTotal: 6,
      isCompleted: false,
      lessons: [
        {
          id: "paid-m4-l1",
          label: "Final project",
          topics: [
            { id: "paid-m4-t1", type: "Reading", title: "Final project brief: an integrated campaign plan", duration: "approx. 15 min read", completed: false, locked: true },
            { id: "paid-m4-t2", type: "Video", title: "Planning your integrated campaign plan", duration: "14 min", completed: false, locked: true },
            { id: "paid-m4-t3", type: "Project", title: "Final Project: Integrated campaign plan", duration: "approx. 2 h", completed: false, locked: true },
            { id: "paid-m4-t4", type: "Peer Review", title: "Review two campaign plans", duration: "approx. 20 min", completed: false, locked: true },
          ],
        },
        {
          id: "paid-m4-l2",
          label: "Assessment and wrap-up",
          topics: [
            { id: "paid-m4-t5", type: "Quiz", title: "Final Assessment", duration: "approx. 20 min", completed: false, locked: true },
            { id: "paid-m4-t6", type: "Video", title: "Course wrap-up and next steps", duration: "5 min", completed: false, locked: true },
          ],
        },
      ],
    },
  ],
};
