import type { Course } from "@/lib/courses/kit";

/**
 * "Social Media and Ecommerce Marketing": course 5 of the AI Augmented Digital Marketing
 * program, not started. 64 topics in 5 modules, none done; Module 5 is locked until
 * Module 4 is complete. It opens on "Course Introduction", as the Program page says.
 */
export const outline: Course = {
  id: "smec",
  slug: "social-media-and-ecommerce-marketing",
  title: "Social Media and Ecommerce Marketing",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Beginner",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 0,
  modulesCompleted: 0,
  modulesTotal: 5,
  modules: [
    {
      id: "smec-m1",
      label: "MODULE 01",
      title: "Social Media Strategy & Platform Fundamentals",
      topicsCompleted: 0,
      topicsTotal: 14,
      isCompleted: false,
      lessons: [
        {
          id: "smec-m1-l1",
          label: "Strategy before platforms",
          topics: [
            {
              id: "smec-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "6 min",
              completed: false,
              transcript: [
                { id: "smec-m1-t1-ln1", ts: "0:00", text: "Welcome to course 5 of the program. So far you have worked on content, search and paid media. This course is about the two places where a customer meets the brand most often: the social feed and the store." },
                { id: "smec-m1-t1-ln2", ts: "0:19", text: "We treat them as one journey. A post earns attention, a profile or a shop turns that attention into a visit, and a product page turns the visit into an order." },
                { id: "smec-m1-t1-ln3", ts: "0:37", text: "There are five modules. The first two cover social media: strategy and platforms, then content, community and creators." },
                { id: "smec-m1-t1-ln4", ts: "0:52", text: "Modules 3 and 4 cover ecommerce: selling inside social platforms, the storefront itself, and then conversion, retention and measurement." },
                { id: "smec-m1-t1-ln5", ts: "1:08", text: "You will use an AI assistant throughout: to audit a profile, to draft a week of posts, to rewrite a product page. Each time, you write the brief and you check the result." },
                { id: "smec-m1-t1-ln6", ts: "1:26", text: "Four assignments count towards your grade, one per module. In Module 5 you bring them together in a launch plan for one product, which two peers review." },
                { id: "smec-m1-t1-ln7", ts: "1:44", text: "Pick a business to work on now: your own, your employer's, or the case-study shop in Handouts. You will use the same one in every assignment." },
                { id: "smec-m1-t1-ln8", ts: "2:01", text: "Let's start with the question most teams skip: what is social media for, in this business?" },
              ],
            },
            { id: "smec-m1-t2", type: "Reading", title: "What social media is for: reach, relationship and revenue", duration: "approx. 10 min read", completed: false },
            {
              id: "smec-m1-t3",
              type: "Video",
              title: "Choosing platforms by audience and job, not by trend",
              duration: "12 min",
              completed: false,
              transcript: [
                { id: "smec-m1-t3-ln1", ts: "0:00", text: "New platforms appear every year, and each one is described as the place you have to be. This video gives you a calmer way to choose: by audience and by job." },
                { id: "smec-m1-t3-ln2", ts: "0:21", text: "Start with the audience. Where do the people you want to reach already spend time, and what are they doing there? A platform's total number of users tells you nothing about that." },
                { id: "smec-m1-t3-ln3", ts: "0:42", text: "Then the job, from the last reading: reach, relationship or revenue. Each kind of platform is better at some jobs than others." },
                { id: "smec-m1-t3-ln4", ts: "0:57", text: "Short-video platforms are built for reach. The feed shows your video to people who have never heard of you, if it holds attention." },
                { id: "smec-m1-t3-ln5", ts: "1:12", text: "Photo and story platforms suit relationship and, with a shop attached, revenue. Professional networks reach people in their working role. Messaging channels and groups serve the customers you already have." },
                { id: "smec-m1-t3-ln6", ts: "1:32", text: "Now check what you can sustain. A video platform needs two or three videos a week. If nobody on the team can film, that platform is a plan to fail, however good the audience." },
                { id: "smec-m1-t3-ln7", ts: "1:55", text: "For a small team, one platform done well and a second kept simple is usually right. A shop that sells spice kits picks short video for reach and one photo platform with a shop for revenue. It leaves the others." },
                { id: "smec-m1-t3-ln8", ts: "2:22", text: "Write down what you decided not to do, and why. When the next new platform arrives, you will have the questions ready." },
              ],
            },
            { id: "smec-m1-t4", type: "Reading", title: "How feeds rank content: signals you can and cannot influence", duration: "approx. 12 min read", completed: false },
            {
              id: "smec-m1-t5",
              type: "Video",
              title: "Setting social objectives and the metrics behind them",
              duration: "12 min",
              completed: false,
              transcript: [
                { id: "smec-m1-t5-ln1", ts: "0:00", text: "An objective says what you want social media to do for the business. A metric is the number that shows whether it is happening. In this video we write one of each for the three jobs." },
                { id: "smec-m1-t5-ln2", ts: "0:24", text: "Start with reach. Objective: people who cook at home discover our spice kits. The metrics are accounts reached that do not follow us, and how much of each video they watch." },
                { id: "smec-m1-t5-ln3", ts: "0:45", text: "Follower count is not the metric here. It grows slowly and says nothing about whether new people saw you this week." },
                { id: "smec-m1-t5-ln4", ts: "0:59", text: "For relationship, the objective might be: customers come to us with cooking questions and get an answer the same day. The metrics are replies and messages received, saves and shares, and response time." },
                { id: "smec-m1-t5-ln5", ts: "1:21", text: "For revenue: followers buy the new kit through the shop link. The metrics are link clicks, orders from social, and the value of those orders." },
                { id: "smec-m1-t5-ln6", ts: "1:38", text: "Now add a number and a date. Reach eight thousand non-followers a week by the end of the quarter. Without both, you cannot tell whether a month was good." },
                { id: "smec-m1-t5-ln7", ts: "1:57", text: "Keep to one main metric per objective and two supporting ones. A report with twenty numbers hides the one that matters." },
                { id: "smec-m1-t5-ln8", ts: "2:11", text: "And check the chain. If reach rises and nothing else moves, the content is attracting the wrong people, or the profile gives them no reason to stay. Profiles come later in this module." },
              ],
            },
            { id: "smec-m1-t6", type: "Activity", title: "Map three audiences to the platforms they use", duration: "approx. 15 min", completed: false },
            { id: "smec-m1-t7", type: "Practice Assignment", title: "Practice Quiz: Platforms and objectives", duration: "approx. 10 min", completed: false },
          ],
        },
        {
          id: "smec-m1-l2",
          label: "Profiles, pillars and listening",
          topics: [
            {
              id: "smec-m1-t8",
              type: "Video",
              title: "Profiles that turn a visit into a follow",
              duration: "10 min",
              completed: false,
              transcript: [
                { id: "smec-m1-t8-ln1", ts: "0:00", text: "Someone sees one of your posts, likes it and taps your name. They will give your profile about three seconds. In that time it has to answer three questions: who is this, what will I get, and what should I do?" },
                { id: "smec-m1-t8-ln2", ts: "0:27", text: "Start with the name and the picture. Use the name people would search for and a picture that is readable at the size of a fingernail. A logo with small text turns into a smudge." },
                { id: "smec-m1-t8-ln3", ts: "0:50", text: "The bio is one or two lines. Say what you offer and for whom, in plain words. Spice kits for weeknight cooking, with a new recipe every Tuesday, beats passionate about flavour." },
                { id: "smec-m1-t8-ln4", ts: "1:11", text: "That second half matters. A promise of what you post and how often tells the visitor what following will bring them." },
                { id: "smec-m1-t8-ln5", ts: "1:25", text: "Then one link, to the page that matches your leading job. If the job is revenue, the shop. If it is relationship, the newsletter sign-up. A link to the home page asks the visitor to do the work." },
                { id: "smec-m1-t8-ln6", ts: "1:50", text: "Use the pinned posts. Pin the three that best introduce you: what you sell, your most useful post, and proof from a customer. A newcomer should not meet last night's story about a delivery delay first." },
                { id: "smec-m1-t8-ln7", ts: "2:14", text: "Finally, look at the grid or the video list as a whole. Do the first nine posts make clear what you talk about? If a stranger cannot tell, neither can the feed." },
              ],
            },
            { id: "smec-m1-t9", type: "Reading", title: "Content pillars: what the brand talks about, and what it does not", duration: "approx. 10 min read", completed: false },
            {
              id: "smec-m1-t10",
              type: "Video",
              title: "Auditing a social presence with an AI assistant",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "smec-m1-t10-ln1", ts: "0:00", text: "An audit is a structured look at what a brand's social accounts are doing today. An AI assistant makes it much faster, as long as you give it real material and check what it tells you." },
                { id: "smec-m1-t10-ln2", ts: "0:24", text: "First collect the evidence yourself. For each account: the bio, the last twenty posts with their captions, and the numbers you can see, such as views, comments and shares. Paste them into a document." },
                { id: "smec-m1-t10-ln3", ts: "0:47", text: "An assistant without that material will describe the account from memory, or invent it. Never ask what do you think of this brand's social media. Ask it to analyse the text you supply." },
                { id: "smec-m1-t10-ln4", ts: "1:09", text: "Now the prompt. Role: a social media analyst. Task: sort these twenty posts by subject and format, and say which subjects get the most shares and comments. Format: a table, then three observations." },
                { id: "smec-m1-t10-ln5", ts: "1:31", text: "The table is where the time is saved. Sorting twenty captions by hand takes half an hour. The assistant does it in seconds, and you spot-check five rows." },
                { id: "smec-m1-t10-ln6", ts: "1:50", text: "Then ask a second question: read these forty comments and group what people ask for or complain about. Remove usernames first. You want the themes, not the people." },
                { id: "smec-m1-t10-ln7", ts: "2:09", text: "Treat the observations as hypotheses. The assistant may say recipe videos perform best because three of them did well. Look at the numbers and decide whether that is a pattern or one lucky week." },
                { id: "smec-m1-t10-ln8", ts: "2:32", text: "The audit ends in three lists: keep, stop and try. Those are your decisions. In Assignment 01 you run this audit on two platforms for the business you chose." },
              ],
            },
            { id: "smec-m1-t11", type: "Reading", title: "Social listening: what your audience already says", duration: "approx. 12 min read", completed: false },
            { id: "smec-m1-t12", type: "Activity", title: "Compare two competitors with the audit template", duration: "approx. 20 min", completed: false },
            { id: "smec-m1-t13", type: "Graded Assignment", title: "Assignment 01 · Platform and audience audit", duration: "approx. 40 min", completed: false },
            { id: "smec-m1-t14", type: "Quiz", title: "Graded Quiz: Social strategy and platforms", duration: "approx. 10 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "smec-m2",
      label: "MODULE 02",
      title: "Content, Community & Creator Partnerships",
      topicsCompleted: 0,
      topicsTotal: 14,
      isCompleted: false,
      lessons: [
        {
          id: "smec-m2-l1",
          label: "Content that earns attention",
          topics: [
            { id: "smec-m2-t1", type: "Video", title: "Formats and what each is good at: short video, carousels, stories, live", duration: "14 min", completed: false },
            { id: "smec-m2-t2", type: "Reading", title: "Hooks, captions and calls to action", duration: "approx. 10 min read", completed: false },
            { id: "smec-m2-t3", type: "Video", title: "Drafting a week of posts with an AI assistant", duration: "14 min", completed: false },
            { id: "smec-m2-t4", type: "Reading", title: "Repurposing one idea across platforms", duration: "approx. 10 min read", completed: false },
            { id: "smec-m2-t5", type: "Activity", title: "Turn one article into five social posts", duration: "approx. 20 min", completed: false },
            { id: "smec-m2-t6", type: "Video", title: "The content calendar and the approval flow", duration: "12 min", completed: false },
            { id: "smec-m2-t7", type: "Practice Assignment", title: "Practice Quiz: Formats and calendars", duration: "approx. 10 min", completed: false },
          ],
        },
        {
          id: "smec-m2-l2",
          label: "Community and creators",
          topics: [
            { id: "smec-m2-t8", type: "Reading", title: "Community management: replies, moderation and response times", duration: "approx. 12 min read", completed: false },
            { id: "smec-m2-t9", type: "Video", title: "Sorting comments and messages with AI, and where a person takes over", duration: "12 min", completed: false },
            { id: "smec-m2-t10", type: "Reading", title: "Working with creators: briefs, usage rights and disclosure", duration: "approx. 12 min read", completed: false },
            { id: "smec-m2-t11", type: "Video", title: "Choosing creators by fit and engagement, not follower count", duration: "12 min", completed: false },
            { id: "smec-m2-t12", type: "Activity", title: "Write a creator brief for one product", duration: "approx. 15 min", completed: false },
            { id: "smec-m2-t13", type: "Reading", title: "Answering a complaint in public: a worked case", duration: "approx. 8 min read", completed: false },
            { id: "smec-m2-t14", type: "Graded Assignment", title: "Assignment 02 · Two-week content calendar", duration: "approx. 40 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "smec-m3",
      label: "MODULE 03",
      title: "Social Commerce & Ecommerce Storefronts",
      topicsCompleted: 0,
      topicsTotal: 14,
      isCompleted: false,
      lessons: [
        {
          id: "smec-m3-l1",
          label: "Selling where people scroll",
          topics: [
            {
              id: "smec-m3-t1",
              type: "Video",
              title: "From post to purchase: how social commerce works",
              duration: "12 min",
              completed: false,
              transcript: [
                { id: "smec-m3-t1-ln1", ts: "0:00", text: "Social commerce means the purchase starts, and sometimes finishes, inside the social app. In this video we follow one order from a post to a doorstep, and name the parts that make it possible." },
                { id: "smec-m3-t1-ln2", ts: "0:23", text: "It begins with a catalogue: a list of your products with their names, prices, images and stock, held by the platform and kept in step with your store." },
                { id: "smec-m3-t1-ln3", ts: "0:42", text: "From the catalogue comes a shop: a storefront on your profile where people can browse. And from the catalogue come product tags, which you attach to a post or a video." },
                { id: "smec-m3-t1-ln4", ts: "1:03", text: "So a viewer watches a thirty-second recipe, sees a small tag for the curry kit, and taps it. A product card opens with the price and the photos, without leaving the app." },
                { id: "smec-m3-t1-ln5", ts: "1:24", text: "From there the path splits. On some platforms and in some countries, the viewer pays inside the app. On others, a button takes them to the product page on your own site to finish." },
                { id: "smec-m3-t1-ln6", ts: "1:47", text: "In-app checkout is quicker for the buyer, and you depend more on the platform: it handles the payment, takes a fee and holds more of the customer relationship. Checkout on your site keeps the relationship and adds a step." },
                { id: "smec-m3-t1-ln7", ts: "2:13", text: "Either way, the order has to be fulfilled, the stock updated and the customer answered, by you. A tag on a product that sold out yesterday is a broken promise in public." },
                { id: "smec-m3-t1-ln8", ts: "2:34", text: "The idea to keep is fewer steps between wanting and buying. The next reading takes the moving parts one at a time." },
              ],
            },
            { id: "smec-m3-t2", type: "Reading", title: "Shops, product tags and catalogues: the moving parts", duration: "approx. 12 min read", completed: false },
            { id: "smec-m3-t3", type: "Video", title: "Setting up a product catalogue and keeping it in sync", duration: "14 min", completed: false },
            { id: "smec-m3-t4", type: "Reading", title: "Live shopping and shoppable video: when they pay off", duration: "approx. 10 min read", completed: false },
            { id: "smec-m3-t5", type: "Activity", title: "Tag products in three sample posts", duration: "approx. 15 min", completed: false },
            { id: "smec-m3-t6", type: "Practice Assignment", title: "Practice Quiz: Social commerce basics", duration: "approx. 10 min", completed: false },
          ],
        },
        {
          id: "smec-m3-l2",
          label: "The storefront",
          topics: [
            { id: "smec-m3-t7", type: "Video", title: "Anatomy of a product page that sells", duration: "14 min", completed: false },
            { id: "smec-m3-t8", type: "Reading", title: "Writing product titles and descriptions with an AI assistant", duration: "approx. 12 min read", completed: false },
            { id: "smec-m3-t9", type: "Video", title: "Product photos and generated imagery: what must stay true", duration: "12 min", completed: false },
            { id: "smec-m3-t10", type: "Reading", title: "Marketplace or your own store: fees, control and customer data", duration: "approx. 12 min read", completed: false },
            { id: "smec-m3-t11", type: "Activity", title: "Rewrite a product page from customers' questions", duration: "approx. 20 min", completed: false },
            { id: "smec-m3-t12", type: "Reading", title: "Reviews and customer content as proof", duration: "approx. 8 min read", completed: false },
            { id: "smec-m3-t13", type: "Graded Assignment", title: "Assignment 03 · Product page and shop listing", duration: "approx. 40 min", completed: false },
            { id: "smec-m3-t14", type: "Quiz", title: "Graded Quiz: Social commerce and storefronts", duration: "approx. 10 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "smec-m4",
      label: "MODULE 04",
      title: "Ecommerce Growth: Conversion, Retention & Analytics",
      topicsCompleted: 0,
      topicsTotal: 14,
      isCompleted: false,
      lessons: [
        {
          id: "smec-m4-l1",
          label: "Conversion",
          topics: [
            { id: "smec-m4-t1", type: "Video", title: "The ecommerce funnel: sessions, carts, checkouts, orders", duration: "12 min", completed: false },
            { id: "smec-m4-t2", type: "Reading", title: "Reading a funnel report: where shoppers leave, and why", duration: "approx. 12 min read", completed: false },
            { id: "smec-m4-t3", type: "Video", title: "Checkout friction: delivery costs, payment and trust", duration: "12 min", completed: false },
            { id: "smec-m4-t4", type: "Reading", title: "Abandoned carts: reminders that help and reminders that annoy", duration: "approx. 10 min read", completed: false },
            { id: "smec-m4-t5", type: "Activity", title: "Find the biggest leak in a sample funnel", duration: "approx. 20 min", completed: false },
            { id: "smec-m4-t6", type: "Video", title: "Testing one change at a time in a small store", duration: "12 min", completed: false },
            { id: "smec-m4-t7", type: "Practice Assignment", title: "Practice Quiz: Funnel metrics", duration: "approx. 10 min", completed: false },
          ],
        },
        {
          id: "smec-m4-l2",
          label: "Retention and measurement",
          topics: [
            { id: "smec-m4-t8", type: "Reading", title: "Average order value, repeat rate and customer lifetime value", duration: "approx. 12 min read", completed: false },
            { id: "smec-m4-t9", type: "Video", title: "Bundles, cross-sells and AI recommendations", duration: "14 min", completed: false },
            { id: "smec-m4-t10", type: "Reading", title: "Attribution for social: tagged links, platform reports and their limits", duration: "approx. 12 min read", completed: false },
            { id: "smec-m4-t11", type: "Video", title: "A weekly ecommerce dashboard you will actually read", duration: "12 min", completed: false },
            { id: "smec-m4-t12", type: "Activity", title: "Tag five campaign links and find them in a report", duration: "approx. 15 min", completed: false },
            { id: "smec-m4-t13", type: "Reading", title: "Customer data, consent and privacy in ecommerce", duration: "approx. 10 min read", completed: false },
            { id: "smec-m4-t14", type: "Graded Assignment", title: "Assignment 04 · Funnel and retention analysis", duration: "approx. 40 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "smec-m5",
      label: "MODULE 05",
      title: "Final Project, Assessment, and Wrap-Up",
      topicsCompleted: 0,
      topicsTotal: 8,
      isCompleted: false,
      lessons: [
        {
          id: "smec-m5-l1",
          label: "Final project",
          topics: [
            { id: "smec-m5-t1", type: "Reading", title: "Final project brief: a social commerce launch plan", duration: "approx. 12 min read", completed: false, locked: true },
            { id: "smec-m5-t2", type: "Video", title: "Planning a launch: channels, calendar and budget", duration: "12 min", completed: false, locked: true },
            { id: "smec-m5-t3", type: "Activity", title: "Draft the launch timeline", duration: "approx. 15 min", completed: false, locked: true },
            { id: "smec-m5-t4", type: "Project", title: "Final Project: Social commerce launch plan", duration: "approx. 90 min", completed: false, locked: true },
            { id: "smec-m5-t5", type: "Peer Review", title: "Review two launch plans", duration: "approx. 20 min", completed: false, locked: true },
          ],
        },
        {
          id: "smec-m5-l2",
          label: "Assessment and wrap-up",
          topics: [
            { id: "smec-m5-t6", type: "Reading", title: "How the final assessment works", duration: "approx. 6 min read", completed: false, locked: true },
            { id: "smec-m5-t7", type: "Quiz", title: "Final Assessment", duration: "approx. 20 min", completed: false, locked: true },
            { id: "smec-m5-t8", type: "Video", title: "Course wrap-up and next steps", duration: "5 min", completed: false, locked: true },
          ],
        },
      ],
    },
  ],
};
