import type { Course } from "@/lib/courses/kit";

/**
 * "Identity, Access and Cloud Security": course 3 of 5 of the Cybersecurity Fundamentals
 * Certificate, not started. 39 topics in 4 modules, none done: the player opens on
 * the first topic. Module 4 is locked until Module 3 is complete.
 */
export const outline: Course = {
  id: "sec3",
  slug: "identity-access-and-cloud-security",
  title: "Identity, Access and Cloud Security",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Beginner",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 0,
  modulesCompleted: 0,
  modulesTotal: 4,
  modules: [
    {
      id: "sec3-m1",
      label: "MODULE 01",
      title: "Identity and Authentication",
      topicsCompleted: 0,
      topicsTotal: 9,
      isCompleted: false,
      lessons: [
        {
          id: "sec3-m1-l1",
          label: "Proving who you are",
          topics: [
            {
              id: "sec3-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "6 min",
              completed: false,
              transcript: [
                {
                  id: "sec3-m1-t1-ln1",
                  ts: "0:00",
                  text: "Welcome to Identity, Access and Cloud Security, the third course of the Cybersecurity Fundamentals Certificate.",
                },
                {
                  id: "sec3-m1-t1-ln2",
                  ts: "0:20",
                  text: "When work happened inside one office, the network edge was the boundary. Today staff sign in to cloud services from anywhere, so the account has become the boundary.",
                },
                {
                  id: "sec3-m1-t1-ln3",
                  ts: "0:40",
                  text: "Module 1 is about proving identity: authentication factors, phishing-resistant sign-in and single sign-on.",
                },
                {
                  id: "sec3-m1-t1-ln4",
                  ts: "0:55",
                  text: "Module 2 is about what an identity may do once it is in: least privilege, roles, privileged accounts and regular access reviews.",
                },
                {
                  id: "sec3-m1-t1-ln5",
                  ts: "1:15",
                  text: "Module 3 moves to the cloud: who secures what under the shared responsibility model, and the misconfigurations behind most cloud exposures.",
                },
                {
                  id: "sec3-m1-t1-ln6",
                  ts: "1:30",
                  text: "Module 4 covers the data itself: classification, encryption, keys, backups and safe sharing.",
                },
                {
                  id: "sec3-m1-t1-ln7",
                  ts: "1:50",
                  text: "You will design an access model for a thirty-person company and review the security settings of a sample cloud account. Begin with the reading that follows.",
                },
              ],
            },
            {
              id: "sec3-m1-t2",
              type: "Reading",
              title: "Identification, authentication and authorisation",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec3-m1-t3",
              type: "Video",
              title: "Authentication factors and how they fail",
              duration: "13 min",
              completed: false,
              transcript: [
                {
                  id: "sec3-m1-t3-ln1",
                  ts: "0:00",
                  text: "An authentication factor is a kind of evidence that you are who you claim to be. There are three kinds.",
                },
                {
                  id: "sec3-m1-t3-ln2",
                  ts: "0:20",
                  text: "Something you know, such as a password or a PIN. Something you have, such as a phone or a security key. Something you are, such as a fingerprint or your face.",
                },
                {
                  id: "sec3-m1-t3-ln3",
                  ts: "0:40",
                  text: "Multi-factor authentication asks for two different kinds. Two passwords are not two factors: both are things you know, and both can be stolen the same way.",
                },
                {
                  id: "sec3-m1-t3-ln4",
                  ts: "0:55",
                  text: "Each factor fails in its own way. Passwords are reused, guessed and given away on fake sign-in pages.",
                },
                {
                  id: "sec3-m1-t3-ln5",
                  ts: "1:15",
                  text: "Codes sent by text message can be intercepted, or read out to a caller who pretends to be support. Approval prompts can be accepted by a tired user who is asked often enough.",
                },
                {
                  id: "sec3-m1-t3-ln6",
                  ts: "1:30",
                  text: "The strongest common methods bind the sign-in to the real site. A passkey or a hardware security key checks the site's address itself, so a look-alike page gets nothing it can reuse.",
                },
                {
                  id: "sec3-m1-t3-ln7",
                  ts: "1:50",
                  text: "The lesson for a defender: turn multi-factor authentication on everywhere, then move the most important accounts to the phishing-resistant methods first. The next reading shows how.",
                },
              ],
            },
            {
              id: "sec3-m1-t4",
              type: "Reading",
              title: "Phishing-resistant sign-in: passkeys and security keys",
              duration: "approx. 13 min read",
              completed: false,
            },
            {
              id: "sec3-m1-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Authentication",
              duration: "approx. 8 min",
              completed: false,
            },
          ],
        },
        {
          id: "sec3-m1-l2",
          label: "Signing in once",
          topics: [
            { id: "sec3-m1-t6", type: "Video", title: "Single sign-on and federation", duration: "12 min", completed: false },
            {
              id: "sec3-m1-t7",
              type: "Reading",
              title: "Directories and the identity lifecycle",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec3-m1-t8",
              type: "Activity",
              title: "Choose a sign-in method for six scenarios",
              duration: "approx. 15 min",
              completed: false,
            },
            {
              id: "sec3-m1-t9",
              type: "Quiz",
              title: "Graded Quiz: Identity and authentication",
              duration: "approx. 12 min",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sec3-m2",
      label: "MODULE 02",
      title: "Access Control",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "sec3-m2-l1",
          label: "Deciding who can do what",
          topics: [
            {
              id: "sec3-m2-t1",
              type: "Video",
              title: "Least privilege and separation of duties",
              duration: "12 min",
              completed: false,
            },
            {
              id: "sec3-m2-t2",
              type: "Reading",
              title: "Role-based and attribute-based access control",
              duration: "approx. 14 min read",
              completed: false,
            },
            {
              id: "sec3-m2-t3",
              type: "Video",
              title: "Privileged accounts and how to contain them",
              duration: "13 min",
              completed: false,
            },
            {
              id: "sec3-m2-t4",
              type: "Reading",
              title: "Joiners, movers and leavers",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec3-m2-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Access control",
              duration: "approx. 8 min",
              completed: false,
            },
          ],
        },
        {
          id: "sec3-m2-l2",
          label: "Keeping access honest",
          topics: [
            {
              id: "sec3-m2-t6",
              type: "Video",
              title: "Access reviews and recertification",
              duration: "10 min",
              completed: false,
            },
            {
              id: "sec3-m2-t7",
              type: "Reading",
              title: "Service accounts, API keys and secrets",
              duration: "approx. 13 min read",
              completed: false,
            },
            {
              id: "sec3-m2-t8",
              type: "Activity",
              title: "Find the excess permissions in an access matrix",
              duration: "approx. 20 min",
              completed: false,
            },
            {
              id: "sec3-m2-t9",
              type: "Graded Assignment",
              title: "Assignment 01 · Access model for a 30-person company",
              duration: "approx. 60 min",
              completed: false,
            },
            {
              id: "sec3-m2-t10",
              type: "Quiz",
              title: "Graded Quiz: Access control",
              duration: "approx. 12 min",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sec3-m3",
      label: "MODULE 03",
      title: "Cloud Security Fundamentals",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "sec3-m3-l1",
          label: "Who secures what",
          topics: [
            {
              id: "sec3-m3-t1",
              type: "Video",
              title: "Cloud service models: IaaS, PaaS and SaaS",
              duration: "12 min",
              completed: false,
            },
            {
              id: "sec3-m3-t2",
              type: "Reading",
              title: "The shared responsibility model",
              duration: "approx. 13 min read",
              completed: false,
            },
            {
              id: "sec3-m3-t3",
              type: "Video",
              title: "Cloud identity: roles, policies and conditions",
              duration: "13 min",
              completed: false,
            },
            {
              id: "sec3-m3-t4",
              type: "Reading",
              title: "Common cloud misconfigurations and their fixes",
              duration: "approx. 14 min read",
              completed: false,
            },
            {
              id: "sec3-m3-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Cloud fundamentals",
              duration: "approx. 8 min",
              completed: false,
            },
          ],
        },
        {
          id: "sec3-m3-l2",
          label: "Guardrails",
          topics: [
            { id: "sec3-m3-t6", type: "Video", title: "Network controls in the cloud", duration: "11 min", completed: false },
            {
              id: "sec3-m3-t7",
              type: "Reading",
              title: "Logging and monitoring a cloud account",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec3-m3-t8",
              type: "Activity",
              title: "Assign responsibilities for three cloud services",
              duration: "approx. 15 min",
              completed: false,
            },
            {
              id: "sec3-m3-t9",
              type: "Video",
              title: "Posture management: checking configuration continuously",
              duration: "10 min",
              completed: false,
            },
            {
              id: "sec3-m3-t10",
              type: "Quiz",
              title: "Graded Quiz: Cloud security fundamentals",
              duration: "approx. 12 min",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sec3-m4",
      label: "MODULE 04",
      title: "Protecting Data",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "sec3-m4-l1",
          label: "Encryption and keys",
          topics: [
            {
              id: "sec3-m4-t1",
              type: "Video",
              title: "Data classification: deciding what needs protecting",
              duration: "11 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec3-m4-t2",
              type: "Reading",
              title: "Encryption at rest and in transit",
              duration: "approx. 13 min read",
              completed: false,
              locked: true,
            },
            {
              id: "sec3-m4-t3",
              type: "Video",
              title: "Key management: who holds the keys",
              duration: "12 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec3-m4-t4",
              type: "Reading",
              title: "Backups, retention and recovery objectives",
              duration: "approx. 13 min read",
              completed: false,
              locked: true,
            },
            {
              id: "sec3-m4-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Protecting data",
              duration: "approx. 8 min",
              completed: false,
              locked: true,
            },
          ],
        },
        {
          id: "sec3-m4-l2",
          label: "Sharing safely",
          topics: [
            {
              id: "sec3-m4-t6",
              type: "Reading",
              title: "Securing SaaS: sharing settings and third-party apps",
              duration: "approx. 12 min read",
              completed: false,
              locked: true,
            },
            {
              id: "sec3-m4-t7",
              type: "Video",
              title: "Data loss prevention in practice",
              duration: "11 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec3-m4-t8",
              type: "Peer-graded",
              title: "Cloud account security review",
              duration: "approx. 45 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec3-m4-t9",
              type: "Quiz",
              title: "Graded Quiz: Protecting data",
              duration: "approx. 15 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec3-m4-t10",
              type: "Video",
              title: "Course wrap-up and what comes next",
              duration: "5 min",
              completed: false,
              locked: true,
            },
          ],
        },
      ],
    },
  ],
};
