import type { Course } from "@/lib/courses/kit";

/**
 * "Security Foundations and the Threat Landscape": course 1 of 5 of the Cybersecurity Fundamentals
 * Certificate, not started. 39 topics in 4 modules, none done: the player opens on
 * the first topic. Module 4 is locked until Module 3 is complete.
 */
export const outline: Course = {
  id: "sec1",
  slug: "security-foundations-and-the-threat-landscape",
  title: "Security Foundations and the Threat Landscape",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Beginner",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 0,
  modulesCompleted: 0,
  modulesTotal: 4,
  modules: [
    {
      id: "sec1-m1",
      label: "MODULE 01",
      title: "Security Principles and Risk",
      topicsCompleted: 0,
      topicsTotal: 9,
      isCompleted: false,
      lessons: [
        {
          id: "sec1-m1-l1",
          label: "What security protects",
          topics: [
            {
              id: "sec1-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "6 min",
              completed: false,
              transcript: [
                {
                  id: "sec1-m1-t1-ln1",
                  ts: "0:00",
                  text: "Welcome to Security Foundations and the Threat Landscape, the first course of the Cybersecurity Fundamentals Certificate.",
                },
                {
                  id: "sec1-m1-t1-ln2",
                  ts: "0:20",
                  text: "Security work starts with a plain question: what do we have that matters, and what could happen to it?",
                },
                {
                  id: "sec1-m1-t1-ln3",
                  ts: "0:40",
                  text: "In Module 1 you learn the vocabulary for that question: confidentiality, integrity and availability, then assets, threats, vulnerabilities and risk.",
                },
                {
                  id: "sec1-m1-t1-ln4",
                  ts: "0:55",
                  text: "Module 2 looks at who attacks organisations and how an intrusion usually unfolds, so that controls are placed where they interrupt it.",
                },
                {
                  id: "sec1-m1-t1-ln5",
                  ts: "1:15",
                  text: "Module 3 is about people: why social engineering works, and the everyday habits that stop most of it.",
                },
                {
                  id: "sec1-m1-t1-ln6",
                  ts: "1:30",
                  text: "Module 4 covers the frameworks, laws and professional ethics that shape the job. Everything in this program is defensive: we study attacks in order to prevent, detect and respond to them.",
                },
                {
                  id: "sec1-m1-t1-ln7",
                  ts: "1:50",
                  text: "You will write a risk register for a small business and an acceptable use policy. Start with the next reading, and keep a list of terms as you go.",
                },
              ],
            },
            {
              id: "sec1-m1-t2",
              type: "Reading",
              title: "Confidentiality, integrity and availability",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec1-m1-t3",
              type: "Video",
              title: "Assets, threats and vulnerabilities",
              duration: "11 min",
              completed: false,
              transcript: [
                {
                  id: "sec1-m1-t3-ln1",
                  ts: "0:00",
                  text: "Three words carry most of a risk conversation: asset, threat and vulnerability. They are often mixed up, so let us separate them.",
                },
                {
                  id: "sec1-m1-t3-ln2",
                  ts: "0:20",
                  text: "An asset is anything of value to the organisation: customer records, the booking system, a laptop, the ability to take payments, its reputation.",
                },
                {
                  id: "sec1-m1-t3-ln3",
                  ts: "0:40",
                  text: "A threat is something that could cause harm to an asset. It can be a person, such as a criminal or a careless employee, or an event, such as a flood or a power cut.",
                },
                {
                  id: "sec1-m1-t3-ln4",
                  ts: "0:55",
                  text: "A vulnerability is a weakness a threat could use: an unpatched server, a shared password, a door that does not lock, a process nobody checks.",
                },
                {
                  id: "sec1-m1-t3-ln5",
                  ts: "1:15",
                  text: "Risk is where the three meet. A threat with no weakness to use, or a weakness on something of no value, is a low risk.",
                },
                {
                  id: "sec1-m1-t3-ln6",
                  ts: "1:30",
                  text: "That is why we start from assets. Listing what matters first keeps the team from spending its effort on weaknesses that protect nothing important.",
                },
                {
                  id: "sec1-m1-t3-ln7",
                  ts: "1:50",
                  text: "In the next reading you will rate risks by likelihood and impact, and record them in a risk register you will reuse in the Module 2 assignment.",
                },
              ],
            },
            {
              id: "sec1-m1-t4",
              type: "Reading",
              title: "Likelihood, impact and the risk register",
              duration: "approx. 14 min read",
              completed: false,
            },
            {
              id: "sec1-m1-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Security principles",
              duration: "approx. 8 min",
              completed: false,
            },
          ],
        },
        {
          id: "sec1-m1-l2",
          label: "From risk to controls",
          topics: [
            {
              id: "sec1-m1-t6",
              type: "Video",
              title: "Preventive, detective and corrective controls",
              duration: "12 min",
              completed: false,
            },
            {
              id: "sec1-m1-t7",
              type: "Reading",
              title: "Defence in depth and least privilege",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec1-m1-t8",
              type: "Activity",
              title: "Classify ten controls by type",
              duration: "approx. 15 min",
              completed: false,
            },
            {
              id: "sec1-m1-t9",
              type: "Quiz",
              title: "Graded Quiz: Principles and risk",
              duration: "approx. 12 min",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sec1-m2",
      label: "MODULE 02",
      title: "The Threat Landscape",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "sec1-m2-l1",
          label: "Who attacks and why",
          topics: [
            { id: "sec1-m2-t1", type: "Video", title: "Threat actors and their motives", duration: "12 min", completed: false },
            {
              id: "sec1-m2-t2",
              type: "Reading",
              title: "How an intrusion unfolds, stage by stage",
              duration: "approx. 15 min read",
              completed: false,
            },
            {
              id: "sec1-m2-t3",
              type: "Video",
              title: "Malware families: what each one does",
              duration: "13 min",
              completed: false,
            },
            {
              id: "sec1-m2-t4",
              type: "Reading",
              title: "Ransomware: why it works and what limits it",
              duration: "approx. 14 min read",
              completed: false,
            },
            {
              id: "sec1-m2-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Threats and malware",
              duration: "approx. 8 min",
              completed: false,
            },
          ],
        },
        {
          id: "sec1-m2-l2",
          label: "Assessing what could go wrong",
          topics: [
            {
              id: "sec1-m2-t6",
              type: "Video",
              title: "Reading a threat report critically",
              duration: "10 min",
              completed: false,
            },
            {
              id: "sec1-m2-t7",
              type: "Reading",
              title: "Supply chain and third-party risk",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec1-m2-t8",
              type: "Activity",
              title: "Map threats to the assets of Fernhill Bakery",
              duration: "approx. 20 min",
              completed: false,
            },
            {
              id: "sec1-m2-t9",
              type: "Graded Assignment",
              title: "Assignment 01 · Risk register for a small business",
              duration: "approx. 60 min",
              completed: false,
            },
            {
              id: "sec1-m2-t10",
              type: "Quiz",
              title: "Graded Quiz: The threat landscape",
              duration: "approx. 12 min",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sec1-m3",
      label: "MODULE 03",
      title: "The Human Factor",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "sec1-m3-l1",
          label: "Social engineering",
          topics: [
            { id: "sec1-m3-t1", type: "Video", title: "Why social engineering works", duration: "11 min", completed: false },
            {
              id: "sec1-m3-t2",
              type: "Reading",
              title: "Recognising phishing: seven signals",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec1-m3-t3",
              type: "Video",
              title: "Pretexting, vishing and business email compromise",
              duration: "13 min",
              completed: false,
            },
            {
              id: "sec1-m3-t4",
              type: "Activity",
              title: "Sort twelve messages: legitimate or suspicious",
              duration: "approx. 15 min",
              completed: false,
            },
            {
              id: "sec1-m3-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Social engineering",
              duration: "approx. 8 min",
              completed: false,
            },
          ],
        },
        {
          id: "sec1-m3-l2",
          label: "Everyday hygiene",
          topics: [
            {
              id: "sec1-m3-t6",
              type: "Video",
              title: "Passwords, passphrases and password managers",
              duration: "12 min",
              completed: false,
            },
            {
              id: "sec1-m3-t7",
              type: "Reading",
              title: "Multi-factor authentication: methods compared",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec1-m3-t8",
              type: "Reading",
              title: "Patching, backups and device hygiene",
              duration: "approx. 13 min read",
              completed: false,
            },
            { id: "sec1-m3-t9", type: "Video", title: "Building a reporting culture", duration: "9 min", completed: false },
            {
              id: "sec1-m3-t10",
              type: "Quiz",
              title: "Graded Quiz: The human factor",
              duration: "approx. 12 min",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sec1-m4",
      label: "MODULE 04",
      title: "Frameworks, Law and Ethics",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "sec1-m4-l1",
          label: "Frameworks and obligations",
          topics: [
            {
              id: "sec1-m4-t1",
              type: "Video",
              title: "What a security framework is for",
              duration: "10 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec1-m4-t2",
              type: "Reading",
              title: "The NIST Cybersecurity Framework at a glance",
              duration: "approx. 14 min read",
              completed: false,
              locked: true,
            },
            {
              id: "sec1-m4-t3",
              type: "Reading",
              title: "ISO/IEC 27001 and the management system idea",
              duration: "approx. 12 min read",
              completed: false,
              locked: true,
            },
            {
              id: "sec1-m4-t4",
              type: "Video",
              title: "Privacy law basics: personal data and breach notice",
              duration: "12 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec1-m4-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Frameworks and law",
              duration: "approx. 8 min",
              completed: false,
              locked: true,
            },
          ],
        },
        {
          id: "sec1-m4-l2",
          label: "Working ethically",
          topics: [
            {
              id: "sec1-m4-t6",
              type: "Reading",
              title: "Authorisation, scope and professional ethics",
              duration: "approx. 10 min read",
              completed: false,
              locked: true,
            },
            {
              id: "sec1-m4-t7",
              type: "Video",
              title: "Writing a security policy people will read",
              duration: "11 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec1-m4-t8",
              type: "Peer-graded",
              title: "Acceptable use policy draft",
              duration: "approx. 45 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec1-m4-t9",
              type: "Quiz",
              title: "Graded Quiz: Frameworks, law and ethics",
              duration: "approx. 15 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec1-m4-t10",
              type: "Video",
              title: "Course wrap-up and what comes next",
              duration: "5 min",
              completed: false,
              locked: true,
            },
          ],
        },
      ],
    },
  ],
};
