import type { CourseContent, OraContent } from "@/lib/courses/kit";
import { activities } from "./activities";

/**
 * The final submission, as the Project topic and the Peer Review topic after it both show
 * it. The four criteria are the rubric the three milestones are graded with.
 */
const FINAL_SUBMISSION: OraContent = {
  brief:
    "Submit your AI-first marketing system for one business: the three milestones, revised after the comments you received and joined into one document. A reader who knows nothing about the business should be able to see what you would do, in which order, how you would know it worked, and which parts an AI tool does.",
  deliverable:
    "Submit one PDF of 8 to 12 pages using the marketing system template: strategy and channel plan, one finished asset per channel, the customer lifecycle, the measurement plan and the AI workflow log. Add half a page on what you changed after each milestone review. Leave out real customer data and anything confidential.",
  dueLabel: "Due 28 Apr 2027",
  requiredReviews: 2,
  acceptedTypes: [".pdf"],
  overallCommentPrompt: "If this business could act on only one part of your peer's system this month, which should it be, and why?",
  criteria: [
    {
      id: "c1",
      label: "Task 1 · Strategy and channel plan",
      maxPoints: 6,
      options: [
        { points: 6, label: "One objective, a specific audience, and a reason for every channel chosen and every channel left out" },
        { points: 4, label: "Objective and audience are clear; channels are listed without reasons" },
        { points: 2, label: "A list of tactics with no objective behind it" },
        { points: 0, label: "Not attempted" },
      ],
    },
    {
      id: "c2",
      label: "Task 2 · Content, campaign and lifecycle assets",
      maxPoints: 5,
      options: [
        { points: 5, label: "One finished asset per channel, on voice, each traceable to the objective" },
        { points: 3, label: "Assets are complete but could belong to any brand" },
        { points: 0, label: "Not attempted" },
      ],
    },
    {
      id: "c3",
      label: "Task 3 · Measurement plan",
      maxPoints: 5,
      options: [
        { points: 5, label: "One metric per objective, where it is read, and the result that would change the plan" },
        { points: 3, label: "Metrics are listed without targets or decisions" },
        { points: 0, label: "Not attempted" },
      ],
    },
    {
      id: "c4",
      label: "Task 4 · AI workflow log and responsible use",
      maxPoints: 4,
      options: [
        { points: 4, label: "Every AI-assisted step is logged with the tool, the prompt, the check made and who made it" },
        { points: 2, label: "AI use is mentioned but the checks are not recorded" },
        { points: 0, label: "Not attempted" },
      ],
    },
  ],
};

export const content: CourseContent = {
  byline: {
    author: "Rajesh Menon",
    role: "Lead instructor · AI Augmented Digital Marketing",
    updated: "September 2026",
  },
  quiz: [
    {
      question: "What does “AI-first” mean in the capstone brief?",
      platformPrompt: "Choose the correct option",
      explanation:
        "AI-first means the system is designed around what AI tools can do well, with a named person checking each result. It does not mean that every task is handed to a tool.",
      options: [
        { id: "a", label: "Every asset is generated by AI with no editing", feedback: "The brief asks for the opposite: each AI-assisted step has a check and an owner." },
        {
          id: "b",
          label: "The system says where AI does the work, where a person checks it, and what is never handed over",
          correct: true,
          feedback: "Correct. The design of the hand-offs is what is assessed.",
        },
        { id: "c", label: "The project is graded by an AI tool", feedback: "Milestones are graded by the course team and the final submission by two peers." },
        { id: "d", label: "No human-written content is allowed", feedback: "Write whatever is better written by you, and say so in the log." },
      ],
    },
    {
      question: "What is the final submission made of?",
      platformPrompt: "Choose the correct option",
      explanation:
        "The final submission is the three milestones, revised after the comments you received and joined into one document, plus a short note on what you changed.",
      options: [
        { id: "a", label: "A new project, separate from the milestones", feedback: "The milestones are the project. The final submission is their revised whole." },
        {
          id: "b",
          label: "The three milestones, revised and joined, with a note on what changed",
          correct: true,
          feedback: "Correct. Revision after feedback is part of what is graded.",
        },
        { id: "c", label: "Only Milestone 3", feedback: "All three belong in it." },
        { id: "d", label: "A slide deck with no supporting detail", feedback: "The template is a document of 8 to 12 pages." },
      ],
    },
    {
      question: "Which entry belongs in the AI workflow log?",
      explanation:
        "The log records each AI-assisted step so that someone else could repeat it and trust it: the tool, the prompt or its summary, what was checked, and who checked it.",
      options: [
        { id: "a", label: "“Used AI for the emails.”", feedback: "Too vague to repeat or to trust. Which tool, which prompt, what was checked?" },
        {
          id: "b",
          label: "“Welcome email 1: drafted from brief B2 with a writing assistant; claims checked against the product sheet by me; subject line rewritten.”",
          correct: true,
          feedback: "Correct. Step, tool, source, check and change are all there.",
        },
        { id: "c", label: "A list of every AI tool you have heard of", feedback: "The log is about what you did, not what exists." },
        { id: "d", label: "Nothing: AI use does not need recording", feedback: "The log is one of the four graded parts of the project." },
      ],
    },
  ],
  articles: {
    "cps-m1-t2": {
      lede: "This is the brief for the whole capstone. Read it before you choose a business, and come back to it before each milestone. It says what you hand in, how the work is divided, and what a strong project looks like.",
      sections: [
        {
          heading: "What you are building",
          paragraphs: [
            "You will design an AI-first marketing system for one business. A system is more than a campaign. A campaign has a start and an end; a system is what the business would keep running: who it is trying to reach and why, which channels carry the message, what is published, how a new contact becomes a repeat customer, and how anyone would know whether it is working.",
            "AI-first means you design the system around what AI tools do well, such as drafting, summarising, sorting and suggesting, and that you say who checks each result. For every part, the project should answer three questions: what does a tool do here, what does a person check, and what is never handed over?",
            "Choose a business you can describe from the inside: your own, your employer's with their agreement, or one of the three scenarios in Handouts. A small, specific business makes a better project than a famous one you know only from outside.",
          ],
        },
        {
          heading: "Three milestones and a final submission",
          paragraphs: [
            "Milestone 1 is the strategy and the channel plan: the business, its audience, one objective for the next quarter, and the channels you chose with the reason for each. Say which channels you left out, too. It draws on courses 1, 3 and 4.",
            "Milestone 2 is the content and campaign assets: one finished asset for each channel in your plan, with the brief and the prompt behind it. A social post, a search-led article outline, an ad, a welcome email. It draws on courses 2, 5 and 6.",
            "Milestone 3 is the measurement plan and the AI workflow log: one metric per objective, where you would read it and what result would make you change the plan; then a log of every AI-assisted step in the project. The final submission is all three, revised after the comments you received and joined into one document of 8 to 12 pages.",
          ],
        },
        {
          heading: "How it is graded",
          paragraphs: [
            "Each milestone is graded by the course team with the same four-part rubric: strategy, assets, measurement, and AI workflow and responsible use. Together the milestones are 45% of the grade. The final submission is another 45%, graded by two peers with that rubric. The remaining 10% is for the two reviews you give.",
            "The rubric rewards decisions over volume. A plan with three channels and a reason for each scores higher than one with eight channels and no reasons. An asset that could only belong to this brand scores higher than five that could belong to any. A log that records what you checked scores higher than a list of tools.",
            "It also rewards revision. The note on what you changed after each milestone review is short, and it is read first.",
          ],
        },
      ],
      pullQuote: {
        text: "A campaign has a start and an end. A system is what the business would keep running.",
        attribution: "Capstone brief",
      },
      takeaways: [
        "One business, one objective, and a system that would keep running after the launch.",
        "Three milestones: strategy and channels, assets, then measurement and the AI workflow log.",
        "For each part, say what a tool does, what a person checks and what is never handed over.",
        "The final submission is the milestones revised and joined; the note on what changed is read first.",
      ],
    },
    "cps-m2-t1": {
      lede: "Every milestone, and the final submission, is graded with the same rubric. It has four parts and it is short. This reading goes through each part with an example of work that earns full marks and one that does not, so that you can check your own before you submit.",
      sections: [
        {
          heading: "Strategy and channel plan",
          paragraphs: [
            "Full marks go to a plan with one objective, a specific audience, and a reason for every channel chosen and every channel left out. The objective is a sentence with a person and an action: “Parents of children aged four to eight who live within five kilometres book a trial swimming lesson: 60 bookings by the end of June.”",
            "A weaker version reads: “Increase awareness and grow our social following.” It names no person and no action, and nobody could say in June whether it had been met. A list of channels with no reasons scores in the middle. A list of tactics with no objective behind it scores near the bottom.",
            "Reasons can be brief. “Search ads: parents look for lessons by town name, and intent is high.” “No short-video platform this quarter: nobody on the team can film weekly.” The second line earns as much credit as the first.",
          ],
        },
        {
          heading: "Content, campaign and lifecycle assets",
          paragraphs: [
            "The rubric asks for one finished asset per channel, on voice, each traceable to the objective. Finished means it could be published as it stands: a real headline, real copy, a real call to action. An outline labelled “post about lessons” is not an asset.",
            "The test a grader applies is whether the asset could belong to another brand. “Summer is here! Book now and make a splash” could be any swimming school anywhere. “Mia put her face in the water in week two. Trial lessons at the Elm Street pool, Saturdays at nine” could only be this one.",
          ],
        },
        {
          heading: "Measurement plan",
          paragraphs: [
            "Full marks need three things for each objective: one metric, where it is read, and the result that would change the plan. “Trial bookings per week, read from the booking system every Monday. Under ten a week by mid-May: move budget from social to search.”",
            "A table of fifteen metrics with no targets and no decisions scores in the middle, however complete it looks. The grader is looking for evidence that a number would lead to an action.",
          ],
        },
        {
          heading: "AI workflow log and responsible use",
          paragraphs: [
            "Each AI-assisted step is one row: the step, the tool, the prompt or a summary of it, what was checked, and who checked it. “Search ad headlines: drafted with a writing assistant from brief B1; character counts and the price checked against the booking page by me; two headlines removed for unsupported claims.”",
            "“Used AI to help with the ads” records nothing a reader could repeat or trust, and scores accordingly. The log is also where you show judgement: the three things you would never hand over in this business, and why.",
            "Across all four parts the pattern is the same. The rubric rewards a decision you can explain over a quantity of material.",
          ],
        },
      ],
      pullQuote: {
        text: "A grader asks one question of every page: what did this person decide, and can I see why?",
        attribution: "Capstone rubric notes",
      },
      takeaways: [
        "The same four-part rubric is used for each milestone and for the final submission.",
        "Strategy: one objective with a person and an action, and a reason for each channel in or out.",
        "Assets: finished, on voice, and impossible to mistake for another brand's.",
        "Measurement and log: every metric leads to a decision, and every AI step records its check.",
      ],
    },
  },
  quizzes: {
    "cps-m3-t3": [
      {
        question: "Your channel plan lists eight channels with a paragraph on each. A reviewer asks why you left none out. What does the rubric reward?",
        platformPrompt: "Choose the correct option",
        hints: [
          "Look at how the top score for strategy is worded.",
          "The rubric asks for a reason for each channel chosen, and for each one left out.",
        ],
        explanation:
          "The rubric rewards decisions: a reason for each channel chosen and for each one left out. A plan that includes everything has decided nothing, and a small business could not run it.",
        reviewTopicId: "cps-m2-t1",
        reviewTopicTitle: "How the milestones are graded: the rubric, with examples",
        options: [
          { id: "a", label: "Covering as many channels as possible", feedback: "Volume is not a criterion. Choice is." },
          {
            id: "b",
            label: "Fewer channels, each with a reason, and a note on what was left out and why",
            correct: true,
            feedback: "Correct. Leaving a channel out, with a reason, is a decision the rubric scores.",
          },
          { id: "c", label: "Longer paragraphs on each of the eight", feedback: "Length does not turn a list into a plan." },
          { id: "d", label: "Removing the channel plan altogether", feedback: "It is one of the four graded parts." },
        ],
      },
      {
        question: "Before submitting, you find a customer's name and order history in one of your example emails. What do you do?",
        platformPrompt: "Choose the correct option",
        explanation:
          "Two peers will read the submission. Real customer data does not belong in it. Replace it with sample data and say that you did.",
        reviewTopicId: "cps-m1-t2",
        reviewTopicTitle: "Capstone brief: an AI-first marketing system for one business",
        options: [
          { id: "a", label: "Leave it: real data makes the project more convincing", feedback: "It also shares personal data with people who have no right to see it." },
          {
            id: "b",
            label: "Replace it with sample data and note that the figures are examples",
            correct: true,
            feedback: "Correct. The project stays convincing and nobody's data is shared.",
          },
          { id: "c", label: "Blur the name but keep the order history", feedback: "An order history can identify a person on its own." },
          { id: "d", label: "Delete the whole email from the project", feedback: "The email is a required asset. Change the data, keep the email." },
        ],
      },
      {
        question: "Which measurement plan is ready to submit?",
        explanation:
          "A measurement plan links each objective to one metric, says where the number is read, and names the result that would change the plan. A list of metrics with no decision attached is a report, not a plan.",
        reviewTopicId: "cps-m3-t1",
        reviewTopicTitle: "Writing a measurement plan and an AI workflow log",
        options: [
          { id: "a", label: "A list of twenty metrics the tools can report", feedback: "Nothing says which matter, or what you would do about them." },
          { id: "b", label: "“We will track performance and optimise.”", feedback: "No metric, no source, no decision." },
          {
            id: "c",
            label: "One metric per objective, where it is read, and the result that would make you change the plan",
            correct: true,
            feedback: "Correct. Each number is tied to a decision.",
          },
          { id: "d", label: "Screenshots of dashboards with no comment", feedback: "A reader cannot tell what you would conclude from them." },
        ],
      },
    ],
  },
  assignments: {
    "cps-m2-t2": {
      brief:
        "Describe the business you chose and write its strategy and channel plan. State one objective for the next quarter as a sentence with a person and an action. Describe the audience by need or situation. Then choose the channels that will carry the plan, give the reason for each, and name the channels you decided to leave out. Mark each step where an AI tool would do the work and who would check it. Submit your work as a PDF or DOCX using the marketing system template.",
      requirements: [
        "2 to 3 pages: the business, the audience, one objective for the quarter",
        "A channel plan with a reason for each channel chosen and each one left out",
        "For each channel, the step an AI tool does and the person who checks it",
        "Graded with the capstone rubric · 15% of your final grade",
      ],
    },
    "cps-m2-t3": {
      brief:
        "Produce one finished asset for each channel of your Milestone 1 plan: for example a social post, an article outline written for search, an ad, and the first email of a welcome series. For each asset, include the content brief and the prompt you gave an AI assistant, and mark what you changed in its draft. Every claim in an asset must be one the business could support. Submit your work as a PDF or DOCX.",
      requirements: [
        "One finished asset per channel of your plan, each on the brand's voice",
        "The brief and the prompt behind each asset, and what you changed in the draft",
        "A line on how each asset serves the objective of Milestone 1",
        "Graded with the capstone rubric · 15% of your final grade",
      ],
    },
    "cps-m3-t2": {
      brief:
        "Write the measurement plan for your system: one metric for the objective and one for each channel, where each number is read, and the result that would make you change the plan. Then complete the AI workflow log for the whole project: each AI-assisted step, the tool, the prompt or a summary of it, what was checked and by whom. Submit the plan and the log together as one PDF or DOCX.",
      requirements: [
        "A one-page measurement plan: metric, source and decision for the objective and for each channel",
        "The AI workflow log, with a row for every AI-assisted step in Milestones 1 and 2",
        "Three things you would never hand over to an AI tool in this business, and why",
        "Graded with the capstone rubric · 15% of your final grade",
      ],
    },
  },
  ora: {
    "cps-m4-t1": FINAL_SUBMISSION,
    "cps-m4-t2": FINAL_SUBMISSION,
  },
  activities,
};
