import type { Course } from "@/lib/courses/kit";

/**
 * "UX Research and Design Thinking": a stand-alone course on My Learning, just started.
 * 40 topics, 2 done; the learner is on the third topic of Module 1.
 */
export const outline: Course = {
  id: "uxr",
  slug: "ux-research-and-design-thinking",
  title: "UX Research and Design Thinking",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Beginner",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 5,
  modulesCompleted: 0,
  modulesTotal: 4,
  modules: [
    {
      id: "uxr-m1",
      label: "MODULE 01",
      title: "Empathize: Understanding Users",
      topicsCompleted: 2,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "uxr-m1-l1",
          label: "Talking to users",
          topics: [
            {
              id: "uxr-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "6 min",
              completed: true,
              transcript: [
                { id: "uxr-m1-t1-ln1", ts: "0:00", text: "Welcome to UX Research and Design Thinking. This course teaches one habit: find out what people do and need before you decide what to build." },
                { id: "uxr-m1-t1-ln2", ts: "0:15", text: "Design thinking is usually drawn as five stages: empathize, define, ideate, prototype and test. The course follows them in four modules." },
                { id: "uxr-m1-t1-ln3", ts: "0:31", text: "Module 1 is about understanding users. You plan interviews, observe people at work and turn your notes into a persona that rests on evidence." },
                { id: "uxr-m1-t1-ln4", ts: "0:48", text: "Module 2 turns research into a problem worth solving: affinity maps, journey maps, problem statements and How Might We questions." },
                { id: "uxr-m1-t1-ln5", ts: "1:05", text: "Module 3 is where ideas appear. You generate many, choose a few and build prototypes cheap enough to throw away." },
                { id: "uxr-m1-t1-ln6", ts: "1:21", text: "Module 4 covers usability testing and the final project, a redesign backed by your own research and reviewed by two peers." },
                { id: "uxr-m1-t1-ln7", ts: "1:38", text: "One case study runs through the course: five interviews with people who organise meals out for a group. You can use it, or your own interviews." },
                { id: "uxr-m1-t1-ln8", ts: "1:55", text: "You do not need design software. A notebook, sticky notes and someone willing to talk to you are enough to begin." },
              ],
            },
            { id: "uxr-m1-t2", type: "Reading", title: "What UX research is, and what it is not", duration: "approx. 12 min read", completed: true },
            {
              id: "uxr-m1-t3",
              type: "Video",
              title: "Discovery interview techniques",
              duration: "14 min",
              completed: false,
              active: true,
              transcript: [
                { id: "uxr-m1-t3-ln1", ts: "0:00", text: "A discovery interview is a conversation about what someone already does, not a pitch for what you plan to build." },
                { id: "uxr-m1-t3-ln2", ts: "0:17", text: "Start with a warm-up. Ask about their role and a normal day, so the person is talking about familiar ground before you get specific." },
                { id: "uxr-m1-t3-ln3", ts: "0:36", text: "Then ask for a story: “Tell me about the last time you did this.” A specific occasion gives you steps, tools and feelings. A general question gives you opinions." },
                { id: "uxr-m1-t3-ln4", ts: "0:58", text: "Avoid leading questions. “Would you like a faster way to do this?” already holds the answer. Ask how it went, and what they did next." },
                { id: "uxr-m1-t3-ln5", ts: "1:18", text: "Follow up with “why?”, or with “tell me more about that”. When the person goes quiet, wait. People often fill a silence with the detail you needed." },
                { id: "uxr-m1-t3-ln6", ts: "1:39", text: "Do not ask people to design the solution or to predict what they would use. Past behaviour is evidence; a prediction is a guess." },
                { id: "uxr-m1-t3-ln7", ts: "1:58", text: "Close by asking what you should have asked. Then write up your notes the same day, while you still remember the tone as well as the words." },
              ],
            },
            { id: "uxr-m1-t4", type: "Reading", title: "Writing an interview guide", duration: "approx. 15 min read", completed: false },
            { id: "uxr-m1-t5", type: "Practice Assignment", title: "Practice Quiz: Interview questions", duration: "approx. 8 min", completed: false },
          ],
        },
        {
          id: "uxr-m1-l2",
          label: "From conversations to evidence",
          topics: [
            {
              id: "uxr-m1-t6",
              type: "Video",
              title: "Observing users in context",
              duration: "12 min",
              completed: false,
              transcript: [
                { id: "uxr-m1-t6-ln1", ts: "0:00", text: "In an interview people tell you what they remember doing. When you watch them, you see what they do. The two are often different." },
                { id: "uxr-m1-t6-ln2", ts: "0:15", text: "Observation in context means going where the work happens: the desk, the shop floor, the kitchen, the phone in a queue." },
                { id: "uxr-m1-t6-ln3", ts: "0:31", text: "Ask the person to carry out a real task, one they needed to do anyway. Say that you are there to learn from them, and that nothing they do is wrong." },
                { id: "uxr-m1-t6-ln4", ts: "0:49", text: "Then stay quiet and take notes. Write what they do, what they use and where they stop. Keep your interpretation in a separate column." },
                { id: "uxr-m1-t6-ln5", ts: "1:07", text: "Look for workarounds: the sticky note on the monitor, the spreadsheet beside the official system, the screenshot sent to a colleague. Each one marks a need the product does not meet." },
                { id: "uxr-m1-t6-ln6", ts: "1:27", text: "Notice the surroundings too. Noise, interruptions, a weak signal or a shared computer shape how a product is used, and no interview question brings them out." },
                { id: "uxr-m1-t6-ln7", ts: "1:45", text: "Ask your questions at the end, and point at what you saw: “I noticed you copied that number by hand. Tell me about that.”" },
                { id: "uxr-m1-t6-ln8", ts: "2:02", text: "Ask before you take photos, and leave out names and screens with personal data. In the activity that follows you sort notes like these into themes." },
              ],
            },
            { id: "uxr-m1-t7", type: "Activity", title: "Sort interview notes into themes", duration: "approx. 20 min", completed: false },
            { id: "uxr-m1-t8", type: "Reading", title: "Personas that come from evidence", duration: "approx. 13 min read", completed: false },
            { id: "uxr-m1-t9", type: "Quiz", title: "Graded Quiz: Research foundations", duration: "approx. 10 min", completed: false },
            { id: "uxr-m1-t10", type: "Peer-graded", title: "Persona research draft", duration: "approx. 45 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "uxr-m2",
      label: "MODULE 02",
      title: "Define: From Research to Problem Statements",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "uxr-m2-l1",
          label: "Synthesis",
          topics: [
            {
              id: "uxr-m2-t1",
              type: "Video",
              title: "From findings to insights",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "uxr-m2-t1-ln1", ts: "0:00", text: "After a round of research you have pages of notes. Those are findings: things you saw or heard. An insight is what a finding means for the design." },
                { id: "uxr-m2-t1-ln2", ts: "0:16", text: "A finding sounds like this: four of five organisers collected replies in a group chat and then counted them by hand." },
                { id: "uxr-m2-t1-ln3", ts: "0:31", text: "The insight asks why it matters. Organisers do not trust any tool to hold the final headcount, so they keep it in their heads until the last minute." },
                { id: "uxr-m2-t1-ln4", ts: "0:49", text: "A useful insight has three parts: what people do, why they do it, and the consequence for them. Leave one out and the team cannot act on it." },
                { id: "uxr-m2-t1-ln5", ts: "1:06", text: "Check that the insight rests on a pattern. One vivid story from one participant is a lead to follow up. It is not yet an insight." },
                { id: "uxr-m2-t1-ln6", ts: "1:22", text: "Keep the solution out of it. “Users need a headcount widget” is a feature request. “Organisers cannot see who is still undecided” leaves room for several answers." },
                { id: "uxr-m2-t1-ln7", ts: "1:41", text: "Write each insight as one sentence and keep the evidence next to it: the participants and the quotes. Someone will ask how you know." },
                { id: "uxr-m2-t1-ln8", ts: "1:57", text: "The next reading shows the method that gets you from a wall of notes to a short list of insights: the affinity map." },
              ],
            },
            { id: "uxr-m2-t2", type: "Reading", title: "Affinity mapping step by step", duration: "approx. 15 min read", completed: false },
            { id: "uxr-m2-t3", type: "Video", title: "Building a persona from research data", duration: "16 min", completed: false },
            { id: "uxr-m2-t4", type: "Reading", title: "Journey maps: stages, actions and pain points", duration: "approx. 15 min read", completed: false },
            { id: "uxr-m2-t5", type: "Activity", title: "Map one journey from the case study", duration: "approx. 25 min", completed: false },
          ],
        },
        {
          id: "uxr-m2-l2",
          label: "Framing the problem",
          topics: [
            {
              id: "uxr-m2-t6",
              type: "Video",
              title: "Writing a problem statement",
              duration: "12 min",
              completed: false,
              transcript: [
                { id: "uxr-m2-t6-ln1", ts: "0:00", text: "A problem statement is one sentence the whole team can point at when it has to decide what is in and what is out." },
                { id: "uxr-m2-t6-ln2", ts: "0:14", text: "The usual form has three parts: a user, a need and the reason behind the need. The reason is the insight from your research." },
                { id: "uxr-m2-t6-ln3", ts: "0:30", text: "For example: a person organising a meal for a group needs to know who is coming before the booking deadline, because the restaurant holds a large table only until then." },
                { id: "uxr-m2-t6-ln4", ts: "0:50", text: "Test the user first. “Everyone who eats out” is too broad to design for. Name the person your research met, in the situation where the problem occurs." },
                { id: "uxr-m2-t6-ln5", ts: "1:07", text: "Test the need next. It should be a verb, something the person is trying to get done. If it names a screen or a feature, you have written a solution." },
                { id: "uxr-m2-t6-ln6", ts: "1:24", text: "Then test the scope. Too narrow, and only one answer fits. Too broad, such as “make group dining better”, and the team cannot tell whether an idea belongs." },
                { id: "uxr-m2-t6-ln7", ts: "1:43", text: "Write three versions and read them to someone outside the project. Keep the one they can repeat back to you an hour later." },
                { id: "uxr-m2-t6-ln8", ts: "1:58", text: "In the next reading you turn the statement into How Might We questions, the starting point for generating ideas." },
              ],
            },
            { id: "uxr-m2-t7", type: "Reading", title: "How Might We questions", duration: "approx. 10 min read", completed: false },
            { id: "uxr-m2-t8", type: "Practice Assignment", title: "Practice Quiz: Define", duration: "approx. 8 min", completed: false },
            { id: "uxr-m2-t9", type: "Video", title: "Prioritising problems with your team", duration: "20 min", completed: false },
            { id: "uxr-m2-t10", type: "Quiz", title: "Graded Quiz: Synthesis and problem framing", duration: "approx. 15 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "uxr-m3",
      label: "MODULE 03",
      title: "Ideate and Prototype",
      topicsCompleted: 0,
      topicsTotal: 11,
      isCompleted: false,
      lessons: [
        {
          id: "uxr-m3-l1",
          label: "Generating ideas",
          topics: [
            {
              id: "uxr-m3-t1",
              type: "Video",
              title: "Divergent and convergent thinking",
              duration: "12 min",
              completed: false,
              transcript: [
                { id: "uxr-m3-t1-ln1", ts: "0:00", text: "Idea work has two modes. In divergent thinking you produce options. In convergent thinking you choose among them. Trouble starts when a team does both at once." },
                { id: "uxr-m3-t1-ln2", ts: "0:18", text: "You know the scene. Someone suggests an idea, someone else explains why it will not work, and after an hour the group has discussed three ideas and kept none." },
                { id: "uxr-m3-t1-ln3", ts: "0:35", text: "So separate the modes in time. Diverge first, with one rule: no judging. Aim for a number, such as thirty ideas in fifteen minutes. Quantity is the goal at this point." },
                { id: "uxr-m3-t1-ln4", ts: "0:54", text: "Work alone before you work together. People who sketch in silence for five minutes bring more varied ideas than a group that starts by talking." },
                { id: "uxr-m3-t1-ln5", ts: "1:10", text: "Then converge, and say out loud that the mode has changed. Group similar ideas, name the groups and compare them against the problem statement." },
                { id: "uxr-m3-t1-ln6", ts: "1:27", text: "Choose with criteria agreed before anyone votes: which idea serves the need, and which one can be tested this week. The loudest voice is not a criterion." },
                { id: "uxr-m3-t1-ln7", ts: "1:44", text: "You will repeat the pair many times: wide then narrow for the problem, and again for the solution. The next reading gives you three methods for the wide part." },
              ],
            },
            { id: "uxr-m3-t2", type: "Reading", title: "Ideation methods: Crazy 8s, brainwriting and SCAMPER", duration: "approx. 15 min read", completed: false },
            { id: "uxr-m3-t3", type: "Activity", title: "Run a Crazy 8s round", duration: "approx. 20 min", completed: false },
            { id: "uxr-m3-t4", type: "Video", title: "Choosing ideas: impact and effort", duration: "10 min", completed: false },
            { id: "uxr-m3-t5", type: "Reading", title: "Storyboards and user flows", duration: "approx. 12 min read", completed: false },
          ],
        },
        {
          id: "uxr-m3-l2",
          label: "Prototyping",
          topics: [
            {
              id: "uxr-m3-t6",
              type: "Video",
              title: "Low-fidelity prototyping on paper",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "uxr-m3-t6-ln1", ts: "0:00", text: "A paper prototype is a set of sketched screens that a person can pretend to use. It takes an hour to make, which is exactly why it is useful." },
                { id: "uxr-m3-t6-ln2", ts: "0:16", text: "Because it is cheap, you will change it without regret. Because it looks unfinished, people tell you what is wrong with it instead of being polite." },
                { id: "uxr-m3-t6-ln3", ts: "0:32", text: "You need paper, a thick pen and scissors. Draw one screen per sheet, at about the size of the device. Draw boxes and labels, and skip the decoration." },
                { id: "uxr-m3-t6-ln4", ts: "0:49", text: "Draw the parts that change on separate slips: a menu, an error message, a confirmation. You will lay them on top when the person taps." },
                { id: "uxr-m3-t6-ln5", ts: "1:05", text: "Sketch only the path you want to learn about. If the question is whether people can invite guests, you need the invitation screens and nothing else." },
                { id: "uxr-m3-t6-ln6", ts: "1:21", text: "In a test, one person plays the computer. They swap the sheets when the participant touches something, and they say nothing. A second person takes notes." },
                { id: "uxr-m3-t6-ln7", ts: "1:39", text: "When a participant gets stuck, redraw the screen on the spot and try again with the next person. Five rounds in an afternoon is normal." },
                { id: "uxr-m3-t6-ln8", ts: "1:54", text: "Paper cannot show timing, scrolling or real data. The next video covers clickable prototypes and when they are worth the extra effort." },
              ],
            },
            { id: "uxr-m3-t7", type: "Video", title: "Clickable prototypes: how much fidelity you need", duration: "16 min", completed: false },
            { id: "uxr-m3-t8", type: "Reading", title: "Prototype to learn, not to impress", duration: "approx. 10 min read", completed: false },
            { id: "uxr-m3-t9", type: "Practice Assignment", title: "Practice Quiz: Ideation and prototyping", duration: "approx. 8 min", completed: false },
            { id: "uxr-m3-t10", type: "Peer-graded", title: "Prototype critique", duration: "approx. 35 min", completed: false },
            { id: "uxr-m3-t11", type: "Quiz", title: "Graded Quiz: Ideate and prototype", duration: "approx. 13 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "uxr-m4",
      label: "MODULE 04",
      title: "Test, Iterate, and Final Project",
      topicsCompleted: 0,
      topicsTotal: 9,
      isCompleted: false,
      lessons: [
        {
          id: "uxr-m4-l1",
          label: "Usability testing",
          topics: [
            { id: "uxr-m4-t1", type: "Video", title: "Planning a usability test", duration: "12 min", completed: false, locked: true },
            { id: "uxr-m4-t2", type: "Reading", title: "Writing tasks and a test script", duration: "approx. 10 min read", completed: false, locked: true },
            { id: "uxr-m4-t3", type: "Video", title: "Moderating a session without leading", duration: "12 min", completed: false, locked: true },
            { id: "uxr-m4-t4", type: "Reading", title: "Reading the results: severity and frequency", duration: "approx. 8 min read", completed: false, locked: true },
            { id: "uxr-m4-t5", type: "Activity", title: "Rate five findings by severity", duration: "approx. 10 min", completed: false, locked: true },
          ],
        },
        {
          id: "uxr-m4-l2",
          label: "Final project",
          topics: [
            { id: "uxr-m4-t6", type: "Reading", title: "Final project brief: a research-backed redesign", duration: "approx. 8 min read", completed: false, locked: true },
            { id: "uxr-m4-t7", type: "Project", title: "Final Project: Research-backed redesign", duration: "approx. 50 min", completed: false, locked: true },
            { id: "uxr-m4-t8", type: "Peer Review", title: "Review two final projects", duration: "approx. 15 min", completed: false, locked: true },
            { id: "uxr-m4-t9", type: "Video", title: "Course wrap-up and next steps", duration: "5 min", completed: false, locked: true },
          ],
        },
      ],
    },
  ],
};
