import type { Course } from "@/lib/courses/kit";

/**
 * "Security Operations and Incident Response": course 4 of 5 of the Cybersecurity Fundamentals
 * Certificate, not started. 39 topics in 4 modules, none done: the player opens on
 * the first topic. Module 4 is locked until Module 3 is complete.
 */
export const outline: Course = {
  id: "sec4",
  slug: "security-operations-and-incident-response",
  title: "Security Operations and Incident Response",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Beginner",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 0,
  modulesCompleted: 0,
  modulesTotal: 4,
  modules: [
    {
      id: "sec4-m1",
      label: "MODULE 01",
      title: "Inside Security Operations",
      topicsCompleted: 0,
      topicsTotal: 9,
      isCompleted: false,
      lessons: [
        {
          id: "sec4-m1-l1",
          label: "What a security operations team does",
          topics: [
            {
              id: "sec4-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "6 min",
              completed: false,
              transcript: [
                {
                  id: "sec4-m1-t1-ln1",
                  ts: "0:00",
                  text: "Welcome to Security Operations and Incident Response, the fourth course of the Cybersecurity Fundamentals Certificate.",
                },
                {
                  id: "sec4-m1-t1-ln2",
                  ts: "0:20",
                  text: "The first three courses were about building defences. This one is about the moment a defence is tested: noticing it, deciding what it means, and responding.",
                },
                {
                  id: "sec4-m1-t1-ln3",
                  ts: "0:40",
                  text: "Module 1 shows how a security operations team works and where its evidence comes from: logs from endpoints, identity systems, the network and the cloud.",
                },
                {
                  id: "sec4-m1-t1-ln4",
                  ts: "0:55",
                  text: "Module 2 is detection and triage: how alerts are produced, and how an analyst decides in minutes whether one is real and how much it matters.",
                },
                {
                  id: "sec4-m1-t1-ln5",
                  ts: "1:15",
                  text: "Module 3 follows the incident response lifecycle, from preparation through containment and recovery, with two worked playbooks.",
                },
                {
                  id: "sec4-m1-t1-ln6",
                  ts: "1:30",
                  text: "Module 4 covers evidence, communication and the review that turns an incident into an improvement.",
                },
                {
                  id: "sec4-m1-t1-ln7",
                  ts: "1:50",
                  text: "You will write a triage report on three sample alerts and summarise a tabletop exercise. Everything uses prepared data; you will not need access to a live system.",
                },
              ],
            },
            {
              id: "sec4-m1-t2",
              type: "Reading",
              title: "Roles, tiers and handovers in a SOC",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec4-m1-t3",
              type: "Video",
              title: "Log sources: endpoints, identity, network and cloud",
              duration: "13 min",
              completed: false,
            },
            {
              id: "sec4-m1-t4",
              type: "Reading",
              title: "What makes a log useful: time, identity, action",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec4-m1-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Logs and telemetry",
              duration: "approx. 8 min",
              completed: false,
            },
          ],
        },
        {
          id: "sec4-m1-l2",
          label: "Collecting the evidence",
          topics: [
            {
              id: "sec4-m1-t6",
              type: "Video",
              title: "How a SIEM collects, normalises and correlates",
              duration: "13 min",
              completed: false,
            },
            {
              id: "sec4-m1-t7",
              type: "Reading",
              title: "Time synchronisation and log retention",
              duration: "approx. 10 min read",
              completed: false,
            },
            {
              id: "sec4-m1-t8",
              type: "Activity",
              title: "Match eight events to their log source",
              duration: "approx. 15 min",
              completed: false,
            },
            {
              id: "sec4-m1-t9",
              type: "Quiz",
              title: "Graded Quiz: Security operations",
              duration: "approx. 12 min",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sec4-m2",
      label: "MODULE 02",
      title: "Detection and Triage",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "sec4-m2-l1",
          label: "From event to alert",
          topics: [
            {
              id: "sec4-m2-t1",
              type: "Video",
              title: "Detection rules: signatures, thresholds and behaviour",
              duration: "13 min",
              completed: false,
            },
            {
              id: "sec4-m2-t2",
              type: "Reading",
              title: "Indicators of compromise and indicators of attack",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec4-m2-t3",
              type: "Video",
              title: "Triage: is this alert real, and does it matter?",
              duration: "12 min",
              completed: false,
              transcript: [
                {
                  id: "sec4-m2-t3-ln1",
                  ts: "0:00",
                  text: "Triage is the first decision on an alert. You are answering two questions: is this real, and how much does it matter?",
                },
                {
                  id: "sec4-m2-t3-ln2",
                  ts: "0:20",
                  text: "Start with what fired. Read the rule, not only its name. An alert called “impossible travel” might mean a stolen account, or an employee who switched on a VPN.",
                },
                {
                  id: "sec4-m2-t3-ln3",
                  ts: "0:40",
                  text: "Then add context. Whose account is it, and what can it reach? Which device, and is it managed? Has this happened before for this user?",
                },
                {
                  id: "sec4-m2-t3-ln4",
                  ts: "0:55",
                  text: "Look either side of the event. What happened in the ten minutes before and after: a password reset, a new mail forwarding rule, a large download?",
                },
                {
                  id: "sec4-m2-t3-ln5",
                  ts: "1:15",
                  text: "Now decide. A false positive is closed with a note saying why. A true positive gets a severity, based on what is affected and whether the activity is still going on.",
                },
                {
                  id: "sec4-m2-t3-ln6",
                  ts: "1:30",
                  text: "Escalate early when the account is privileged, when data is leaving, or when you see the same pattern on more than one machine. Waiting to be certain costs more than a careful false alarm.",
                },
                {
                  id: "sec4-m2-t3-ln7",
                  ts: "1:50",
                  text: "Write the note as you go: what you saw, what you checked, what you concluded. The next analyst should not have to repeat your work.",
                },
              ],
            },
            {
              id: "sec4-m2-t4",
              type: "Reading",
              title: "Severity, priority and escalation",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec4-m2-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: Detection and triage",
              duration: "approx. 8 min",
              completed: false,
            },
          ],
        },
        {
          id: "sec4-m2-l2",
          label: "Working an alert",
          topics: [
            {
              id: "sec4-m2-t6",
              type: "Video",
              title: "Mapping detections to attacker techniques",
              duration: "12 min",
              completed: false,
            },
            {
              id: "sec4-m2-t7",
              type: "Reading",
              title: "Writing a clear alert note",
              duration: "approx. 10 min read",
              completed: false,
            },
            {
              id: "sec4-m2-t8",
              type: "Activity",
              title: "Triage ten alerts from a sample queue",
              duration: "approx. 25 min",
              completed: false,
            },
            {
              id: "sec4-m2-t9",
              type: "Graded Assignment",
              title: "Assignment 01 · Triage report for three alerts",
              duration: "approx. 75 min",
              completed: false,
            },
            {
              id: "sec4-m2-t10",
              type: "Quiz",
              title: "Graded Quiz: Detection and triage",
              duration: "approx. 12 min",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sec4-m3",
      label: "MODULE 03",
      title: "The Incident Response Lifecycle",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "sec4-m3-l1",
          label: "Before and during",
          topics: [
            {
              id: "sec4-m3-t1",
              type: "Video",
              title: "Preparation: plans, roles and contact lists",
              duration: "12 min",
              completed: false,
            },
            {
              id: "sec4-m3-t2",
              type: "Reading",
              title: "The incident response lifecycle, phase by phase",
              duration: "approx. 14 min read",
              completed: false,
            },
            {
              id: "sec4-m3-t3",
              type: "Video",
              title: "Containment: stop the spread, keep the evidence",
              duration: "13 min",
              completed: false,
            },
            {
              id: "sec4-m3-t4",
              type: "Reading",
              title: "Eradication and recovery: back to a known good state",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec4-m3-t5",
              type: "Practice Assignment",
              title: "Practice Quiz: The response lifecycle",
              duration: "approx. 8 min",
              completed: false,
            },
          ],
        },
        {
          id: "sec4-m3-l2",
          label: "Playbooks",
          topics: [
            { id: "sec4-m3-t6", type: "Video", title: "Anatomy of a playbook", duration: "10 min", completed: false },
            {
              id: "sec4-m3-t7",
              type: "Reading",
              title: "Playbook: a reported phishing message",
              duration: "approx. 12 min read",
              completed: false,
            },
            {
              id: "sec4-m3-t8",
              type: "Reading",
              title: "Playbook: ransomware on one workstation",
              duration: "approx. 13 min read",
              completed: false,
            },
            {
              id: "sec4-m3-t9",
              type: "Activity",
              title: "Order the steps of a containment plan",
              duration: "approx. 15 min",
              completed: false,
            },
            {
              id: "sec4-m3-t10",
              type: "Quiz",
              title: "Graded Quiz: Incident response",
              duration: "approx. 12 min",
              completed: false,
            },
          ],
        },
      ],
    },
    {
      id: "sec4-m4",
      label: "MODULE 04",
      title: "Evidence, Communication and Learning",
      topicsCompleted: 0,
      topicsTotal: 10,
      isCompleted: false,
      lessons: [
        {
          id: "sec4-m4-l1",
          label: "Handling evidence",
          topics: [
            {
              id: "sec4-m4-t1",
              type: "Video",
              title: "Order of volatility and preserving evidence",
              duration: "12 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec4-m4-t2",
              type: "Reading",
              title: "Chain of custody and incident notes",
              duration: "approx. 12 min read",
              completed: false,
              locked: true,
            },
            {
              id: "sec4-m4-t3",
              type: "Video",
              title: "Building an incident timeline",
              duration: "12 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec4-m4-t4",
              type: "Practice Assignment",
              title: "Practice Quiz: Evidence handling",
              duration: "approx. 8 min",
              completed: false,
              locked: true,
            },
          ],
        },
        {
          id: "sec4-m4-l2",
          label: "Telling people and improving",
          topics: [
            {
              id: "sec4-m4-t5",
              type: "Reading",
              title: "Who to tell, and when: staff, customers, regulators",
              duration: "approx. 13 min read",
              completed: false,
              locked: true,
            },
            {
              id: "sec4-m4-t6",
              type: "Video",
              title: "Running a blameless post-incident review",
              duration: "12 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec4-m4-t7",
              type: "Reading",
              title: "Metrics that help: time to detect, time to contain",
              duration: "approx. 10 min read",
              completed: false,
              locked: true,
            },
            {
              id: "sec4-m4-t8",
              type: "Peer-graded",
              title: "Tabletop exercise: incident summary",
              duration: "approx. 60 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec4-m4-t9",
              type: "Quiz",
              title: "Graded Quiz: Evidence and communication",
              duration: "approx. 15 min",
              completed: false,
              locked: true,
            },
            {
              id: "sec4-m4-t10",
              type: "Video",
              title: "Course wrap-up and what comes next",
              duration: "5 min",
              completed: false,
              locked: true,
            },
          ],
        },
      ],
    },
  ],
};
