import type { Course } from "@/lib/courses/kit";

/**
 * "SEO, GEO, and Organic Growth with AI": course 3 of the AI Augmented Digital Marketing
 * program. 43 topics, none done: the learner has not started it, so it opens on its
 * "Course Introduction" video. Module 4 is locked until Module 3 is complete.
 */
export const outline: Course = {
  id: "seo",
  slug: "seo-geo-and-organic-growth-with-ai",
  title: "SEO, GEO, and Organic Growth with AI",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Beginner",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 0,
  modulesCompleted: 0,
  modulesTotal: 4,
  modules: [
    {
      id: "seo-m1",
      label: "MODULE 01",
      title: "How Search Works & Keyword Strategy",
      topicsCompleted: 0,
      topicsTotal: 12,
      isCompleted: false,
      lessons: [
        {
          id: "seo-m1-l1",
          label: "Search engines and intent",
          topics: [
            {
              id: "seo-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "6 min",
              completed: false,
              active: true,
              transcript: [
                { id: "seo-m1-t1-ln1", ts: "0:00", text: "Welcome to course 3. This course is about being found without paying for the click: in search results and in the answers AI assistants give." },
                { id: "seo-m1-t1-ln2", ts: "0:17", text: "SEO, search engine optimization, is the work of making pages that a search engine can read, trust and rank for what people look for." },
                { id: "seo-m1-t1-ln3", ts: "0:35", text: "GEO, generative engine optimization, is newer. It is the work of being a source that an AI answer quotes or names." },
                { id: "seo-m1-t1-ln4", ts: "0:52", text: "The two share most of their foundations. Clear pages, real expertise and a good reputation help in both, so we teach them together." },
                { id: "seo-m1-t1-ln5", ts: "1:10", text: "Module 1 covers how search works and how to choose keywords. Module 2 covers the page and the site. Module 3 covers GEO, authority and measurement." },
                { id: "seo-m1-t1-ln6", ts: "1:30", text: "You will use an AI assistant throughout: to expand keyword lists, to draft content briefs and to check pages. You stay the editor." },
                { id: "seo-m1-t1-ln7", ts: "1:48", text: "In Module 4 you build an organic growth plan for one site. The first reading is next: how a search engine crawls, indexes and ranks." },
              ],
            },
            { id: "seo-m1-t2", type: "Reading", title: "How a search engine crawls, indexes and ranks", duration: "approx. 12 min read", completed: false },
            {
              id: "seo-m1-t3",
              type: "Video",
              title: "Reading a results page: links, snippets and AI answers",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "seo-m1-t3-ln1", ts: "0:00", text: "Search for something and look at the page before you click. That page is where you compete, and it holds far more than ten blue links. Let's read one from top to bottom." },
                { id: "seo-m1-t3-ln2", ts: "0:22", text: "Our query is how often to water a snake plant. At the top there may be an AI-generated answer: a short summary written by the search engine, with links to the pages it drew on." },
                { id: "seo-m1-t3-ln3", ts: "0:45", text: "Below it, or in its place, you may see a featured snippet: one passage lifted from a single page, shown with that page's title and address." },
                { id: "seo-m1-t3-ln4", ts: "1:02", text: "Then come related questions that open when you click them, and after those the classic organic results. Each has a title, an address and a short description." },
                { id: "seo-m1-t3-ln5", ts: "1:20", text: "Change the query to buy snake plant online and the page changes with it. Now there are ads marked as sponsored, a row of products with prices, and perhaps a map of nearby shops." },
                { id: "seo-m1-t3-ln6", ts: "1:43", text: "So the layout tells you what the search engine believes the person wants. An answer box means they want to know. Product rows mean they want to buy. A map means they want somewhere close." },
                { id: "seo-m1-t3-ln7", ts: "2:06", text: "Two lessons follow. Before you write for a keyword, search it and see what kind of page is winning. And the first organic result is no longer the top of the page, so being the quoted source matters too." },
                { id: "seo-m1-t3-ln8", ts: "2:32", text: "Next we give these differences a name: search intent." },
              ],
            },
            { id: "seo-m1-t4", type: "Reading", title: "Search intent: informational, navigational, commercial and transactional", duration: "approx. 12 min read", completed: false },
            { id: "seo-m1-t5", type: "Activity", title: "Label the intent behind ten queries", duration: "approx. 20 min", completed: false },
            {
              id: "seo-m1-t6",
              type: "Video",
              title: "Organic growth as a system: demand, content and authority",
              duration: "12 min",
              completed: false,
              transcript: [
                { id: "seo-m1-t6-ln1", ts: "0:00", text: "Organic growth is often taught as a checklist of fixes. It is easier to manage as a system with three parts: demand, content and authority. This video shows how they depend on one another." },
                { id: "seo-m1-t6-ln2", ts: "0:23", text: "Demand is what people already search for. You do not create it with SEO. You find it, through keyword research, and you choose the part of it your business can serve." },
                { id: "seo-m1-t6-ln3", ts: "0:44", text: "Content is your answer to that demand: the pages you publish. Each page should match one need and one intent, and be the most useful result a person could land on for it." },
                { id: "seo-m1-t6-ln4", ts: "1:06", text: "Authority is the reason a search engine believes you. It comes from other sites linking to you and mentioning you, and from a record of pages that satisfied the people who visited." },
                { id: "seo-m1-t6-ln5", ts: "1:27", text: "Take away any one part and the system stalls. Content with no demand is a well-written page nobody looks for. Demand with no content sends the visitor to a competitor." },
                { id: "seo-m1-t6-ln6", ts: "1:47", text: "Content with no authority sits on page five. And authority with thin content does not last, because visitors leave and the ranking follows them." },
                { id: "seo-m1-t6-ln7", ts: "2:03", text: "The parts also compound. A useful guide earns a link. The link lifts the whole site a little. The next guide ranks sooner. That is why organic results are slow at first and then speed up." },
                { id: "seo-m1-t6-ln8", ts: "2:27", text: "Keep the three words in mind through the course. Module 1 is about demand, Module 2 about content, and Module 3 about authority and how to measure all three." },
              ],
            },
          ],
        },
        {
          id: "seo-m1-l2",
          label: "Keyword research with AI",
          topics: [
            {
              id: "seo-m1-t7",
              type: "Video",
              title: "Building a seed list and expanding it with an AI assistant",
              duration: "16 min",
              completed: false,
              transcript: [
                { id: "seo-m1-t7-ln1", ts: "0:00", text: "Keyword research starts with a seed list: ten or so phrases that describe what you sell in the words a customer would use. In this video we build one and then expand it with an AI assistant." },
                { id: "seo-m1-t7-ln2", ts: "0:25", text: "Our example is the small online plant shop from the Handouts. Do not start from the product catalogue. Start from customers: what do they ask in emails, in reviews, at the counter?" },
                { id: "seo-m1-t7-ln3", ts: "0:46", text: "That gives seeds such as indoor plants for low light, plants safe for cats, how to repot a plant, and plant gift delivery. Ten phrases, each a different need." },
                { id: "seo-m1-t7-ln4", ts: "1:05", text: "Now the assistant. Give it the role, the business and one seed, and ask for thirty phrases a real person might type, grouped by what the person is trying to do." },
                { id: "seo-m1-t7-ln5", ts: "1:26", text: "Ask for variety by name: questions, comparisons, problems, phrases with a place or a season. Otherwise you get thirty versions of the same three words." },
                { id: "seo-m1-t7-ln6", ts: "1:43", text: "Read the list as an editor. Delete what the shop cannot serve. It does not sell outdoor trees, so those go. Mark what surprises you, such as plants for a north-facing bathroom." },
                { id: "seo-m1-t7-ln7", ts: "2:04", text: "One warning. If the assistant gives you search volumes, ignore them. It is not reading search data, and it will produce numbers that look precise and are invented." },
                { id: "seo-m1-t7-ln8", ts: "2:23", text: "The assistant widens the list. A keyword tool or your own search report measures it. Choosing from the measured list is the subject of the next reading." },
              ],
            },
            { id: "seo-m1-t8", type: "Reading", title: "Volume, difficulty and business value: choosing keywords", duration: "approx. 15 min read", completed: false },
            { id: "seo-m1-t9", type: "Reading", title: "Grouping keywords into topic clusters", duration: "approx. 12 min read", completed: false },
            { id: "seo-m1-t10", type: "Practice Assignment", title: "Practice Quiz: Intent and keywords", duration: "approx. 10 min", completed: false },
            { id: "seo-m1-t11", type: "Graded Assignment", title: "Assignment 01 · Keyword map", duration: "approx. 45 min", completed: false },
            { id: "seo-m1-t12", type: "Quiz", title: "Graded Quiz: Search and keyword strategy", duration: "approx. 15 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "seo-m2",
      label: "MODULE 02",
      title: "On-Page, Technical and Content SEO",
      topicsCompleted: 0,
      topicsTotal: 13,
      isCompleted: false,
      lessons: [
        {
          id: "seo-m2-l1",
          label: "On-page and content",
          topics: [
            {
              id: "seo-m2-t1",
              type: "Video",
              title: "What a page tells a search engine",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "seo-m2-t1-ln1", ts: "0:00", text: "A search engine does not see a page the way you do. It reads the code and the text, and from a handful of elements it works out what the page is about. Let's go through them in the order it meets them." },
                { id: "seo-m2-t1-ln2", ts: "0:29", text: "First the address. A URL that ends in guides, low light plants says something before a single word is read. A string of numbers says nothing." },
                { id: "seo-m2-t1-ln3", ts: "0:46", text: "Then the title tag. It is not shown on the page itself. It appears in the browser tab and usually as the headline of the search result, and it is the strongest single statement of the topic." },
                { id: "seo-m2-t1-ln4", ts: "1:11", text: "Next the headings. One main heading says what the page is. The subheadings are its outline. If you read only the headings, you should still understand the page." },
                { id: "seo-m2-t1-ln5", ts: "1:30", text: "Then the body. The search engine looks at the opening lines, at the words and related terms used throughout, and at whether the page answers the question its title raises." },
                { id: "seo-m2-t1-ln6", ts: "1:50", text: "Images are read through their file names and their alternative text. A photo called image four seven tells it nothing. Low light snake plant, with a one-line description, does." },
                { id: "seo-m2-t1-ln7", ts: "2:09", text: "Links complete the picture: which pages this one points to, and which words are used in the link text. Click here carries no meaning. Guide to repotting does." },
                { id: "seo-m2-t1-ln8", ts: "2:28", text: "None of this is a trick. Each element answers the same question for a machine that a reader answers at a glance: what is this page, and whom is it for?" },
              ],
            },
            { id: "seo-m2-t2", type: "Reading", title: "Titles, headings and meta descriptions that earn the click", duration: "approx. 12 min read", completed: false },
            { id: "seo-m2-t3", type: "Video", title: "Writing a content brief from a keyword cluster", duration: "16 min", completed: false },
            { id: "seo-m2-t4", type: "Reading", title: "Helpful content: experience, expertise and trust", duration: "approx. 15 min read", completed: false },
            { id: "seo-m2-t5", type: "Activity", title: "Audit one page against an on-page checklist", duration: "approx. 25 min", completed: false },
            { id: "seo-m2-t6", type: "Reading", title: "Internal links and site structure", duration: "approx. 10 min read", completed: false },
          ],
        },
        {
          id: "seo-m2-l2",
          label: "Technical foundations",
          topics: [
            {
              id: "seo-m2-t7",
              type: "Video",
              title: "Crawling and indexing: robots rules, sitemaps and canonical tags",
              duration: "18 min",
              completed: false,
              transcript: [
                { id: "seo-m2-t7-ln1", ts: "0:00", text: "Three small files and tags tell a search engine where it may go on your site, what you would like it to find, and which version of a page counts. Get them wrong and good pages disappear." },
                { id: "seo-m2-t7-ln2", ts: "0:25", text: "The first is the robots file, a plain text file at the root of the site. It tells crawlers which folders they may not fetch. Shops use it to keep crawlers out of cart pages and internal search results." },
                { id: "seo-m2-t7-ln3", ts: "0:51", text: "It is a blunt tool. One short rule can block the whole site. That rule is common on test versions of a site, and it sometimes goes live with the launch. Check it first when a site vanishes from search." },
                { id: "seo-m2-t7-ln4", ts: "1:18", text: "Robots rules stop crawling, not indexing. To keep a page out of the index, let the crawler in and put a noindex tag on the page itself." },
                { id: "seo-m2-t7-ln5", ts: "1:36", text: "The second is the sitemap: a list of the addresses you want indexed. It is an invitation, not a command. List only pages that work, that are not blocked, and that are the main version." },
                { id: "seo-m2-t7-ln6", ts: "1:59", text: "The third is the canonical tag. A shop often shows one product at several addresses: with a colour filter, with a tracking code, in two categories. The tag names the address that should rank." },
                { id: "seo-m2-t7-ln7", ts: "2:22", text: "Without it, the search engine picks for you, and links to the other versions are split. With it, they count toward one page." },
                { id: "seo-m2-t7-ln8", ts: "2:37", text: "The three must agree. A page in the sitemap that is blocked by robots, or that points its canonical somewhere else, sends mixed signals. In the audit video you will learn to find those." },
              ],
            },
            { id: "seo-m2-t8", type: "Reading", title: "Page speed and loading metrics in plain terms", duration: "approx. 12 min read", completed: false },
            { id: "seo-m2-t9", type: "Video", title: "Structured data: describing a page to machines", duration: "14 min", completed: false },
            { id: "seo-m2-t10", type: "Reading", title: "Mobile-first and accessible pages", duration: "approx. 10 min read", completed: false },
            { id: "seo-m2-t11", type: "Practice Assignment", title: "Practice Quiz: On-page and technical SEO", duration: "approx. 10 min", completed: false },
            { id: "seo-m2-t12", type: "Video", title: "Running a small site audit with a crawler", duration: "20 min", completed: false },
            { id: "seo-m2-t13", type: "Graded Assignment", title: "Assignment 02 · On-page audit", duration: "approx. 45 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "seo-m3",
      label: "MODULE 03",
      title: "GEO, Authority and Measurement",
      topicsCompleted: 0,
      topicsTotal: 12,
      isCompleted: false,
      lessons: [
        {
          id: "seo-m3-l1",
          label: "Generative engine optimization",
          topics: [
            { id: "seo-m3-t1", type: "Video", title: "How AI answer engines choose their sources", duration: "16 min", completed: false },
            { id: "seo-m3-t2", type: "Reading", title: "GEO and SEO: what changes and what stays", duration: "approx. 15 min read", completed: false },
            {
              id: "seo-m3-t3",
              type: "Video",
              title: "Writing content an AI answer can quote",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "seo-m3-t3-ln1", ts: "0:00", text: "An AI answer is assembled from passages. In this video we take one paragraph from the plant shop's blog and rewrite it so that it can be lifted out and still make sense." },
                { id: "seo-m3-t3-ln2", ts: "0:22", text: "Here is the original. It opens with a memory of the writer's grandmother, wanders through three sentences, and mentions watering every two to three weeks near the end. A person may enjoy it. A machine cannot find the answer." },
                { id: "seo-m3-t3-ln3", ts: "0:48", text: "Step one: put the answer first. Water a snake plant every two to three weeks, and let the soil dry out fully between waterings. Anyone who reads only that line has what they came for." },
                { id: "seo-m3-t3-ln4", ts: "1:11", text: "Step two: make the passage stand alone. Name the subject. Say a snake plant, not it. A lifted sentence loses the paragraph around it, so pronouns that point backwards become riddles." },
                { id: "seo-m3-t3-ln5", ts: "1:32", text: "Step three: be specific, and say where it comes from. Every two to three weeks is quotable. Not too often is not. If a figure comes from your own test or a named source, say so in the sentence." },
                { id: "seo-m3-t3-ln6", ts: "1:58", text: "Step four: use the question as the heading. How often should I water a snake plant, followed directly by the answer, mirrors the way people ask an assistant." },
                { id: "seo-m3-t3-ln7", ts: "2:17", text: "Then keep the grandmother, if she earns her place, below the answer. Structure for the machine does not have to cost you the voice." },
                { id: "seo-m3-t3-ln8", ts: "2:33", text: "An assistant can help you find passages that bury the answer. Ask it to list every paragraph whose main point is not in its first sentence, then rewrite those yourself." },
              ],
            },
            { id: "seo-m3-t4", type: "Activity", title: "Test how AI assistants describe a brand", duration: "approx. 25 min", completed: false },
            { id: "seo-m3-t5", type: "Reading", title: "Entities, mentions and being cited", duration: "approx. 12 min read", completed: false },
          ],
        },
        {
          id: "seo-m3-l2",
          label: "Authority and measurement",
          topics: [
            { id: "seo-m3-t6", type: "Video", title: "Earning links: digital PR and useful resources", duration: "16 min", completed: false },
            { id: "seo-m3-t7", type: "Reading", title: "Link quality and the schemes to avoid", duration: "approx. 10 min read", completed: false },
            { id: "seo-m3-t8", type: "Video", title: "Local search: profiles, reviews and citations", duration: "12 min", completed: false },
            { id: "seo-m3-t9", type: "Reading", title: "Measuring organic growth: impressions, clicks and conversions", duration: "approx. 15 min read", completed: false },
            { id: "seo-m3-t10", type: "Practice Assignment", title: "Practice Quiz: GEO and authority", duration: "approx. 10 min", completed: false },
            { id: "seo-m3-t11", type: "Video", title: "Reading a search performance report", duration: "18 min", completed: false },
            { id: "seo-m3-t12", type: "Quiz", title: "Graded Quiz: GEO, authority and measurement", duration: "approx. 15 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "seo-m4",
      label: "MODULE 04",
      title: "Final Project, Assessment, and Wrap-Up",
      topicsCompleted: 0,
      topicsTotal: 6,
      isCompleted: false,
      lessons: [
        {
          id: "seo-m4-l1",
          label: "Final project",
          topics: [
            { id: "seo-m4-t1", type: "Reading", title: "Final project brief: an organic growth plan", duration: "approx. 15 min read", completed: false, locked: true },
            { id: "seo-m4-t2", type: "Video", title: "Planning your organic growth plan", duration: "14 min", completed: false, locked: true },
            { id: "seo-m4-t3", type: "Project", title: "Final Project: Organic growth plan", duration: "approx. 2 h", completed: false, locked: true },
            { id: "seo-m4-t4", type: "Peer Review", title: "Review two organic growth plans", duration: "approx. 20 min", completed: false, locked: true },
          ],
        },
        {
          id: "seo-m4-l2",
          label: "Assessment and wrap-up",
          topics: [
            { id: "seo-m4-t5", type: "Quiz", title: "Final Assessment", duration: "approx. 20 min", completed: false, locked: true },
            { id: "seo-m4-t6", type: "Video", title: "Course wrap-up and next steps", duration: "5 min", completed: false, locked: true },
          ],
        },
      ],
    },
  ],
};
