import type { CourseContent } from "@/lib/courses/kit";

export const content: CourseContent = {
  byline: {
    author: "Helena Brandt",
    role: "Lead instructor · Project Management with AI Tools",
    updated: "September 2026",
  },
  quiz: [
    {
      question: "A sponsor asks for more scope with the same deadline and the same team. What does the project manager owe them?",
      platformPrompt: "Choose the correct option",
      explanation:
        "Scope, time, cost and quality move together. The project manager's job is to show the trade-off and let the sponsor choose, not to absorb the change silently.",
      options: [
        {
          id: "a",
          label: "The options: what moves if the scope grows, and what each choice costs",
          correct: true,
          feedback: "Correct. The sponsor decides, with the trade-off in front of them.",
        },
        { id: "b", label: "A yes, and overtime for the team", feedback: "That hides the cost in the team's evenings, and usually in quality too." },
        { id: "c", label: "A no, because the scope was signed off", feedback: "Scope can change. What cannot happen is a change with no decision about time, cost or quality." },
        { id: "d", label: "A new plan written by an AI assistant", feedback: "An assistant can draft the options. It cannot choose between them." },
      ],
    },
    {
      question: "Which of these is a sound use of an AI assistant in project work?",
      platformPrompt: "Choose the correct option",
      explanation:
        "An assistant is good at first drafts and at lists you then check. Commitments, priorities and anything that needs facts it was not given stay with people.",
      options: [
        { id: "a", label: "Deciding which stakeholder's request comes first", feedback: "Priority is a decision with consequences. It belongs to the people who answer for it." },
        {
          id: "b",
          label: "Drafting a first list of tasks from a scope statement, for the team to correct",
          correct: true,
          feedback: "Correct. A draft to react to saves time, as long as someone who knows the work corrects it.",
        },
        { id: "c", label: "Confirming that a supplier will deliver on time", feedback: "It has no way of knowing. Only the supplier can confirm that." },
        { id: "d", label: "Committing the team to a delivery date", feedback: "A commitment is made by the people who do the work." },
      ],
    },
    {
      question: "What makes a risk register useful after the first week of a project?",
      explanation:
        "A register is used when each risk has an owner and a next action, and when it is read again on a fixed rhythm. A long list with no owners is a document, not a tool.",
      options: [
        { id: "a", label: "It lists every risk anyone can think of", feedback: "Length is not the point. Fifty risks nobody owns help less than eight that are managed." },
        { id: "b", label: "Each risk has an owner, a response and a date it is next reviewed", correct: true, feedback: "Correct. Owner, response and review date are what keep it alive." },
        { id: "c", label: "It is approved by the sponsor", feedback: "Approval happens once. Use happens every week." },
        { id: "d", label: "It was generated by an AI assistant", feedback: "An assistant can suggest risks. It cannot own them or act on them." },
      ],
    },
  ],
  articles: {
    "pma-m2-t2": {
      lede: "A work breakdown structure, or WBS, splits the scope into pieces small enough to estimate and assign. An AI assistant can draft one in a minute. This reading shows how to ask for it, and the four checks that turn the draft into something a team can plan from.",
      sections: [
        {
          heading: "Give the assistant the scope, not the title",
          paragraphs: [
            "“Create a WBS for a website redesign” returns the same generic tree for every website in the world. The assistant can only break down what you give it, so give it the scope statement: what is in, what is out, the constraints and the definition of done.",
            "Ask for deliverables, not activities. “Checkout page, tested on three browsers” is a deliverable: you can tell whether it exists. “Work on checkout” is an activity, and it is never finished. Ask for two or three levels and for a numbered outline, so that each line can be referred to in the meeting.",
          ],
        },
        {
          heading: "Check it against the 100% rule",
          paragraphs: [
            "The children of a branch must add up to the whole of the parent: nothing missing, nothing extra. Assistants break this rule in both directions. They leave out the dull work (data migration, approvals, training, handover) and they add work nobody asked for, because it usually belongs to projects of this kind.",
            "Read each branch with the scope statement beside it and ask two questions. Is there anything in the scope that no line covers? Is there any line the scope does not ask for? Mark both kinds. The second kind is how scope grows without a decision.",
          ],
        },
        {
          heading: "Ask what it assumed",
          paragraphs: [
            "Follow the draft with one more prompt: “List the assumptions you made to produce this breakdown.” The answer is often more useful than the tree. It will tell you that it assumed one language, an existing design system or a single approver. Each assumption is a question for the team or the client.",
            "Then take the draft to the people who will do the work. They will split lines that are too large to estimate, merge lines that are one afternoon's work, and name the dependency the assistant could not see. A WBS the team has corrected is theirs. One you hand down is only a list.",
          ],
        },
      ],
      pullQuote: {
        text: "The assistant drafts the tree. The team makes it true.",
        attribution: "Course notes, Module 2",
      },
      takeaways: [
        "Prompt with the scope statement, the exclusions and the definition of done.",
        "Ask for deliverables you can check, in a numbered outline.",
        "Apply the 100% rule to every branch: look for what is missing and for what was added.",
        "Ask for the assumptions, then let the team correct the draft.",
      ],
    },
  },
  quizzes: {
    "pma-m2-t6": [
      {
        question: "A three-point estimate for a task is 4 days optimistic, 6 days most likely and 14 days pessimistic. What does the wide range tell you?",
        platformPrompt: "Choose the correct option",
        hints: [
          "Compare the distance from 6 down to 4 with the distance from 6 up to 14.",
          "A range is information about uncertainty, not about effort.",
        ],
        explanation:
          "The pessimistic value sits far from the most likely one, so the task holds an unknown. That is a reason to investigate or split the task before the sprint, not to average the numbers and move on.",
        reviewTopicId: "pma-m2-t3",
        reviewTopicTitle: "Estimating: three-point estimates and reference classes",
        options: [
          { id: "a", label: "The estimator was careless", feedback: "A wide range is an honest answer about something not yet known." },
          {
            id: "b",
            label: "The task holds an unknown that is worth investigating or splitting out",
            correct: true,
            feedback: "Correct. The range points at the uncertainty. Reduce it before you commit.",
          },
          { id: "c", label: "The task will take 14 days", feedback: "The pessimistic value is a possibility, not a forecast." },
          { id: "d", label: "The task should be given to a faster person", feedback: "The range describes the work, not the person." },
        ],
      },
      {
        question: "An AI assistant drafts a WBS for your project. Which check comes first?",
        platformPrompt: "Choose the correct option",
        explanation:
          "The 100% rule: the breakdown must cover the whole scope and nothing outside it. Formatting and estimates only matter once the list of work is right.",
        reviewTopicId: "pma-m2-t2",
        reviewTopicTitle: "Drafting a WBS with an AI assistant, and checking it",
        options: [
          { id: "a", label: "That every line has an estimate", feedback: "Estimates come after you trust the list of work." },
          { id: "b", label: "That the numbering is consistent", feedback: "Useful in a meeting, but it does not tell you whether the work is right." },
          {
            id: "c",
            label: "That it covers all of the scope and adds nothing the scope does not ask for",
            correct: true,
            feedback: "Correct. Missing work and extra work are the two errors a draft makes most.",
          },
          { id: "d", label: "That it has exactly three levels", feedback: "Depth depends on the project. There is no correct number of levels." },
        ],
      },
      {
        question: "On a critical path, where does a schedule buffer protect the finish date best?",
        explanation:
          "Padding hidden in each task tends to be used up whether it is needed or not. One visible buffer at the end of the critical path absorbs the delays that do happen and shows how much protection is left.",
        reviewTopicId: "pma-m2-t5",
        reviewTopicTitle: "Dependencies, critical path and buffers",
        options: [
          { id: "a", label: "Spread evenly inside every task", feedback: "Hidden padding is spent task by task and cannot be shared." },
          {
            id: "b",
            label: "As one visible buffer at the end of the critical path",
            correct: true,
            feedback: "Correct. It is shared by the whole path, and everyone can see how much is left.",
          },
          { id: "c", label: "On the tasks that are not on the critical path", feedback: "Those tasks already have float. The finish date depends on the critical path." },
          { id: "d", label: "Nowhere: a good plan needs no buffer", feedback: "A plan with no buffer assumes nothing will go wrong." },
        ],
      },
    ],
  },
  assignments: {
    "pma-m2-t8": {
      brief:
        "Prepare the plan for a two-week sprint, using the case-study team and backlog in the Downloads tab or your own team's (remove client names and anything confidential). Use an AI assistant to prepare the capacity, three candidate sprint goals and the task breakdown, as in the video before this assignment. Then correct its draft and mark every line it wrote. Submit your work as a PDF or DOCX.",
      requirements: [
        "The sprint goal in one sentence, and the capacity in hours with how you calculated it",
        "The selected stories split into tasks with estimates, the assistant's lines marked",
        "The assumptions the assistant made, and what you changed in its draft and why",
        "Counts toward your final grade",
      ],
    },
  },
  ora: {},
};
