import type { Course } from "@/lib/courses/kit";

/**
 * "Project Management with AI Tools": a stand-alone course on My Learning, in progress.
 * 40 topics, 14 done: Module 1 complete and 6 of 8 in Module 2; the learner is on the
 * sprint planning video, the last one before Assignment 01.
 */
export const outline: Course = {
  id: "pma",
  slug: "project-management-with-ai-tools",
  title: "Project Management with AI Tools",
  provider: "SkillUp",
  courseType: "Course",
  difficulty: "Intermediate",
  deliveryMode: "Flexible Learning",
  overallProgressPct: 35,
  modulesCompleted: 1,
  modulesTotal: 5,
  modules: [
    {
      id: "pma-m1",
      label: "MODULE 01",
      title: "Project Foundations and Where AI Fits",
      topicsCompleted: 8,
      topicsTotal: 8,
      isCompleted: true,
      lessons: [
        {
          id: "pma-m1-l1",
          label: "The shape of a project",
          topics: [
            {
              id: "pma-m1-t1",
              type: "Video",
              title: "Course Introduction",
              duration: "5 min",
              completed: true,
              transcript: [
                { id: "pma-m1-t1-ln1", ts: "0:00", text: "Welcome to Project Management with AI Tools. This is a course about running projects well. The AI assistant is a tool in it, and the project manager stays in charge." },
                { id: "pma-m1-t1-ln2", ts: "0:16", text: "A project is temporary work with a defined result: a launch, a migration, an event. It ends. That is what separates it from operations." },
                { id: "pma-m1-t1-ln3", ts: "0:31", text: "Module 1 covers the foundations: the trade-offs you manage, the main ways of delivering, and what an assistant can and cannot do for you." },
                { id: "pma-m1-t1-ln4", ts: "0:48", text: "Module 2 is planning: breaking down scope, estimating, scheduling and preparing a sprint. Module 3 covers risks, stakeholders and communication." },
                { id: "pma-m1-t1-ln5", ts: "1:05", text: "Module 4 is about tracking progress, reporting it honestly and using AI tools responsibly with client data. Module 5 is the final project." },
                { id: "pma-m1-t1-ln6", ts: "1:22", text: "For that project you plan a product launch and submit a plan pack, which two peers review. Before it there are two graded assignments and three graded quizzes, and after it a final assessment." },
                { id: "pma-m1-t1-ln7", ts: "1:40", text: "You can follow the course with any general-purpose AI assistant. We name no product, because the method matters more than the tool." },
                { id: "pma-m1-t1-ln8", ts: "1:54", text: "One rule holds for the whole course: the assistant drafts, you check, and your name is on the plan." },
              ],
            },
            { id: "pma-m1-t2", type: "Reading", title: "Scope, time, cost and quality: the trade-offs a project manager owns", duration: "approx. 12 min read", completed: true },
            {
              id: "pma-m1-t3",
              type: "Video",
              title: "Predictive, agile and hybrid delivery",
              duration: "14 min",
              completed: true,
              transcript: [
                { id: "pma-m1-t3-ln1", ts: "0:00", text: "There are two families of delivery approach, and most real projects sit somewhere between them." },
                { id: "pma-m1-t3-ln2", ts: "0:13", text: "Predictive delivery, often called waterfall, plans the whole project up front: requirements, design, build, test, release. Change is handled through a formal request." },
                { id: "pma-m1-t3-ln3", ts: "0:31", text: "It fits work where the requirements are stable and a mistake is expensive to undo: a building, a regulated product, a fixed-price contract." },
                { id: "pma-m1-t3-ln4", ts: "0:47", text: "Agile delivery works in short cycles. The team builds a small piece, shows it, learns from it and plans the next cycle. The scope is expected to change." },
                { id: "pma-m1-t3-ln5", ts: "1:04", text: "It fits work where you find out what is needed by trying, which describes most software and most new products." },
                { id: "pma-m1-t3-ln6", ts: "1:18", text: "Hybrid delivery combines them. A common pattern is predictive at the edges, with fixed milestones, budget and contract, and agile in the middle, where the team builds in sprints." },
                { id: "pma-m1-t3-ln7", ts: "1:38", text: "To choose, ask three questions. How well do we know the requirements? How costly is a late change? How often can the customer give feedback?" },
                { id: "pma-m1-t3-ln8", ts: "1:55", text: "Whatever you choose, say it plainly at kickoff. Many conflicts on projects come from a sponsor expecting a fixed plan and a team working in sprints." },
              ],
            },
            { id: "pma-m1-t4", type: "Reading", title: "What AI assistants can and cannot do for a project manager", duration: "approx. 15 min read", completed: true },
          ],
        },
        {
          id: "pma-m1-l2",
          label: "Working with an AI assistant",
          topics: [
            {
              id: "pma-m1-t5",
              type: "Video",
              title: "Giving an assistant project context",
              duration: "16 min",
              completed: true,
              transcript: [
                { id: "pma-m1-t5-ln1", ts: "0:00", text: "An AI assistant knows a lot about projects in general and nothing about yours. The quality of what it gives back depends on the context you give it." },
                { id: "pma-m1-t5-ln2", ts: "0:16", text: "Ask it to “write a project plan for a website” and you get a plan for an average website, with an average team that does not exist." },
                { id: "pma-m1-t5-ln3", ts: "0:31", text: "Give it five things instead. First, the goal and how success will be measured. Second, the scope, including what is out of scope." },
                { id: "pma-m1-t5-ln4", ts: "0:47", text: "Third, the constraints: the deadline, the budget, the fixed dates. Fourth, the team: roles, availability and who decides. Fifth, what is already known or agreed." },
                { id: "pma-m1-t5-ln5", ts: "1:06", text: "Then say what you want back and in what form: a table, a list of ten items, a draft email of under a hundred and fifty words." },
                { id: "pma-m1-t5-ln6", ts: "1:21", text: "Keep this context in one short document, a project brief, and paste it at the start of each conversation. Update it when a decision changes." },
                { id: "pma-m1-t5-ln7", ts: "1:37", text: "Ask the assistant to list what it assumed and what it would need to know. The gaps it names are often gaps in your own brief." },
                { id: "pma-m1-t5-ln8", ts: "1:52", text: "Before you paste anything, remove client names, personal data and anything under a confidentiality agreement. Module 4 covers this in detail." },
                { id: "pma-m1-t5-ln9", ts: "2:07", text: "In the activity that follows you turn a kickoff email into a one-page charter, using exactly this context." },
              ],
            },
            { id: "pma-m1-t6", type: "Activity", title: "Turn a kickoff email into a one-page charter", duration: "approx. 25 min", completed: true },
            { id: "pma-m1-t7", type: "Practice Assignment", title: "Practice Quiz: Project foundations", duration: "approx. 8 min", completed: true },
            { id: "pma-m1-t8", type: "Quiz", title: "Graded Quiz: Foundations and AI basics", duration: "approx. 10 min", completed: true },
          ],
        },
      ],
    },
    {
      id: "pma-m2",
      label: "MODULE 02",
      title: "Planning and Estimating with AI",
      topicsCompleted: 6,
      topicsTotal: 8,
      isCompleted: false,
      lessons: [
        {
          id: "pma-m2-l1",
          label: "From scope to backlog",
          topics: [
            {
              id: "pma-m2-t1",
              type: "Video",
              title: "Breaking scope into a work breakdown structure",
              duration: "15 min",
              completed: true,
              transcript: [
                { id: "pma-m2-t1-ln1", ts: "0:00", text: "A work breakdown structure, or WBS, is a tree. At the top is the whole project. Below it are the deliverables, and below those the pieces of work needed to produce them." },
                { id: "pma-m2-t1-ln2", ts: "0:18", text: "It answers one question: what is all the work? It does not say when the work happens or who does it. Those come later, and they depend on this." },
                { id: "pma-m2-t1-ln3", ts: "0:33", text: "Break down by deliverable, not by department or phase. “Checkout page” is a deliverable. “Development” is an activity that hides ten of them." },
                { id: "pma-m2-t1-ln4", ts: "0:49", text: "The key rule is the 100% rule. The children of any box must add up to all of the parent, and to nothing more. If something is missing from the tree, it is missing from the plan." },
                { id: "pma-m2-t1-ln5", ts: "1:08", text: "Stop breaking down when a piece can be estimated with confidence and given to one owner. That lowest level is called a work package." },
                { id: "pma-m2-t1-ln6", ts: "1:23", text: "A rough guide for size: a work package takes between one day and two weeks of effort. Smaller, and you are writing a to-do list. Larger, and you cannot see inside it." },
                { id: "pma-m2-t1-ln7", ts: "1:41", text: "Do not forget the work nobody thinks of as a deliverable: project management itself, testing, training, handover. They take real time." },
                { id: "pma-m2-t1-ln8", ts: "1:56", text: "In agile work the same idea appears as epics, stories and tasks. The next reading shows how to draft the tree with an assistant and how to check its draft." },
              ],
            },
            { id: "pma-m2-t2", type: "Reading", title: "Drafting a WBS with an AI assistant, and checking it", duration: "approx. 15 min read", completed: true },
            {
              id: "pma-m2-t3",
              type: "Video",
              title: "Estimating: three-point estimates and reference classes",
              duration: "16 min",
              completed: true,
              transcript: [
                { id: "pma-m2-t3-ln1", ts: "0:00", text: "An estimate is a range with a level of confidence. When you give a single number, people hear a promise." },
                { id: "pma-m2-t3-ln2", ts: "0:13", text: "The three-point estimate makes the range visible. For each piece of work, ask for three figures: optimistic, most likely and pessimistic." },
                { id: "pma-m2-t3-ln3", ts: "0:28", text: "The usual weighted average is the optimistic figure, plus four times the most likely, plus the pessimistic, divided by six." },
                { id: "pma-m2-t3-ln4", ts: "0:43", text: "Take four, six and fourteen days. Four plus twenty-four plus fourteen is forty-two. Divided by six, that gives seven days. The long tail pulls the estimate above the most likely value." },
                { id: "pma-m2-t3-ln5", ts: "1:03", text: "The gap between optimistic and pessimistic is information as well. A wide gap means the task is poorly understood. Break it down, or find out more, before you commit." },
                { id: "pma-m2-t3-ln6", ts: "1:20", text: "The second technique looks outward. A reference class is a set of similar past projects. You ask how long they took in reality, and you start from that." },
                { id: "pma-m2-t3-ln7", ts: "1:37", text: "If the last five integrations in your company took eight to twelve weeks, a plan that says four needs a very good reason." },
                { id: "pma-m2-t3-ln8", ts: "1:51", text: "An assistant can run the arithmetic and suggest what to compare with. It has no access to your team's history unless you provide it, so bring the real figures." },
                { id: "pma-m2-t3-ln9", ts: "2:06", text: "In the activity that follows you estimate a backlog of twelve items using both techniques." },
              ],
            },
            { id: "pma-m2-t4", type: "Activity", title: "Estimate a backlog of twelve items", duration: "approx. 25 min", completed: true },
          ],
        },
        {
          id: "pma-m2-l2",
          label: "Schedules and sprints",
          topics: [
            { id: "pma-m2-t5", type: "Reading", title: "Dependencies, critical path and buffers", duration: "approx. 18 min read", completed: true },
            { id: "pma-m2-t6", type: "Practice Assignment", title: "Practice Quiz: Planning and estimating", duration: "approx. 10 min", completed: true },
            {
              id: "pma-m2-t7",
              type: "Video",
              title: "AI-assisted sprint planning",
              duration: "18 min",
              completed: false,
              active: true,
              transcript: [
                { id: "pma-m2-t7-ln1", ts: "0:00", text: "Sprint planning answers two questions: what can the team finish in the next two weeks, and how will it get done." },
                { id: "pma-m2-t7-ln2", ts: "0:15", text: "An AI assistant can prepare the meeting. It cannot commit for the team. Keep that line clear and it saves you an hour." },
                { id: "pma-m2-t7-ln3", ts: "0:32", text: "Start with capacity. Give the assistant the working days of each person, minus leave and support duty, and ask for the hours available. Check the sum yourself." },
                { id: "pma-m2-t7-ln4", ts: "0:54", text: "Next, the sprint goal. Paste the top of the backlog and ask for three candidate goals of one sentence each. The product owner picks one, or writes a fourth." },
                { id: "pma-m2-t7-ln5", ts: "1:15", text: "Then ask the assistant to split each selected story into tasks and to list what it assumed. The assumptions are the useful part: they are the questions for the meeting." },
                { id: "pma-m2-t7-ln6", ts: "1:38", text: "Compare the estimate with your last three sprints. If the plan needs more than the team has ever delivered, the plan is wrong, however tidy the list looks." },
                { id: "pma-m2-t7-ln7", ts: "1:58", text: "Finish in the room: the team reads the plan, changes it and commits. In the assignment that follows you prepare a sprint plan this way and mark every line the assistant drafted." },
              ],
            },
            { id: "pma-m2-t8", type: "Graded Assignment", title: "Assignment 01 · Sprint plan with an AI assistant", duration: "approx. 45 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "pma-m3",
      label: "MODULE 03",
      title: "Risks, Stakeholders and Communication",
      topicsCompleted: 0,
      topicsTotal: 8,
      isCompleted: false,
      lessons: [
        {
          id: "pma-m3-l1",
          label: "Risks and stakeholders",
          topics: [
            {
              id: "pma-m3-t1",
              type: "Video",
              title: "Building a risk register that gets used",
              duration: "14 min",
              completed: false,
              transcript: [
                { id: "pma-m3-t1-ln1", ts: "0:00", text: "A risk is something that may happen and would affect the project if it did. A risk register is the list of those things and what you are doing about each." },
                { id: "pma-m3-t1-ln2", ts: "0:16", text: "Most registers are filled in at kickoff and never opened again. The difference between that and a useful one is small and specific." },
                { id: "pma-m3-t1-ln3", ts: "0:30", text: "First, write each risk as cause, event and effect. “Because the supplier has one engineer on our account, the integration may slip, which would move the launch date.”" },
                { id: "pma-m3-t1-ln4", ts: "0:49", text: "Compare that with “supplier risk”. The long version tells you what to watch and what to do. The short one tells you nothing." },
                { id: "pma-m3-t1-ln5", ts: "1:02", text: "Second, score probability and impact, each on a simple scale from one to five. The score is for ranking. Do not pretend it is precise." },
                { id: "pma-m3-t1-ln6", ts: "1:17", text: "Third, give every risk one owner by name and a response: avoid it, reduce it, transfer it or accept it. Add a trigger, the early sign that it is starting to happen." },
                { id: "pma-m3-t1-ln7", ts: "1:35", text: "Fourth, keep it short. Ten to fifteen live risks that the team recognises are better than sixty that nobody reads." },
                { id: "pma-m3-t1-ln8", ts: "1:49", text: "And review it on a rhythm: five minutes in the weekly meeting, top five only. Close what has passed, add what is new and move what has changed." },
                { id: "pma-m3-t1-ln9", ts: "2:05", text: "The next reading uses an assistant to find the risks your team has not thought of." },
              ],
            },
            { id: "pma-m3-t2", type: "Reading", title: "Using an AI assistant to surface risks you have not thought of", duration: "approx. 15 min read", completed: false },
            { id: "pma-m3-t3", type: "Activity", title: "Score ten risks by probability and impact", duration: "approx. 20 min", completed: false },
            { id: "pma-m3-t4", type: "Video", title: "Stakeholder mapping: power, interest and what each one needs", duration: "15 min", completed: false },
          ],
        },
        {
          id: "pma-m3-l2",
          label: "Communication",
          topics: [
            { id: "pma-m3-t5", type: "Reading", title: "Status reports people read", duration: "approx. 12 min read", completed: false },
            { id: "pma-m3-t6", type: "Video", title: "Meeting notes, decisions and actions with an AI assistant", duration: "16 min", completed: false },
            { id: "pma-m3-t7", type: "Practice Assignment", title: "Practice Quiz: Risk and communication", duration: "approx. 10 min", completed: false },
            { id: "pma-m3-t8", type: "Quiz", title: "Graded Quiz: Risks and stakeholders", duration: "approx. 12 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "pma-m4",
      label: "MODULE 04",
      title: "Tracking, Reporting and Responsible Use",
      topicsCompleted: 0,
      topicsTotal: 8,
      isCompleted: false,
      lessons: [
        {
          id: "pma-m4-l1",
          label: "Tracking delivery",
          topics: [
            { id: "pma-m4-t1", type: "Video", title: "Burndown, velocity and earned value in plain terms", duration: "16 min", completed: false },
            { id: "pma-m4-t2", type: "Reading", title: "Forecasting a finish date from real progress", duration: "approx. 15 min read", completed: false },
            { id: "pma-m4-t3", type: "Video", title: "Automating routine updates without losing the facts", duration: "14 min", completed: false },
            { id: "pma-m4-t4", type: "Activity", title: "Find the three errors in an AI-written status report", duration: "approx. 20 min", completed: false },
          ],
        },
        {
          id: "pma-m4-l2",
          label: "Change and responsible use",
          topics: [
            { id: "pma-m4-t5", type: "Reading", title: "Confidential data, client contracts and AI tools", duration: "approx. 14 min read", completed: false },
            { id: "pma-m4-t6", type: "Video", title: "When the plan changes: change requests and replanning", duration: "15 min", completed: false },
            { id: "pma-m4-t7", type: "Graded Assignment", title: "Assignment 02 · Risk register and status report", duration: "approx. 50 min", completed: false },
            { id: "pma-m4-t8", type: "Quiz", title: "Graded Quiz: Tracking and reporting", duration: "approx. 12 min", completed: false },
          ],
        },
      ],
    },
    {
      id: "pma-m5",
      label: "MODULE 05",
      title: "Final Project and Wrap-Up",
      topicsCompleted: 0,
      topicsTotal: 8,
      isCompleted: false,
      lessons: [
        {
          id: "pma-m5-l1",
          label: "Final project",
          topics: [
            { id: "pma-m5-t1", type: "Reading", title: "Final project brief: plan a product launch", duration: "approx. 12 min read", completed: false, locked: true },
            { id: "pma-m5-t2", type: "Video", title: "Planning your project pack", duration: "12 min", completed: false, locked: true },
            { id: "pma-m5-t3", type: "Project", title: "Final Project: Project plan pack", duration: "approx. 1 h 30 min", completed: false, locked: true },
            { id: "pma-m5-t4", type: "Peer Review", title: "Review two project plan packs", duration: "approx. 25 min", completed: false, locked: true },
          ],
        },
        {
          id: "pma-m5-l2",
          label: "Retrospective and wrap-up",
          topics: [
            { id: "pma-m5-t5", type: "Video", title: "Running a retrospective that changes something", duration: "14 min", completed: false, locked: true },
            { id: "pma-m5-t6", type: "Reading", title: "Lessons learned: what to keep for the next project", duration: "approx. 10 min read", completed: false, locked: true },
            { id: "pma-m5-t7", type: "Quiz", title: "Final Assessment", duration: "approx. 15 min", completed: false, locked: true },
            { id: "pma-m5-t8", type: "Video", title: "Course wrap-up and next steps", duration: "5 min", completed: false, locked: true },
          ],
        },
      ],
    },
  ],
};
